INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 1, 'V. Natal Pertama');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 2, '12. Penampakan Para Malaikat');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 3, 'Lukas 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 5, '8 Di daerah itu ada gembala-gembala yang tinggal di padang menjaga kawanan ternak mereka pada waktu malam.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 6, '9 Tiba-tiba berdirilah seorang malaikat Tuhan di dekat mereka dan kemuliaan Tuhan bersinar meliputi mereka dan mereka sangat ketakutan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 7, '10 Lalu kata malaikat itu kepada mereka: "Jangan takut, sebab sesungguhnya aku memberitakan kepadamu kesukaan besar untuk seluruh bangsa:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 8, '11 Hari ini telah lahir bagimu Juruselamat, yaitu Kristus, Tuhan, di kota Daud.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 9, '12 Dan inilah tandanya bagimu: Kamu akan menjumpai seorang bayi dibungkus dengan lampin dan terbaring di dalam palungan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 10, '13 Dan tiba-tiba tampaklah bersama-sama dengan malaikat itu sejumlah besar bala tentara sorga yang memuji Allah, katanya:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 11, '14 "Kemuliaan bagi Allah di tempat yang mahatinggi dan damai sejahtera di bumi di antara manusia yang berkenan kepada-Nya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 12, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 13, 'Lukas 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 14, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 15, '15 Setelah malaikat-malaikat itu meninggalkan mereka dan kembali ke sorga, gembala-gembala itu berkata seorang kepada yang lain: "Marilah kita pergi ke Betlehem untuk melihat apa yang terjadi di sana, seperti yang diberitahukan Tuhan kepada kita."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 16, '16 Lalu mereka cepat-cepat berangkat dan menjumpai Maria dan Yusuf dan bayi itu, yang sedang berbaring di dalam palungan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 17, '17 Dan ketika mereka melihat-Nya, mereka memberitahukan apa yang telah dikatakan kepada mereka tentang Anak itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 18, '18 Dan semua orang yang mendengarnya heran tentang apa yang dikatakan gembala-gembala itu kepada mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 19, '19 Tetapi Maria menyimpan segala perkara itu di dalam hatinya dan merenungkannya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(10, 20, '20 Maka kembalilah gembala-gembala itu sambil memuji dan memuliakan Allah karena segala sesuatu yang mereka dengar dan mereka lihat, semuanya sesuai dengan apa yang telah dikatakan kepada mereka.');
