INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 1, 'V.a Masa Bayi Yesus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 2, '14. Yesus Disunat');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 3, 'Lukas 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 5, '21 Dan ketika genap delapan hari dan Ia harus disunatkan, Ia diberi nama Yesus, yaitu nama yang disebut oleh malaikat sebelum Ia dikandung ibu-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 6, '15. Ucapan Syukur Simeon dan Hana');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 7, 'Lukas 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 8, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 9, '22 Dan ketika genap waktu pentahiran, menurut hukum Taurat Musa, mereka membawa Dia ke Yerusalem untuk menyerahkan-Nya kepada Tuhan,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 10, '23 seperti ada tertulis dalam hukum Tuhan: "Semua anak laki-laki sulung harus dikuduskan bagi Allah",');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 11, '24 dan untuk mempersembahkan korban menurut apa yang difirmankan dalam hukum Tuhan, yaitu sepasang burung tekukur atau dua ekor anak burung merpati.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 12, '25 Adalah di Yerusalem seorang bernama Simeon. Ia seorang yang benar dan saleh yang menantikan penghiburan bagi Israel. Roh Kudus ada di atasnya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 13, '26 dan kepadanya telah dinyatakan oleh Roh Kudus, bahwa ia tidak akan mati sebelum ia melihat Mesias, yaitu Dia yang diurapi Tuhan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 14, '27 Ia datang ke Bait Allah oleh Roh Kudus. Ketika Yesus, Anak itu, dibawa masuk oleh orang tua-Nya untuk melakukan kepada-Nya apa yang ditentukan hukum Taurat,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 15, '28 ia menyambut Anak itu dan menatang-Nya sambil memuji Allah, katanya:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 16, '29 "Sekarang, Tuhan, biarkanlah hamba-Mu ini pergi dalam damai sejahtera, sesuai dengan firman-Mu,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 17, '30 sebab mataku telah melihat keselamatan yang dari pada-Mu,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 18, '31 yang telah Engkau sediakan di hadapan segala bangsa,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 19, '32 yaitu terang yang menjadi penyataan bagi bangsa-bangsa lain dan menjadi kemuliaan bagi umat-Mu, Israel."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 20, '33 Dan bapa serta ibu-Nya amat heran akan segala apa yang dikatakan tentang Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 21, '34 Lalu Simeon memberkati mereka dan berkata kepada Maria, ibu Anak itu: "Sesungguhnya Anak ini ditentukan untuk menjatuhkan atau membangkitkan banyak orang di Israel dan untuk menjadi suatu tanda yang menimbulkan perbantahan');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 22, '35 --dan suatu pedang akan menembus jiwamu sendiri--,supaya menjadi nyata pikiran hati banyak orang."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 23, '36 Lagipula di situ ada Hana, seorang nabi perempuan, anak Fanuel dari suku Asyer. Ia sudah sangat lanjut umurnya. Sesudah kawin ia hidup tujuh tahun lamanya bersama suaminya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 24, '37 dan sekarang ia janda dan berumur delapan puluh empat tahun. Ia tidak pernah meninggalkan Bait Allah dan siang malam beribadah dengan berpuasa dan berdoa.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 25, '38 Dan pada ketika itu juga datanglah ia ke situ dan mengucap syukur kepada Allah dan berbicara tentang Anak itu kepada semua orang yang menantikan kelepasan untuk Yerusalem.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 26, '16. Kunjungan Orang Majus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 27, 'Matius 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 28, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 29, '1 Sesudah Yesus dilahirkan di Betlehem di tanah Yudea pada zaman raja Herodes, datanglah orang-orang majus dari Timur ke Yerusalem');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 30, '2 dan bertanya-tanya: "Di manakah Dia, raja orang Yahudi yang baru dilahirkan itu? Kami telah melihat bintang-Nya di Timur dan kami datang untuk menyembah Dia."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 31, '3 Ketika raja Herodes mendengar hal itu terkejutlah ia beserta seluruh Yerusalem.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 32, '4 Maka dikumpulkannya semua imam kepala dan ahli Taurat bangsa Yahudi, lalu dimintanya keterangan dari mereka, di mana Mesias akan dilahirkan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 33, '5 Mereka berkata kepadanya: "Di Betlehem di tanah Yudea, karena demikianlah ada tertulis dalam kitab nabi:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 34, '6 Dan engkau Betlehem, tanah Yehuda, engkau sekali-kali bukanlah yang terkecil di antara mereka yang memerintah Yehuda, karena dari padamulah akan bangkit seorang pemimpin, yang akan menggembalakan umat-Ku Israel."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 35, '7 Lalu dengan diam-diam Herodes memanggil orang-orang majus itu dan dengan teliti bertanya kepada mereka, bilamana bintang itu nampak.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 36, '8 Kemudian ia menyuruh mereka ke Betlehem, katanya: "Pergi dan selidikilah dengan seksama hal-hal mengenai Anak itu dan segera sesudah kamu menemukan Dia, kabarkanlah kepadaku supaya akupun datang menyembah Dia."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 37, '9 Setelah mendengar kata-kata raja itu, berangkatlah mereka. Dan lihatlah, bintang yang mereka lihat di Timur itu mendahului mereka hingga tiba dan berhenti di atas tempat, di mana Anak itu berada.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 38, '10 Ketika mereka melihat bintang itu, sangat bersukacitalah mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 39, '11 Maka masuklah mereka ke dalam rumah itu dan melihat Anak itu bersama Maria, ibu-Nya, lalu sujud menyembah Dia. Merekapun membuka tempat harta bendanya dan mempersembahkan persembahan kepada-Nya, yaitu emas, kemenyan dan mur.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 40, '12 Dan karena diperingatkan dalam mimpi, supaya jangan kembali kepada Herodes, maka pulanglah mereka ke negerinya melalui jalan lain.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 41, '17. Menyingkir ke Mesir');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 42, 'Matius 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 43, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 44, '13 Setelah orang-orang majus itu berangkat, nampaklah malaikat Tuhan kepada Yusuf dalam mimpi dan berkata: "Bangunlah, ambillah Anak itu serta ibu-Nya, larilah ke Mesir dan tinggallah di sana sampai Aku berfirman kepadamu, karena Herodes akan mencari Anak itu untuk membunuh Dia."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 45, '14 Maka Yusufpun bangunlah, diambilnya Anak itu serta ibu-Nya malam itu juga, lalu menyingkir ke Mesir,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 46, '15 dan tinggal di sana hingga Herodes mati. Hal itu terjadi supaya genaplah yang difirmankan Tuhan oleh nabi: "Dari Mesir Kupanggil Anak-Ku."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 47, '16 Ketika Herodes tahu, bahwa ia telah diperdayakan oleh orang-orang majus itu, ia sangat marah. Lalu ia menyuruh membunuh semua anak di Betlehem dan sekitarnya, yaitu anak-anak yang berumur dua tahun ke bawah, sesuai dengan waktu yang dapat diketahuinya dari orang-orang majus itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 48, '17 Dengan demikian genaplah firman yang disampaikan oleh nabi Yeremia:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 49, '18 "Terdengarlah suara di Rama, tangis dan ratap yang amat sedih; Rahel menangisi anak-anaknya dan ia tidak mau dihibur, sebab mereka tidak ada lagi."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 50, 'Lukas 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 51, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 52, '39 Dan setelah selesai semua yang harus dilakukan menurut hukum Tuhan, kembalilah mereka ke kota kediamannya, yaitu kota Nazaret di Galilea.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 53, '18. Kembali ke Nazaret');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 54, 'Matius 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 55, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 56, '19 Setelah Herodes mati, nampaklah malaikat Tuhan kepada Yusuf dalam mimpi di Mesir, katanya:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 57, '20 "Bangunlah, ambillah Anak itu serta ibu-Nya dan berangkatlah ke tanah Israel, karena mereka yang hendak membunuh Anak itu, sudah mati."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 58, '21 Lalu Yusufpun bangunlah, diambilnya Anak itu serta ibu-Nya dan pergi ke tanah Israel.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 59, '22 Tetapi setelah didengarnya, bahwa Arkhelaus menjadi raja di Yudea menggantikan Herodes, ayahnya, ia takut ke sana. Karena dinasihati dalam mimpi, pergilah Yusuf ke daerah Galilea.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(11, 60, '23 Setibanya di sana iapun tinggal di sebuah kota yang bernama Nazaret. Hal itu terjadi supaya genaplah firman yang disampaikan oleh nabi-nabi, bahwa Ia akan disebut: Orang Nazaret.');
