INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 1, '19. Masa Kanak-kanak di Nazaret');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 2, 'Lukas 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 3, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 4, '40 Anak itu bertambah besar dan menjadi kuat, penuh hikmat, dan kasih karunia Allah ada pada-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 5, '20. Paskah di Yerusalem');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 6, 'Lukas 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 7, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 8, '41 Tiap-tiap tahun orang tua Yesus pergi ke Yerusalem pada hari raya Paskah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 9, '42 Ketika Yesus telah berumur dua belas tahun pergilah mereka ke Yerusalem seperti yang lazim pada hari raya itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 10, '43 Sehabis hari-hari perayaan itu, ketika mereka berjalan pulang, tinggallah Yesus di Yerusalem tanpa diketahui orang tua-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 11, '44 Karena mereka menyangka bahwa Ia ada di antara orang-orang seperjalanan mereka, berjalanlah mereka sehari perjalanan jauhnya, lalu mencari Dia di antara kaum keluarga dan kenalan mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 12, '45 Karena mereka tidak menemukan Dia, kembalilah mereka ke Yerusalem sambil terus mencari Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 13, '46 Sesudah tiga hari mereka menemukan Dia dalam Bait Allah; Ia sedang duduk di tengah-tengah alim ulama, sambil mendengarkan mereka dan mengajukan pertanyaan-pertanyaan kepada mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 14, '47 Dan semua orang yang mendengar Dia sangat heran akan kecerdasan-Nya dan segala jawab yang diberikan-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 15, '48 Dan ketika orang tua-Nya melihat Dia, tercenganglah mereka, lalu kata ibu-Nya kepada-Nya: "Nak, mengapakah Engkau berbuat demikian terhadap kami? Bapa-Mu dan aku dengan cemas mencari Engkau."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 16, '49 Jawab-Nya kepada mereka: "Mengapa kamu mencari Aku? Tidakkah kamu tahu, bahwa Aku harus berada di dalam rumah Bapa-Ku?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 17, '50 Tetapi mereka tidak mengerti apa yang dikatakan-Nya kepada mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 18, '21. Masa Tenang di Nazaret');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 19, 'Lukas 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 20, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 21, '51 Lalu Ia pulang bersama-sama mereka ke Nazaret; dan Ia tetap hidup dalam asuhan mereka. Dan ibu-Nya menyimpan semua perkara itu di dalam hatinya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 22, '52 Dan Yesus makin bertambah besar dan bertambah hikmat-Nya dan besar-Nya, dan makin dikasihi oleh Allah dan manusia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 23, '1 Ukupan diterjemahkan dari thumiama (Yunani) dan incense (Inggris).');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 24, '2 Mezbah diterjemahkan dari thusiasterion (Yunani) dan altar (Inggris).');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 25, '3 Penglihatan diterjemahkan dari optasian (Yunani) dan vision (Inggris).');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(12, 26, '4 Kesukaan besar, kabar gembira dan Injil diterjemahkan dari euanggelion (Yunani) dan glad tiding, good news, gospel (Inggris).');
