INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 1, 'C. PROKLAMASI TENTANG KRISTUS');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 2, 'VII. Permulaan Pelayanan Yesus Kristus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 3, '22. Pelayanan Yohanes Pembaptis');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 4, 'Lukas 3');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 5, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 6, '1 Dalam tahun kelima belas dari pemerintahan Kaisar Tiberius, ketika Pontius Pilatus menjadi wali negeri Yudea, dan Herodes raja wilayah Galilea, Filipus, saudaranya, raja wilayah Iturea dan Trakhonitis, dan Lisanias raja wilayah Abilene,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 7, '2 pada waktu Hanas dan Kayafas menjadi Imam Besar, datanglah firman Allah kepada Yohanes, anak Zakharia, di padang gurun.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 8, '3 Maka datanglah Yohanes ke seluruh daerah Yordan dan menyerukan: "Bertobatlah dan berilah dirimu dibaptis dan Allah akan mengampuni dosamu,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 9, '4 seperti ada tertulis dalam kitab nubuat-nubuat Yesaya: Ada suara yang berseru-seru di padang gurun: Persiapkanlah jalan untuk Tuhan, luruskanlah jalan bagi-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 10, '5 Setiap lembah akan ditimbun dan setiap gunung dan bukit akan menjadi rata, yang berliku-liku akan diluruskan, yang berlekuk-lekuk akan diratakan,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 11, '6 dan semua orang akan melihat keselamatan yang dari Tuhan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 12, '7 Lalu ia berkata kepada orang banyak yang datang kepadanya untuk dibaptis, katanya: "Hai kamu keturunan ular beludak! Siapakah yang mengatakan kepada kamu melarikan diri dari murka yang akan datang?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 13, '8 Jadi hasilkanlah buah-buah yang sesuai dengan pertobatan. Dan janganlah berpikir dalam hatimu: Abraham adalah bapa kami! Karena aku berkata kepadamu: Allah dapat menjadikan anak-anak bagi Abraham dari batu-batu ini!');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 14, '9 Kapak sudah tersedia pada akar pohon dan setiap pohon yang tidak menghasilkan buah yang baik, akan ditebang dan dibuang ke dalam api."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 15, '10 Orang banyak bertanya kepadanya: "Jika demikian, apakah yang harus kami perbuat?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 16, '11 Jawabnya: "Barangsiapa mempunyai dua helai baju, hendaklah ia membaginya dengan yang tidak punya, dan barangsiapa mempunyai makanan, hendaklah ia berbuat juga demikian."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 17, '12 Ada datang juga pemungut-pemungut cukai untuk dibaptis dan mereka bertanya kepadanya: "Guru, apakah yang harus kami perbuat?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 18, '13 Jawabnya: "Jangan menagih lebih banyak dari pada yang telah ditentukan bagimu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 19, '14 Dan prajurit-prajurit bertanya juga kepadanya: "Dan kami, apakah yang harus kami perbuat?" Jawab Yohanes kepada mereka: "Jangan merampas dan jangan memeras dan cukupkanlah dirimu dengan gajimu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 20, '15 Tetapi karena orang banyak sedang menanti dan berharap, dan semuanya bertanya dalam hatinya tentang Yohanes, kalau-kalau ia adalah Mesias,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 21, '16 Yohanes menjawab dan berkata kepada semua orang itu: "Aku membaptis kamu dengan air, tetapi Ia yang lebih berkuasa dari padaku akan datang dan membuka tali kasut-Nyapun aku tidak layak. Ia akan membaptis kamu dengan Roh Kudus dan dengan api.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 22, '17 Alat penampi sudah di tangan-Nya untuk membersihkan tempat pengirikan-Nya dan untuk mengumpulkan gandum-Nya ke dalam lumbung-Nya, tetapi debu jerami itu akan dibakar-Nya dalam api yang tidak terpadamkan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 23, '18 Dengan banyak nasihat lain Yohanes memberitakan Injil kepada orang banyak.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 24, 'Matius 3');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 25, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 26, '1 Pada waktu itu tampillah Yohanes Pembaptis di padang gurun Yudea dan memberitakan:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 27, '2 "Bertobatlah, sebab Kerajaan Sorga sudah dekat!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 28, '3 Sesungguhnya dialah yang dimaksudkan nabi Yesaya ketika ia berkata: "Ada suara orang yang berseru-seru di padang gurun: Persiapkanlah jalan untuk Tuhan, luruskanlah jalan bagi-Nya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 29, '4 Yohanes memakai jubah bulu unta dan ikat pinggang kulit, dan makanannya belalang dan madu hutan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 30, '5 Maka datanglah kepadanya penduduk dari Yerusalem, dari seluruh Yudea dan dari seluruh daerah sekitar Yordan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 31, '6 Lalu sambil mengaku dosanya mereka dibaptis oleh Yohanes di sungai Yordan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 32, '7 Tetapi waktu ia melihat banyak orang Farisi dan orang Saduki datang untuk dibaptis, berkatalah ia kepada mereka: "Hai kamu keturunan ular beludak. Siapakah yang mengatakan kepada kamu, bahwa kamu dapat melarikan diri dari murka yang akan datang?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 33, '8 Jadi hasilkanlah buah yang sesuai dengan pertobatan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 34, '9 Dan janganlah mengira, bahwa kamu dapat berkata dalam hatimu: Abraham adalah bapa kami! Karena aku berkata kepadamu: Allah dapat menjadikan anak-anak bagi Abraham dari batu-batu ini!');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 35, '10 Kapak sudah tersedia pada akar pohon dan setiap pohon yang tidak menghasilkan buah yang baik, pasti ditebang dan dibuang ke dalam api.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 36, '11 Aku membaptis kamu dengan air sebagai tanda pertobatan, tetapi Ia yang datang kemudian dari padaku lebih berkuasa dari padaku dan aku tidak layak melepaskan kasut-Nya. Ia akan membaptiskan kamu dengan Roh Kudus dan dengan api.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 37, '12 Alat penampi sudah ditangan-Nya. Ia akan membersihkan tempat pengirikan-Nya dan mengumpulkan gandum-Nya ke dalam lumbung, tetapi debu jerami itu akan dibakar-Nya dalam api yang tidak terpadamkan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 38, 'Markus 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 39, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 40, '1 Inilah permulaan Injil tentang Yesus Kristus, Anak Allah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 41, '2 Seperti ada tertulis dalam kitab nabi Yesaya: "Lihatlah, Aku menyuruh utusan-Ku mendahului Engkau, ia akan mempersiapkan jalan bagi-Mu;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 42, '3 ada suara orang yang berseru-seru di padang gurun: Persiapkanlah jalan untuk Tuhan, luruskanlah jalan bagi-Nya",');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 43, '4 demikianlah Yohanes Pembaptis tampil di padang gurun dan menyerukan: "Bertobatlah dan berilah dirimu dibaptis dan Allah akan mengampuni dosamu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 44, '5 Lalu datanglah kepadanya orang-orang dari seluruh daerah Yudea dan semua penduduk Yerusalem, dan sambil mengaku dosanya mereka dibaptis di sungai Yordan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 45, '6 Yohanes memakai jubah bulu unta dan ikat pinggang kulit, dan makanannya belalang dan madu hutan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 46, '7 Inilah yang diberitakannya: "Sesudah aku akan datang Ia yang lebih berkuasa dari padaku; membungkuk dan membuka tali kasut-Nyapun aku tidak layak.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(13, 47, '8 Aku membaptis kamu dengan air, tetapi Ia akan membaptis kamu dengan Roh Kudus."');
