INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 1, '23. Yesus Dibaptis');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 2, 'Matius 3');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 3, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 4, '13 Maka datanglah Yesus dari Galilea ke Yordan kepada Yohanes untuk dibaptis olehnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 5, '14 Tetapi Yohanes mencegah Dia, katanya: "Akulah yang perlu dibaptis oleh-Mu, dan Engkau yang datang kepadaku?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 6, '15 Lalu Yesus menjawab, kata-Nya kepadanya: "Biarlah hal itu terjadi, karena demikianlah sepatutnya kita menggenapkan seluruh kehendak Allah." Dan Yohanespun menuruti-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 7, '16 Sesudah dibaptis, Yesus segera keluar dari air dan pada waktu itu juga langit terbuka dan Ia melihat Roh Allah seperti burung merpati turun ke atas-Nya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 8, '17 lalu terdengarlah suara dari sorga yang mengatakan: "Inilah Anak-Ku yang Kukasihi, kepada-Nyalah Aku berkenan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 8, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 2, 'Markus 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 3, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 4, '9 Pada waktu itu datanglah Yesus dari Nazaret di tanah Galilea, dan Ia dibaptis di sungai Yordan oleh Yohanes.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 5, '10 Pada saat Ia keluar dari air, Ia melihat langit terkoyak, dan Roh seperti burung merpati turun ke atas-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 6, '11 Lalu terdengarlah suara dari sorga: "Engkaulah Anak-Ku yang Kukasihi, kepada-Mulah Aku berkenan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 6, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 2, 'Lukas 3');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 3, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 4, '21 Ketika seluruh orang banyak itu telah dibaptis dan ketika Yesus juga dibaptis dan sedang berdoa, terbukalah langit');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 5, '22 dan turunlah Roh Kudus dalam rupa burung merpati ke atas-Nya. Dan terdengarlah suara dari langit: "Engkaulah Anak-Ku yang Kukasihi, kepada-Mulah Aku berkenan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 6, '23 Ketika Yesus memulai pekerjaan-Nya, Ia berumur kira-kira tiga puluh tahun dan menurut anggapan orang, Ia adalah anak Yusuf, anak Eli,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 6, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 2, 'Yohanes 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 3, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 4, '15 Yohanes memberi kesaksian tentang Dia dan berseru, katanya: "Inilah Dia, yang kumaksudkan ketika aku berkata: Kemudian dari padaku akan datang Dia yang telah mendahului aku, sebab Dia telah ada sebelum aku."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 5, '16 Karena dari kepenuhan-Nya kita semua telah menerima kasih karunia demi kasih karunia;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 6, '17 sebab hukum Taurat diberikan oleh Musa, tetapi kasih karunia dan kebenaran datang oleh Yesus Kristus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(14, 7, '18 Tidak seorangpun yang pernah melihat Allah; tetapi Anak Tunggal Allah, yang ada di pangkuan Bapa, Dialah yang menyatakan-Nya.');
