INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 1, 'VII. Permulaan Pelayanan Yesus Kristus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 2, '24. Yesus Dicobai');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 3, 'Lukas 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 5, '1 Yesus, yang penuh dengan Roh Kudus, kembali dari sungai Yordan, lalu dibawa oleh Roh Kudus ke padang gurun.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 6, '2 Di situ Ia tinggal empat puluh hari lamanya dan dicobai Iblis. Selama di situ Ia tidak makan apa-apa dan sesudah waktu itu Ia lapar.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 7, '3 Lalu berkatalah Iblis kepada-Nya: "Jika Engkau Anak Allah, suruhlah batu ini menjadi roti."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 8, '4 Jawab Yesus kepadanya: "Ada tertulis: Manusia hidup bukan dari roti saja."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 9, '5 Kemudian ia membawa Yesus ke suatu tempat yang tinggi dan dalam sekejap mata ia memperlihatkan kepada-Nya semua kerajaan dunia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 10, '6 Kata Iblis kepada-Nya: "Segala kuasa itu serta kemuliaannya akan kuberikan kepada-Mu, sebab semuanya itu telah diserahkan kepadaku dan aku memberikannya kepada siapa saja yang kukehendaki.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 11, '7 Jadi jikalau Engkau menyembah aku, seluruhnya itu akan menjadi milik-Mu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 12, '8 Tetapi Yesus berkata kepadanya: "Ada tertulis: Engkau harus menyembah Tuhan, Allahmu, dan hanya kepada Dia sajalah engkau berbakti!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 13, '9 Kemudian ia membawa Yesus ke Yerusalem dan menempatkan Dia di bubungan Bait Allah, lalu berkata kepada-Nya: "Jika Engkau Anak Allah, jatuhkanlah diri-Mu dari sini ke bawah,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 14, '10 sebab ada tertulis: Mengenai Engkau, Ia akan memerintahkan malaikat-malaikat-Nya untuk melindungi Engkau,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 15, '11 dan mereka akan menatang Engkau di atas tangannya, supaya kaki-Mu jangan terantuk kepada batu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 16, '12 Yesus menjawabnya, kata-Nya: "Ada firman: Jangan engkau mencobai Tuhan, Allahmu!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 17, '13 Sesudah Iblis mengakhiri semua pencobaan itu, ia mundur dari pada-Nya dan menunggu waktu yang baik.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 17, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 3, 'Matius 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 5, '1 Maka Yesus dibawa oleh Roh ke padang gurun untuk dicobai Iblis.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 6, '2 Dan setelah berpuasa empat puluh hari dan empat puluh malam, akhirnya laparlah Yesus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 7, '3 Lalu datanglah si pencoba itu dan berkata kepada-Nya: "Jika Engkau Anak Allah, perintahkanlah supaya batu-batu ini menjadi roti."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 8, '4 Tetapi Yesus menjawab: "Ada tertulis: Manusia hidup bukan dari roti saja, tetapi dari setiap firman yang keluar dari mulut Allah."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 9, '5 Kemudian Iblis membawa-Nya ke Kota Suci dan menempatkan Dia di bubungan Bait Allah,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 10, '6 lalu berkata kepada-Nya: "Jika Engkau Anak Allah, jatuhkanlah diri-Mu ke bawah, sebab ada tertulis: Mengenai Engkau Ia akan memerintahkan malaikat-malaikat-Nya dan mereka akan menatang Engkau di atas tangannya, supaya kaki-Mu jangan terantuk kepada batu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 11, '7 Yesus berkata kepadanya: "Ada pula tertulis: Janganlah engkau mencobai Tuhan, Allahmu!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 12, '8 Dan Iblis membawa-Nya pula ke atas gunung yang sangat tinggi dan memperlihatkan kepada-Nya semua kerajaan dunia dengan kemegahannya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 13, '9 dan berkata kepada-Nya: "Semua itu akan kuberikan kepada-Mu, jika Engkau sujud menyembah aku."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 14, '10 Maka berkatalah Yesus kepadanya: "Enyahlah, Iblis! Sebab ada tertulis: Engkau harus menyembah Tuhan, Allahmu, dan hanya kepada Dia sajalah engkau berbakti!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 15, '11 Lalu Iblis meninggalkan Dia, dan lihatlah, malaikat-malaikat datang melayani Yesus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 15, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 3, 'Markus 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 5, '12 Segera sesudah itu Roh memimpin Dia ke padang gurun.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(15, 6, '13 Di padang gurun itu Ia tinggal empat puluh hari lamanya, dicobai oleh Iblis. Ia berada di sana di antara binatang-binatang liar dan malaikat-malaikat melayani Dia.');
