INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 1, 'VII. Permulaan Pelayanan Yesus Kristus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 2, '25. Kesaksian Yohanes Pembaptis');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 3, 'Yohanes 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 5, '19 Dan inilah kesaksian Yohanes ketika orang Yahudi dari Yerusalem mengutus beberapa imam dan orang-orang Lewi kepadanya untuk menanyakan dia: "Siapakah engkau?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 6, '20 Ia mengaku dan tidak berdusta, katanya: "Aku bukan Mesias."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 7, '21 Lalu mereka bertanya kepadanya: "Kalau begitu, siapakah engkau? Elia?" Dan ia menjawab: "Bukan!" "Engkaukah nabi yang akan datang?" Dan ia menjawab: "Bukan!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 8, '22 Maka kata mereka kepadanya: "Siapakah engkau? Sebab kami harus memberi jawab kepada mereka yang mengutus kami. Apakah katamu tentang dirimu sendiri?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 9, '23 Jawabnya: "Akulah suara orang yang berseru-seru di padang gurun: Luruskanlah jalan Tuhan! seperti yang telah dikatakan nabi Yesaya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 10, '24 Dan di antara orang-orang yang diutus itu ada beberapa orang Farisi.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 11, '25 Mereka bertanya kepadanya, katanya: "Mengapakah engkau membaptis, jikalau engkau bukan Mesias, bukan Elia, dan bukan nabi yang akan datang?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 12, '26 Yohanes menjawab mereka, katanya: "Aku membaptis dengan air; tetapi di tengah-tengah kamu berdiri Dia yang tidak kamu kenal,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 13, '27 yaitu Dia, yang datang kemudian dari padaku. Membuka tali kasut-Nyapun aku tidak layak."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 14, '28 Hal itu terjadi di Betania yang di seberang sungai Yordan, di mana Yohanes membaptis.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 15, '29 Pada keesokan harinya Yohanes melihat Yesus datang kepadanya dan ia berkata: "Lihatlah Anak domba Allah, yang menghapus dosa dunia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 16, '30 Dialah yang kumaksud ketika kukatakan: Kemudian dari padaku akan datang seorang, yang telah mendahului aku, sebab Dia telah ada sebelum aku.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 17, '31 Dan aku sendiripun mula-mula tidak mengenal Dia, tetapi untuk itulah aku datang dan membaptis dengan air, supaya Ia dinyatakan kepada Israel."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 18, '32 Dan Yohanes memberi kesaksian, katanya: "Aku telah melihat Roh turun dari langit seperti merpati, dan Ia tinggal di atas-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 19, '33 Dan akupun tidak mengenal-Nya, tetapi Dia, yang mengutus aku untuk membaptis dengan air, telah berfirman kepadaku: Jikalau engkau melihat Roh itu turun ke atas seseorang dan tinggal di atas-Nya, Dialah itu yang akan membaptis dengan Roh Kudus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(16, 20, '34 Dan aku telah melihat-Nya dan memberi kesaksian: Ia inilah Anak Allah."');
