INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 1, 'VII. Permulaan Pelayanan Yesus Kristus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 2, '26. Murid-murid Yesus yang Pertama 40,46,114,115,189,192,197');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 3, 'Yohanes 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 5, '35 Pada keesokan harinya Yohanes berdiri di situ pula dengan dua orang muridnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 6, '36 Dan ketika ia melihat Yesus lewat, ia berkata: "Lihatlah Anak domba Allah!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 7, '37 Kedua murid itu mendengar apa yang dikatakannya itu, lalu mereka pergi mengikut Yesus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 8, '38 Tetapi Yesus menoleh ke belakang. Ia melihat, bahwa mereka mengikut Dia lalu berkata kepada mereka: "Apakah yang kamu cari?" Kata mereka kepada-Nya: "Rabi (artinya: Guru), di manakah Engkau tinggal?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 9, '39 Ia berkata kepada mereka: "Marilah dan kamu akan melihatnya." Merekapun datang dan melihat di mana Ia tinggal, dan hari itu mereka tinggal bersama-sama dengan Dia; waktu itu kira-kira pukul empat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 10, '40 Salah seorang dari keduanya yang mendengar perkataan Yohanes lalu mengikut Yesus adalah Andreas, saudara Simon Petrus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 11, '41 Andreas mula-mula bertemu dengan Simon, saudaranya, dan ia berkata kepadanya: "Kami telah menemukan Mesias (artinya: Kristus)."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 12, '42 Ia membawanya kepada Yesus. Yesus memandang dia dan berkata: "Engkau Simon, anak Yohanes, engkau akan dinamakan Kefas (artinya: Petrus)."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 13, '43 Pada keesokan harinya Yesus memutuskan untuk berangkat ke Galilea. Ia bertemu dengan Filipus, dan berkata kepadanya: "Ikutlah Aku!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 14, '44 Filipus itu berasal dari Betsaida, kota Andreas dan Petrus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 15, '45 Filipus bertemu dengan Natanael dan berkata kepadanya: "Kami telah menemukan Dia, yang disebut oleh Musa dalam kitab Taurat dan oleh para nabi, yaitu Yesus, anak Yusuf dari Nazaret."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 16, '46 Kata Natanael kepadanya: "Mungkinkah sesuatu yang baik datang dari Nazaret?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 17, '47 Kata Filipus kepadanya: "Mari dan lihatlah!" Yesus melihat Natanael datang kepada-Nya, lalu berkata tentang dia: "Lihat, inilah seorang Israel sejati, tidak ada kepalsuan di dalamnya!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 18, '48 Kata Natanael kepada-Nya: "Bagaimana Engkau mengenal aku?" Jawab Yesus kepadanya: "Sebelum Filipus memanggil engkau, Aku telah melihat engkau di bawah pohon ara."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 19, '49 Kata Natanael kepada-Nya: "Rabi, Engkau Anak Allah, Engkau Raja orang Israel!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 20, '50 Yesus menjawab, kata-Nya: "Karena Aku berkata kepadamu: Aku melihat engkau di bawah pohon ara, maka engkau percaya? Engkau akan melihat hal-hal yang lebih besar dari pada itu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(17, 21, '51 Lalu kata Yesus kepadanya: "Aku berkata kepadamu, sesungguhnya engkau akan melihat langit terbuka dan malaikat-malaikat Allah turun naik kepada Anak Manusia."');
