INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 1, 'VII. Permulaan Pelayanan Yesus Kristus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 2, '27. Mujizad Pertama di Kana 37');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 3, 'Yohanes 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 5, '1 Pada hari ketiga ada perkawinan di Kana yang di Galilea, dan ibu Yesus ada di situ;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 6, '2 Yesus dan murid-murid-Nya diundang juga ke perkawinan itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 7, '3 Ketika mereka kekurangan anggur, ibu Yesus berkata kepada-Nya: "Mereka kehabisan anggur."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 8, '4 Kata Yesus kepadanya: "Mau apakah engkau dari pada-Ku, ibu? Saat-Ku belum tiba."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 9, '5 Tetapi ibu Yesus berkata kepada pelayan-pelayan: "Apa yang dikatakan kepadamu, buatlah itu!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 10, '6 Di situ ada enam tempayan yang disediakan untuk pembasuhan menurut adat orang Yahudi, masing-masing isinya dua tiga buyung.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 11, '7 Yesus berkata kepada pelayan-pelayan itu: "Isilah tempayan-tempayan itu penuh dengan air." Dan merekapun mengisinya sampai penuh.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 12, '8 Lalu kata Yesus kepada mereka: "Sekarang cedoklah dan bawalah kepada pemimpin pesta." Lalu merekapun membawanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 13, '9 Setelah pemimpin pesta itu mengecap air, yang telah menjadi anggur itu--dan ia tidak tahu dari mana datangnya, tetapi pelayan-pelayan, yang mencedok air itu, mengetahuinya--ia memanggil mempelai laki-laki,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 14, '10 dan berkata kepadanya: "Setiap orang menghidangkan anggur yang baik dahulu dan sesudah orang puas minum, barulah yang kurang baik; akan tetapi engkau menyimpan anggur yang baik sampai sekarang."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 15, '11 Hal itu dibuat Yesus di Kana yang di Galilea, sebagai yang pertama dari tanda-tanda-Nya dan dengan itu Ia telah menyatakan kemuliaan-Nya, dan murid-murid-Nya percaya kepada-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(18, 16, '12 Sesudah itu Yesus pergi ke Kapernaum, bersama-sama dengan ibu-Nya dan saudara-saudara-Nya dan murid-murid-Nya, dan mereka tinggal di situ hanya beberapa hari saja.');
