INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 1, 'VIII. Pelayanan Awal Yesus di Yudea');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 2, 'VIII.a Pelayanan di Yerusalem');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 3, '28. Paskah Pertama dan Yesus Meyucikan Bait Allah untuk Pertama Kali 169');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 4, 'Yohanes 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 5, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 6, '13 Ketika hari raya Paskah orang Yahudi sudah dekat, Yesus berangkat ke Yerusalem.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 7, '14 Dalam Bait Suci didapati-Nya pedagang-pedagang lembu, kambing domba dan merpati, dan penukar-penukar uang duduk di situ.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 8, '15 Ia membuat cambuk dari tali lalu mengusir mereka semua dari Bait Suci dengan semua kambing domba dan lembu mereka; uang penukar-penukar dihamburkan-Nya ke tanah dan meja-meja mereka dibalikkan-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 9, '16 Kepada pedagang-pedagang merpati Ia berkata: "Ambil semuanya ini dari sini, jangan kamu membuat rumah Bapa-Ku menjadi tempat berjualan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 10, '17 Maka teringatlah murid-murid-Nya, bahwa ada tertulis: "Cinta untuk rumah-Mu menghanguskan Aku."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 11, '18 Orang-orang Yahudi menantang Yesus, katanya: "Tanda apakah dapat Engkau tunjukkan kepada kami, bahwa Engkau berhak bertindak demikian?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 12, '19 Jawab Yesus kepada mereka: "Rombak Bait Allah ini, dan dalam tiga hari Aku akan mendirikannya kembali."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 13, '20 Lalu kata orang Yahudi kepada-Nya: "Empat puluh enam tahun orang mendirikan Bait Allah ini dan Engkau dapat membangunnya dalam tiga hari?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 14, '21 Tetapi yang dimaksudkan-Nya dengan Bait Allah ialah tubuh-Nya sendiri.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(19, 15, '22 Kemudian, sesudah Ia bangkit dari antara orang mati, barulah teringat oleh murid-murid-Nya bahwa hal itu telah dikatakan-Nya, dan merekapun percayalah akan Kitab Suci dan akan perkataan yang telah diucapkan Yesus.');
