INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 1, 'Yohanes 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 2, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 3, '1 Pada mulanya adalah Firman; Firman itu bersama-sama dengan Allah dan Firman itu adalah Allah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 4, '2 Ia pada mulanya bersama-sama dengan Allah');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 5, '3 Segala sesuatu dijadikan oleh Dia dan tanpa Dia tidak ada suatupun yang telah jadi dari segala yang telah dijadikan');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 6, '4 Dalam Dia ada hidup dan hidup itu adalah terang manusia');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 7, '5 Terang itu bercahaya di dalam kegelapan dan kegelapan itu tidak menguasainya');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 8, '6 Datanglah seorang yang diutus Allah, namanya Yohanes');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 9, '7 ia datang sebagai saksi untuk memberi kesaksian tentang terang itu, supaya oleh dia semua orang menjadi percaya');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 10, '8 Ia bukan terang itu, tetapi ia harus memberi kesaksian tentang terang itu');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 11, '9 Terang yang sesungguhnya, yang menerangi setiap orang, sedang datang ke dalam dunia');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 12, '10 Ia telah ada di dalam dunia dan dunia dijadikan oleh-Nya, tetapi dunia tidak mengenal-Nya');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 13, '11 Ia datang kepada milik kepunyaan-Nya, tetapi orang-orang kepunyaan-Nya itu tidak menerima-Nya');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 14, '12 Tetapi semua orang yang menerima-Nya diberi-Nya kuasa supaya menjadi anak-anak Allah, yaitu mereka yang percaya dalam nama-Nya');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 15, '13 orang-orang yang diperanakkan bukan dari darah atau dari daging, bukan pula secara jasmani oleh keinginan seorang laki-laki, melainkan dari Allah');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 16, '14 Firman itu telah menjadi manusia, dan diam di antara kita, dan kita telah melihat kemuliaan-Nya, yaitu kemuliaan yang diberikan kepada-Nya sebagai Anak Tunggal Bapa, penuh kasih karunia dan kebenaran');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 17, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 18, 'Ibrani 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 19, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(2, 20, '3 Ia adalah cahaya kemuliaan Allah dan gambar wujud Allah dan menopang segala yang ada dengan firman-Nya yang penuh kekuasaan. Dan setelah Ia selesai mengadakan penyucian dosa, Ia duduk di sebelah kanan Yang Mahabesar, di tempat yang tinggi');
