INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 1, '29. Yesus mengajar Nikodemus tentang Kelahiran Kembali');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 2, 'Yohanes 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 3, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 4, '23 Dan sementara Ia di Yerusalem selama hari raya Paskah, banyak orang percaya dalam nama-Nya, karena mereka telah melihat tanda-tanda yang diadakan-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 5, '24 Tetapi Yesus sendiri tidak mempercayakan diri-Nya kepada mereka, karena Ia mengenal mereka semua,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 6, '25 dan karena tidak perlu seorangpun memberi kesaksian kepada-Nya tentang manusia, sebab Ia tahu apa yang ada di dalam hati manusia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 7, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 2, 'Yohanes 3');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 3, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 4, '1 Adalah seorang Farisi yang bernama Nikodemus, seorang pemimpin agama Yahudi.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 5, '2 Ia datang pada waktu malam kepada Yesus dan berkata: "Rabi, kami tahu, bahwa Engkau datang sebagai guru yang diutus Allah; sebab tidak ada seorangpun yang dapat mengadakan tanda-tanda yang Engkau adakan itu, jika Allah tidak menyertainya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 6, '3 Yesus menjawab, kata-Nya: "Aku berkata kepadamu, sesungguhnya jika seorang tidak dilahirkan kembali, ia tidak dapat melihat Kerajaan Allah."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 7, '4 Kata Nikodemus kepada-Nya: "Bagaimanakah mungkin seorang dilahirkan, kalau ia sudah tua? Dapatkah ia masuk kembali ke dalam rahim ibunya dan dilahirkan lagi?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 8, '5 Jawab Yesus: "Aku berkata kepadamu, sesungguhnya jika seorang tidak dilahirkan dari air dan Roh, ia tidak dapat masuk ke dalam Kerajaan Allah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 9, '6 Apa yang dilahirkan dari daging, adalah daging, dan apa yang dilahirkan dari Roh, adalah roh.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 10, '7 Janganlah engkau heran, karena Aku berkata kepadamu: Kamu harus dilahirkan kembali.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 11, '8 Angin bertiup ke mana ia mau, dan engkau mendengar bunyinya, tetapi engkau tidak tahu dari mana ia datang atau ke mana ia pergi. Demikianlah halnya dengan tiap-tiap orang yang lahir dari Roh."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 12, '9 Nikodemus menjawab, katanya: "Bagaimanakah mungkin hal itu terjadi?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 13, '10 Jawab Yesus: "Engkau adalah pengajar Israel, dan engkau tidak mengerti hal-hal itu?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 14, '11 Aku berkata kepadamu, sesungguhnya kami berkata-kata tentang apa yang kami ketahui dan kami bersaksi tentang apa yang kami lihat, tetapi kamu tidak menerima kesaksian kami.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 15, '12 Kamu tidak percaya, waktu Aku berkata-kata dengan kamu tentang hal-hal duniawi, bagaimana kamu akan percaya, kalau Aku berkata-kata dengan kamu tentang hal-hal sorgawi?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 16, '13 Tidak ada seorangpun yang telah naik ke sorga, selain dari pada Dia yang telah turun dari sorga, yaitu Anak Manusia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 17, '14 Dan sama seperti Musa meninggikan ular di padang gurun, demikian juga Anak Manusia harus ditinggikan,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 18, '15 supaya setiap orang yang percaya kepada-Nya beroleh hidup yang kekal.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 19, '16 Karena begitu besar kasih Allah akan dunia ini, sehingga Ia telah mengaruniakan Anak-Nya yang tunggal, supaya setiap orang yang percaya kepada-Nya tidak binasa, melainkan beroleh hidup yang kekal.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 20, '17 Sebab Allah mengutus Anak-Nya ke dalam dunia bukan untuk menghakimi dunia, melainkan untuk menyelamatkannya oleh Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 21, '18 Barangsiapa percaya kepada-Nya, ia tidak akan dihukum; barangsiapa tidak percaya, ia telah berada di bawah hukuman, sebab ia tidak percaya dalam nama Anak Tunggal Allah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 22, '19 Dan inilah hukuman itu: Terang telah datang ke dalam dunia, tetapi manusia lebih menyukai kegelapan dari pada terang, sebab perbuatan-perbuatan mereka jahat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 23, '20 Sebab barangsiapa berbuat jahat, membenci terang dan tidak datang kepada terang itu, supaya perbuatan-perbuatannya yang jahat itu tidak nampak;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(20, 24, '21 tetapi barangsiapa melakukan yang benar, ia datang kepada terang, supaya menjadi nyata, bahwa perbuatan-perbuatannya dilakukan dalam Allah."');
