INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 1, 'VIII.b Pelayanan Kristus di Yudea');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 2, '30. Pelayanan Pembaptisan Kristus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 3, 'Yohanes 3');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 5, '22 Sesudah itu Yesus pergi dengan murid-murid-Nya ke tanah Yudea dan Ia diam di sana bersama-sama mereka dan membaptis.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 6, '23 Akan tetapi Yohanespun membaptis juga di Ainon, dekat Salim, sebab di situ banyak air, dan orang-orang datang ke situ untuk dibaptis,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 7, '24 sebab pada waktu itu Yohanes belum dimasukkan ke dalam penjara.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 8, '31. Kesaksian Yohanes Pembaptis tentang Yesus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 9, 'Yohanes 3');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 10, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 11, '25 Maka timbullah perselisihan di antara murid-murid Yohanes dengan seorang Yahudi tentang penyucian.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 12, '26 Lalu mereka datang kepada Yohanes dan berkata kepadanya: "Rabi, orang yang bersama dengan engkau di seberang sungai Yordan dan yang tentang Dia engkau telah memberi kesaksian, Dia membaptis juga dan semua orang pergi kepada-Nya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 13, '27 Jawab Yohanes: "Tidak ada seorangpun yang dapat mengambil sesuatu bagi dirinya, kalau tidak dikaruniakan kepadanya dari sorga.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 14, '28 Kamu sendiri dapat memberi kesaksian, bahwa aku telah berkata: Aku bukan Mesias, tetapi aku diutus untuk mendahului-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 15, '29 Yang empunya mempelai perempuan, ialah mempelai laki-laki; tetapi sahabat mempelai laki-laki, yang berdiri dekat dia dan yang mendengarkannya, sangat bersukacita mendengar suara mempelai laki-laki itu. Itulah sukacitaku, dan sekarang sukacitaku itu penuh.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 16, '30 Ia harus makin besar, tetapi aku harus makin kecil.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 17, '31 Siapa yang datang dari atas adalah di atas semuanya; siapa yang berasal dari bumi, termasuk pada bumi dan berkata-kata dalam bahasa bumi. Siapa yang datang dari sorga adalah di atas semuanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 18, '32 Ia memberi kesaksian tentang apa yang dilihat-Nya dan yang didengar-Nya, tetapi tak seorangpun yang menerima kesaksian-Nya itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 19, '33 Siapa yang menerima kesaksian-Nya itu, ia mengaku, bahwa Allah adalah benar.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 20, '34 Sebab siapa yang diutus Allah, Dialah yang menyampaikan firman Allah, karena Allah mengaruniakan Roh-Nya dengan tidak terbatas.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 21, '35 Bapa mengasihi Anak dan telah menyerahkan segala sesuatu kepada-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 22, '36 Barangsiapa percaya kepada Anak, ia beroleh hidup yang kekal, tetapi barangsiapa tidak taat kepada Anak, ia tidak akan melihat hidup, melainkan murka Allah tetap ada di atasnya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 23, '32. Yohanes Pembaptis Dipenjarakan');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 24, 'Lukas 3');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 25, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 26, '18 Dengan banyak nasihat lain Yohanes memberitakan Injil kepada orang banyak.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 27, '19 Akan tetapi setelah ia menegor raja wilayah Herodes karena peristiwa Herodias, isteri saudaranya, dan karena segala kejahatan lain yang dilakukannya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(21, 28, '20 raja itu menambah kejahatannya dengan memasukkan Yohanes ke dalam penjara.');
