INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 1, 'IX. Pelayanan Yesus di daerah Samaria');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 2, '33. Yesus Berangkat dari Yudea ke Samaria');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 3, 'Yohanes 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 5, '1 Ketika Tuhan Yesus mengetahui, bahwa orang-orang Farisi telah mendengar, bahwa Ia memperoleh dan membaptis murid lebih banyak dari pada Yohanes');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 6, '2 --meskipun Yesus sendiri tidak membaptis, melainkan murid-murid-Nya, --');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 7, '3 Iapun meninggalkan Yudea dan kembali lagi ke Galilea.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 8, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 9, 'Matius 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 10, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 11, '12 Tetapi waktu Yesus mendengar, bahwa Yohanes telah ditangkap, menyingkirlah Ia ke Galilea.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 12, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 13, 'Markus 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 14, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 15, '14 Sesudah Yohanes ditangkap datanglah Yesus ke Galilea memberitakan Injil Allah,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 16, '34.C');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 17, 'Yohanes 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 18, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 19, '4 Ia harus melintasi daerah Samaria.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 20, '5 Maka sampailah Ia ke sebuah kota di Samaria, yang bernama Sikhar dekat tanah yang diberikan Yakub dahulu kepada anaknya, Yusuf.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 21, '6 Di situ terdapat sumur Yakub. Yesus sangat letih oleh perjalanan, karena itu Ia duduk di pinggir sumur itu. Hari kira-kira pukul dua belas.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 22, '7 Maka datanglah seorang perempuan Samaria hendak menimba air. Kata Yesus kepadanya: "Berilah Aku minum."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 23, '8 Sebab murid-murid-Nya telah pergi ke kota membeli makanan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 24, '9 Maka kata perempuan Samaria itu kepada-Nya: "Masakan Engkau, seorang Yahudi, minta minum kepadaku, seorang Samaria?" (Sebab orang Yahudi tidak bergaul dengan orang Samaria.)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 25, '10 Jawab Yesus kepadanya: "Jikalau engkau tahu tentang karunia Allah dan siapakah Dia yang berkata kepadamu: Berilah Aku minum! niscaya engkau telah meminta kepada-Nya dan Ia telah memberikan kepadamu air hidup."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 26, '11 Kata perempuan itu kepada-Nya: "Tuhan, Engkau tidak punya timba dan sumur ini amat dalam; dari manakah Engkau memperoleh air hidup itu?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 27, '12 Adakah Engkau lebih besar dari pada bapa kami Yakub, yang memberikan sumur ini kepada kami dan yang telah minum sendiri dari dalamnya, ia serta anak-anaknya dan ternaknya?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 28, '13 Jawab Yesus kepadanya: "Barangsiapa minum air ini, ia akan haus lagi,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 29, '14 tetapi barangsiapa minum air yang akan Kuberikan kepadanya, ia tidak akan haus untuk selama-lamanya. Sebaliknya air yang akan Kuberikan kepadanya, akan menjadi mata air di dalam dirinya, yang terus-menerus memancar sampai kepada hidup yang kekal."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 30, '15 Kata perempuan itu kepada-Nya: "Tuhan, berikanlah aku air itu, supaya aku tidak haus dan tidak usah datang lagi ke sini untuk menimba air."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 31, '16 Kata Yesus kepadanya: "Pergilah, panggillah suamimu dan datang ke sini."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 32, '17 Kata perempuan itu: "Aku tidak mempunyai suami." Kata Yesus kepadanya: "Tepat katamu, bahwa engkau tidak mempunyai suami,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 33, '18 sebab engkau sudah mempunyai lima suami dan yang ada sekarang padamu, bukanlah suamimu. Dalam hal ini engkau berkata benar."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 34, '19 Kata perempuan itu kepada-Nya: "Tuhan, nyata sekarang padaku, bahwa Engkau seorang nabi.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 35, '20 Nenek moyang kami menyembah di atas gunung ini, tetapi kamu katakan, bahwa Yerusalemlah tempat orang menyembah."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 36, '21 Kata Yesus kepadanya: "Percayalah kepada-Ku, hai perempuan, saatnya akan tiba, bahwa kamu akan menyembah Bapa bukan di gunung ini dan bukan juga di Yerusalem.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 37, '22 Kamu menyembah apa yang tidak kamu kenal, kami menyembah apa yang kami kenal, sebab keselamatan datang dari bangsa Yahudi.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 38, '23 Tetapi saatnya akan datang dan sudah tiba sekarang, bahwa penyembah-penyembah benar akan menyembah Bapa dalam roh dan kebenaran; sebab Bapa menghendaki penyembah-penyembah demikian.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 39, '24 Allah itu Roh dan barangsiapa menyembah Dia, harus menyembah-Nya dalam roh dan kebenaran."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 40, '25 Jawab perempuan itu kepada-Nya: "Aku tahu, bahwa Mesias akan datang, yang disebut juga Kristus; apabila Ia datang, Ia akan memberitakan segala sesuatu kepada kami."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 41, '26 Kata Yesus kepadanya: "Akulah Dia, yang sedang berkata-kata dengan engkau."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 42, '35. Pertobatan Orang-orang Samaria');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 43, 'Yohanes 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 44, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 45, '27 Pada waktu itu datanglah murid-murid-Nya dan mereka heran, bahwa Ia sedang bercakap-cakap dengan seorang perempuan. Tetapi tidak seorangpun yang berkata: "Apa yang Engkau kehendaki? Atau: Apa yang Engkau percakapkan dengan dia?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 46, '28 Maka perempuan itu meninggalkan tempayannya di situ lalu pergi ke kota dan berkata kepada orang-orang yang di situ:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 47, '29 "Mari, lihat! Di sana ada seorang yang mengatakan kepadaku segala sesuatu yang telah kuperbuat. Mungkinkah Dia Kristus itu?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 48, '30 Maka merekapun pergi ke luar kota lalu datang kepada Yesus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 49, '31 Sementara itu murid-murid-Nya mengajak Dia, katanya: "Rabi, makanlah."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 50, '32 Akan tetapi Ia berkata kepada mereka: "Pada-Ku ada makanan yang tidak kamu kenal."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 51, '33 Maka murid-murid itu berkata seorang kepada yang lain: "Adakah orang yang telah membawa sesuatu kepada-Nya untuk dimakan?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 52, '34 Kata Yesus kepada mereka: "Makanan-Ku ialah melakukan kehendak Dia yang mengutus Aku dan menyelesaikan pekerjaan-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 53, '35 Bukankah kamu mengatakan: Empat bulan lagi tibalah musim menuai? Tetapi Aku berkata kepadamu: Lihatlah sekelilingmu dan pandanglah ladang-ladang yang sudah menguning dan matang untuk dituai.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 54, '36 Sekarang juga penuai telah menerima upahnya dan ia mengumpulkan buah untuk hidup yang kekal, sehingga penabur dan penuai sama-sama bersukacita.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 55, '37 Sebab dalam hal ini benarlah peribahasa: Yang seorang menabur dan yang lain menuai.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 56, '38 Aku mengutus kamu untuk menuai apa yang tidak kamu usahakan; orang-orang lain berusaha dan kamu datang memetik hasil usaha mereka."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 57, '39 Dan banyak orang Samaria dari kota itu telah menjadi percaya kepada-Nya karena perkataan perempuan itu, yang bersaksi: "Ia mengatakan kepadaku segala sesuatu yang telah kuperbuat."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 58, '40 Ketika orang-orang Samaria itu sampai kepada Yesus, mereka meminta kepada-Nya, supaya Ia tinggal pada mereka; dan Iapun tinggal di situ dua hari lamanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 59, '41 Dan lebih banyak lagi orang yang menjadi percaya karena perkataan-Nya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(22, 60, '42 dan mereka berkata kepada perempuan itu: "Kami percaya, tetapi bukan lagi karena apa yang kaukatakan, sebab kami sendiri telah mendengar Dia dan kami tahu, bahwa Dialah benar-benar Juruselamat dunia."');
