INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 1, 'X. Pelayanan Kristus di Daerah Galilea');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 2, 'X.a. Periode Awal Pelayanan di Galilea');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 3, 'X.a.1 Ketibaan di Galilea');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 4, 'Yohanes 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 5, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 6, '43 Dan setelah dua hari itu Yesus berangkat dari sana ke Galilea,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 7, '44 sebab Yesus sendiri telah bersaksi, bahwa seorang nabi tidak dihormati di negerinya sendiri.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 8, '45 Maka setelah ia tiba di Galilea, orang-orang Galileapun menyambut Dia, karena mereka telah melihat segala sesuatu yang dikerjakan-Nya di Yerusalem pada pesta itu, sebab mereka sendiripun turut ke pesta itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 9, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 10, 'Matius 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 11, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 12, '17 Sejak waktu itulah Yesus memberitakan: "Bertobatlah, sebab Kerajaan Sorga sudah dekat!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 13, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 14, 'Markus 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 15, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 16, '14 Sesudah Yohanes ditangkap datanglah Yesus ke Galilea memberitakan Injil Allah,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 17, '15 kata-Nya: "Waktunya telah genap; Kerajaan Allah sudah dekat. Bertobatlah dan percayalah kepada Injil!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 18, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 19, 'Lukas 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 20, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 21, '14 Dalam kuasa Roh kembalilah Yesus ke Galilea. Dan tersiarlah kabar tentang Dia di seluruh daerah itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 22, '15 Sementara itu Ia mengajar di rumah-rumah ibadat di situ dan semua orang memuji Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 23, '37. Mujizad Kedua di Kana 27');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 24, 'Yohanes 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 25, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 26, '46 Maka Yesus kembali lagi ke Kana di Galilea, di mana Ia membuat air menjadi anggur. Dan di Kapernaum ada seorang pegawai istana, anaknya sedang sakit.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 27, '47 Ketika ia mendengar, bahwa Yesus telah datang dari Yudea ke Galilea, pergilah ia kepada-Nya lalu meminta, supaya Ia datang dan menyembuhkan anaknya, sebab anaknya itu hampir mati.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 28, '48 Maka kata Yesus kepadanya: "Jika kamu tidak melihat tanda dan mujizat, kamu tidak percaya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 29, '49 Pegawai istana itu berkata kepada-Nya: "Tuhan, datanglah sebelum anakku mati."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 30, '50 Kata Yesus kepadanya: "Pergilah, anakmu hidup!" Orang itu percaya akan perkataan yang dikatakan Yesus kepadanya, lalu pergi.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 31, '51 Ketika ia masih di tengah jalan hamba-hambanya telah datang kepadanya dengan kabar, bahwa anaknya hidup.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 32, '52 Ia bertanya kepada mereka pukul berapa anak itu mulai sembuh. Jawab mereka: "Kemarin siang pukul satu demamnya hilang."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 33, '53 Maka teringatlah ayah itu, bahwa pada saat itulah Yesus berkata kepadanya: "Anakmu hidup." Lalu iapun percaya, ia dan seluruh keluarganya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 34, '54 Dan itulah tanda kedua yang dibuat Yesus ketika Ia pulang dari Yudea ke Galilea.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 35, '38. Yesus Ditolak di Nazaret untuk Pertama Kali 79,130,183');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 36, 'Lukas 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 37, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 38, '16 Ia datang ke Nazaret tempat Ia dibesarkan, dan menurut kebiasaan-Nya pada hari Sabat Ia masuk ke rumah ibadat, lalu berdiri hendak membaca dari Alkitab.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 39, '17 Kepada-Nya diberikan kitab nabi Yesaya dan setelah dibuka-Nya, Ia menemukan nas, di mana ada tertulis:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 40, '18 "Roh Tuhan ada pada-Ku, oleh sebab Ia telah mengurapi Aku, untuk menyampaikan kabar baik kepada orang-orang miskin; dan Ia telah mengutus Aku');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 41, '19 untuk memberitakan pembebasan kepada orang-orang tawanan, dan penglihatan bagi orang-orang buta, untuk membebaskan orang-orang yang tertindas, untuk memberitakan tahun rahmat Tuhan telah datang."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 42, '20 Kemudian Ia menutup kitab itu, memberikannya kembali kepada pejabat, lalu duduk; dan mata semua orang dalam rumah ibadat itu tertuju kepada-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 43, '21 Lalu Ia memulai mengajar mereka, kata-Nya: "Pada hari ini genaplah nas ini sewaktu kamu mendengarnya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 44, '22 Dan semua orang itu membenarkan Dia dan mereka heran akan kata-kata yang indah yang diucapkan-Nya, lalu kata mereka: "Bukankah Ia ini anak Yusuf?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 45, '23 Maka berkatalah Ia kepada mereka: "Tentu kamu akan mengatakan pepatah ini kepada-Ku: Hai tabib, sembuhkanlah diri-Mu sendiri. Perbuatlah di sini juga, di tempat asal-Mu ini, segala yang kami dengar yang telah terjadi di Kapernaum!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 46, '24 Dan kata-Nya lagi: "Aku berkata kepadamu, sesungguhnya tidak ada nabi yang dihargai di tempat asalnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 47, '25 Dan Aku berkata kepadamu, dan kata-Ku ini benar: Pada zaman Elia terdapat banyak perempuan janda di Israel ketika langit tertutup selama tiga tahun dan enam bulan dan ketika bahaya kelaparan yang hebat menimpa seluruh negeri.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 48, '26 Tetapi Elia diutus bukan kepada salah seorang dari mereka, melainkan kepada seorang perempuan janda di Sarfat, di tanah Sidon.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 49, '27 Dan pada zaman nabi Elisa banyak orang kusta di Israel dan tidak ada seorangpun dari mereka yang ditahirkan, selain dari pada Naaman, orang Siria itu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 50, '28 Mendengar itu sangat marahlah semua orang yang di rumah ibadat itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 51, '29 Mereka bangun, lalu menghalau Yesus ke luar kota dan membawa Dia ke tebing gunung, tempat kota itu terletak, untuk melemparkan Dia dari tebing itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 52, '30 Tetapi Ia berjalan lewat dari tengah-tengah mereka, lalu pergi.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 53, '39. Berangkat ke Kapernaum');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 54, 'Matius 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 55, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 56, '13 Ia meninggalkan Nazaret dan diam di Kapernaum, di tepi danau, di daerah Zebulon dan Naftali,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 57, '14 supaya genaplah firman yang disampaikan oleh nabi Yesaya:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 58, '15 "Tanah Zebulon dan tanah Naftali, jalan ke laut, daerah seberang sungai Yordan, Galilea, wilayah bangsa-bangsa lain, --');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 59, '16 bangsa yang diam dalam kegelapan, telah melihat Terang yang besar dan bagi mereka yang diam di negeri yang dinaungi maut, telah terbit Terang."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 60, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 61, 'Lukas 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 62, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(23, 63, '31 Kemudian Yesus pergi ke Kapernaum, sebuah kota di Galilea, lalu mengajar di situ pada hari-hari Sabat.');
