INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 1, 'X.a.2 Penginjilan Keliling yang Pertama');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 2, '40. Memanggil Orang Galilea sebagai Murid-murid Yesus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 3, 'Lukas 5');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 5, '1 Pada suatu kali Yesus berdiri di pantai danau Genesaret, sedang orang banyak mengerumuni Dia hendak mendengarkan firman Allah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 6, '2 Ia melihat dua perahu di tepi pantai. Nelayan-nelayannya telah turun dan sedang membasuh jalanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 7, '3 Ia naik ke dalam salah satu perahu itu, yaitu perahu Simon, dan menyuruh dia supaya menolakkan perahunya sedikit jauh dari pantai. Lalu Ia duduk dan mengajar orang banyak dari atas perahu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 8, '4 Setelah selesai berbicara, Ia berkata kepada Simon: "Bertolaklah ke tempat yang dalam dan tebarkanlah jalamu untuk menangkap ikan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 9, '5 Simon menjawab: "Guru, telah sepanjang malam kami bekerja keras dan kami tidak menangkap apa-apa, tetapi karena Engkau menyuruhnya, aku akan menebarkan jala juga."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 10, '6 Dan setelah mereka melakukannya, mereka menangkap sejumlah besar ikan, sehingga jala mereka mulai koyak.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 11, '7 Lalu mereka memberi isyarat kepada teman-temannya di perahu yang lain supaya mereka datang membantunya. Dan mereka itu datang, lalu mereka bersama-sama mengisi kedua perahu itu dengan ikan hingga hampir tenggelam.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 12, '8 Ketika Simon Petrus melihat hal itu iapun tersungkur di depan Yesus dan berkata: "Tuhan, pergilah dari padaku, karena aku ini seorang berdosa."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 13, '9 Sebab ia dan semua orang yang bersama-sama dengan dia takjub oleh karena banyaknya ikan yang mereka tangkap;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 14, '10 demikian juga Yakobus dan Yohanes, anak-anak Zebedeus, yang menjadi teman Simon. Kata Yesus kepada Simon: "Jangan takut, mulai dari sekarang engkau akan menjala manusia."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 15, '11 Dan sesudah mereka menghela perahu-perahunya ke darat, merekapun meninggalkan segala sesuatu, lalu mengikut Yesus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 16, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 17, 'Matius 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 18, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 19, '18 Dan ketika Yesus sedang berjalan menyusur danau Galilea, Ia melihat dua orang bersaudara, yaitu Simon yang disebut Petrus, dan Andreas, saudaranya. Mereka sedang menebarkan jala di danau, sebab mereka penjala ikan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 20, '19 Yesus berkata kepada mereka: "Mari, ikutlah Aku, dan kamu akan Kujadikan penjala manusia."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 21, '20 Lalu merekapun segera meninggalkan jalanya dan mengikuti Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 22, '21 Dan setelah Yesus pergi dari sana, dilihat-Nya pula dua orang bersaudara, yaitu Yakobus anak Zebedeus dan Yohanes saudaranya, bersama ayah mereka, Zebedeus, sedang membereskan jala di dalam perahu. Yesus memanggil mereka');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 23, '22 dan mereka segera meninggalkan perahu serta ayahnya, lalu mengikuti Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 24, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 25, 'Markus 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 26, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 27, '16 Ketika Yesus sedang berjalan menyusur danau Galilea, Ia melihat Simon dan Andreas, saudara Simon. Mereka sedang menebarkan jala di danau, sebab mereka penjala ikan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 28, '17 Yesus berkata kepada mereka: "Mari, ikutlah Aku dan kamu akan Kujadikan penjala manusia."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 29, '18 Lalu merekapun segera meninggalkan jalanya dan mengikuti Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 30, '19 Dan setelah Yesus meneruskan perjalanan-Nya sedikit lagi, dilihat-Nya Yakobus, anak Zebedeus, dan Yohanes, saudaranya, sedang membereskan jala di dalam perahu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 31, '20 Yesus segera memanggil mereka dan mereka meninggalkan ayahnya, Zebedeus, di dalam perahu bersama orang-orang upahannya lalu mengikuti Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 32, '41. Membebaskan Orang yang Kerasukan di Bait Allah');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 33, 'Markus 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 34, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 35, '21 Mereka tiba di Kapernaum. Setelah hari Sabat mulai, Yesus segera masuk ke dalam rumah ibadat dan mengajar.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 36, '22 Mereka takjub mendengar pengajaran-Nya, sebab Ia mengajar mereka sebagai orang yang berkuasa, tidak seperti ahli-ahli Taurat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 37, '23 Pada waktu itu di dalam rumah ibadat itu ada seorang yang kerasukan roh jahat. Orang itu berteriak:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 38, '24 "Apa urusan-Mu dengan kami, hai Yesus orang Nazaret? Engkau datang hendak membinasakan kami? Aku tahu siapa Engkau: Yang Kudus dari Allah."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 39, '25 Tetapi Yesus menghardiknya, kata-Nya: "Diam, keluarlah dari padanya!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 40, '26 Roh jahat itu menggoncang-goncang orang itu, dan sambil menjerit dengan suara nyaring ia keluar dari padanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 41, '27 Mereka semua takjub, sehingga mereka memperbincangkannya, katanya: "Apa ini? Suatu ajaran baru. Ia berkata-kata dengan kuasa. Roh-roh jahatpun diperintah-Nya dan mereka taat kepada-Nya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 42, '28 Lalu tersebarlah dengan cepat kabar tentang Dia ke segala penjuru di seluruh Galilea.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 43, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 44, 'Lukas 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 45, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 46, '31 Kemudian Yesus pergi ke Kapernaum, sebuah kota di Galilea, lalu mengajar di situ pada hari-hari Sabat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 47, '32 Mereka takjub mendengar pengajaran-Nya, sebab perkataan-Nya penuh kuasa.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 48, '33 Di dalam rumah ibadat itu ada seorang yang kerasukan setan dan ia berteriak dengan suara keras:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 49, '34 "Hai Engkau, Yesus orang Nazaret, apa urusan-Mu dengan kami? Engkau datang hendak membinasakan kami? Aku tahu siapa Engkau: Yang Kudus dari Allah."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 50, '35 Tetapi Yesus menghardiknya, kata-Nya: "Diam, keluarlah dari padanya!" Dan setan itupun menghempaskan orang itu ke tengah-tengah orang banyak, lalu keluar dari padanya dan sama sekali tidak menyakitinya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 51, '36 Dan semua orang takjub, lalu berkata seorang kepada yang lain, katanya: "Alangkah hebatnya perkataan ini! Sebab dengan penuh wibawa dan kuasa Ia memberi perintah kepada roh-roh jahat dan merekapun keluar."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 52, '37 Dan tersebarlah berita tentang Dia ke mana-mana di daerah itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 53, '42. Ibu Mertua Petrus Disembuhkan');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 54, 'Markus 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 55, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 56, '29 Sekeluarnya dari rumah ibadat itu Yesus dengan Yakobus dan Yohanes pergi ke rumah Simon dan Andreas.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 57, '30 Ibu mertua Simon terbaring karena sakit demam. Mereka segera memberitahukan keadaannya kepada Yesus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 58, '31 Ia pergi ke tempat perempuan itu, dan sambil memegang tangannya Ia membangunkan dia, lalu lenyaplah demamnya. Kemudian perempuan itu melayani mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 59, '32 Menjelang malam, sesudah matahari terbenam, dibawalah kepada Yesus semua orang yang menderita sakit dan yang kerasukan setan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 60, '33 Maka berkerumunlah seluruh penduduk kota itu di depan pintu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 61, '34 Ia menyembuhkan banyak orang yang menderita bermacam-macam penyakit dan mengusir banyak setan; Ia tidak memperbolehkan setan-setan itu berbicara, sebab mereka mengenal Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 62, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 63, 'Matius 8');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 64, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 65, '14 Setibanya di rumah Petrus, Yesuspun melihat ibu mertua Petrus terbaring karena sakit demam.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 66, '15 Maka dipegang-Nya tangan perempuan itu, lalu lenyaplah demamnya. Iapun bangunlah dan melayani Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 67, '16 Menjelang malam dibawalah kepada Yesus banyak orang yang kerasukan setan dan dengan sepatah kata Yesus mengusir roh-roh itu dan menyembuhkan orang-orang yang menderita sakit.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 68, '17 Hal itu terjadi supaya genaplah firman yang disampaikan oleh nabi Yesaya: "Dialah yang memikul kelemahan kita dan menanggung penyakit kita."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 69, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 70, 'Lukas 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 71, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 72, '38 Kemudian Ia meninggalkan rumah ibadat itu dan pergi ke rumah Simon. Adapun ibu mertua Simon demam keras dan mereka meminta kepada Yesus supaya menolong dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 73, '39 Maka Ia berdiri di sisi perempuan itu, lalu menghardik demam itu, dan penyakit itupun meninggalkan dia. Perempuan itu segera bangun dan melayani mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 74, '40 Ketika matahari terbenam, semua orang membawa kepada-Nya orang-orang sakitnya, yang menderita bermacam-macam penyakit. Iapun meletakkan tangan-Nya atas mereka masing-masing dan menyembuhkan mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(24, 75, '41 Dari banyak orang keluar juga setan-setan sambil berteriak: "Engkau adalah Anak Allah." Lalu Ia dengan keras melarang mereka dan tidak memperbolehkan mereka berbicara, karena mereka tahu bahwa Ia adalah Mesias.');
