INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 1, '43. Yesus Mengajar di Galilea untuk Pertama Kali');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 2, 'Markus 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 3, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 4, '35 Pagi-pagi benar, waktu hari masih gelap, Ia bangun dan pergi ke luar. Ia pergi ke tempat yang sunyi dan berdoa di sana.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 5, '36 Tetapi Simon dan kawan-kawannya menyusul Dia;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 6, '37 waktu menemukan Dia mereka berkata: "Semua orang mencari Engkau."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 7, '38 Jawab-Nya: "Marilah kita pergi ke tempat lain, ke kota-kota yang berdekatan, supaya di sana juga Aku memberitakan Injil, karena untuk itu Aku telah datang."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 8, '39 Lalu pergilah Ia ke seluruh Galilea dan memberitakan Injil dalam rumah-rumah ibadat mereka dan mengusir setan-setan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 9, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 10, 'Matius 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 11, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 12, '23 Yesuspun berkeliling di seluruh Galilea; Ia mengajar dalam rumah-rumah ibadat dan memberitakan Injil Kerajaan Allah serta melenyapkan segala penyakit dan kelemahan di antara bangsa itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 13, '24 Maka tersiarlah berita tentang Dia di seluruh Siria dan dibawalah kepada-Nya semua orang yang buruk keadaannya, yang menderita pelbagai penyakit dan sengsara, yang kerasukan, yang sakit ayan dan yang lumpuh, lalu Yesus menyembuhkan mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 14, '25 Maka orang banyak berbondong-bondong mengikuti Dia. Mereka datang dari Galilea dan dari Dekapolis, dari Yerusalem dan dari Yudea dan dari seberang Yordan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 15, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 16, 'Lukas 4');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 17, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 18, '42 Ketika hari siang, Yesus berangkat dan pergi ke suatu tempat yang sunyi. Tetapi orang banyak mencari Dia, lalu menemukan-Nya dan berusaha menahan Dia supaya jangan meninggalkan mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 19, '43 Tetapi Ia berkata kepada mereka: "Juga di kota-kota lain Aku harus memberitakan Injil Kerajaan Allah sebab untuk itulah Aku diutus."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 20, '44 Dan Ia memberitakan Injil dalam rumah-rumah ibadat di Yudea.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 21, 'Penyembuhan Orang Kusta');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 22, 'Markus 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 23, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 24, '40 Seorang yang sakit kusta datang kepada Yesus, dan sambil berlutut di hadapan-Nya ia memohon bantuan-Nya, katanya: "Kalau Engkau mau, Engkau dapat mentahirkan aku."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 25, '41 Maka tergeraklah hati-Nya oleh belas kasihan, lalu Ia mengulurkan tangan-Nya, menjamah orang itu dan berkata kepadanya: "Aku mau, jadilah engkau tahir."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 26, '42 Seketika itu juga lenyaplah penyakit kusta orang itu, dan ia menjadi tahir.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 27, '43 Segera Ia menyuruh orang itu pergi dengan peringatan keras:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 28, '44 "Ingatlah, janganlah engkau memberitahukan apa-apa tentang hal ini kepada siapapun, tetapi pergilah, perlihatkanlah dirimu kepada imam dan persembahkanlah untuk pentahiranmu persembahan, yang diperintahkan oleh Musa, sebagai bukti bagi mereka."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 29, '45 Tetapi orang itu pergi memberitakan peristiwa itu dan menyebarkannya kemana-mana, sehingga Yesus tidak dapat lagi terang-terangan masuk ke dalam kota. Ia tinggal di luar di tempat-tempat yang sepi; namun orang terus juga datang kepada-Nya dari segala penjuru.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 30, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 31, 'Matius 8');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 32, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 33, '2 Maka datanglah seorang yang sakit kusta kepada-Nya, lalu sujud menyembah Dia dan berkata: "Tuan, jika Tuan mau, Tuan dapat mentahirkan aku."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 34, '3 Lalu Yesus mengulurkan tangan-Nya, menjamah orang itu dan berkata: "Aku mau, jadilah engkau tahir." Seketika itu juga tahirlah orang itu dari pada kustanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 35, '4 Lalu Yesus berkata kepadanya: "Ingatlah, jangan engkau memberitahukan hal ini kepada siapapun, tetapi pergilah, perlihatkanlah dirimu kepada imam dan persembahkanlah persembahan yang diperintahkan Musa, sebagai bukti bagi mereka."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 36, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 37, 'Lukas 5');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 38, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 39, '12 Pada suatu kali Yesus berada dalam sebuah kota. Di situ ada seorang yang penuh kusta. Ketika ia melihat Yesus, tersungkurlah ia dan memohon: "Tuan, jika Tuan mau, Tuan dapat mentahirkan aku."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 40, '13 Lalu Yesus mengulurkan tangan-Nya, menjamah orang itu, dan berkata: "Aku mau, jadilah engkau tahir." Seketika itu juga lenyaplah penyakit kustanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 41, '14 Yesus melarang orang itu memberitahukannya kepada siapapun juga dan berkata: "Pergilah, perlihatkanlah dirimu kepada imam dan persembahkanlah untuk pentahiranmu persembahan seperti yang diperintahkan Musa, sebagai bukti bagi mereka."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 42, '15 Tetapi kabar tentang Yesus makin jauh tersiar dan datanglah orang banyak berbondong-bondong kepada-Nya untuk mendengar Dia dan untuk disembuhkan dari penyakit mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 43, '16 Akan tetapi Ia mengundurkan diri ke tempat-tempat yang sunyi dan berdoa.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 44, 'Orang Lumpuh Disembuhkan');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 45, 'Markus 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 46, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 47, '1 Kemudian, sesudah lewat beberapa hari, waktu Yesus datang lagi ke Kapernaum, tersiarlah kabar, bahwa Ia ada di rumah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 48, '2 Maka datanglah orang-orang berkerumun sehingga tidak ada lagi tempat, bahkan di muka pintupun tidak. Sementara Ia memberitakan firman kepada mereka,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 49, '3 ada orang-orang datang membawa kepada-Nya seorang lumpuh, digotong oleh empat orang.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 50, '4 Tetapi mereka tidak dapat membawanya kepada-Nya karena orang banyak itu, lalu mereka membuka atap yang di atas-Nya; sesudah terbuka mereka menurunkan tilam, tempat orang lumpuh itu terbaring.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 51, '5 Ketika Yesus melihat iman mereka, berkatalah Ia kepada orang lumpuh itu: "Hai anak-Ku, dosamu sudah diampuni!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 52, '6 Tetapi di situ ada juga duduk beberapa ahli Taurat, mereka berpikir dalam hatinya:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 53, '7 "Mengapa orang ini berkata begitu? Ia menghujat Allah. Siapa yang dapat mengampuni dosa selain dari pada Allah sendiri?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 54, '8 Tetapi Yesus segera mengetahui dalam hati-Nya, bahwa mereka berpikir demikian, lalu Ia berkata kepada mereka: "Mengapa kamu berpikir begitu dalam hatimu?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 55, '9 Manakah lebih mudah, mengatakan kepada orang lumpuh ini: Dosamu sudah diampuni, atau mengatakan: Bangunlah, angkatlah tilammu dan berjalan?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 56, '10 Tetapi supaya kamu tahu, bahwa di dunia ini Anak Manusia berkuasa mengampuni dosa" --berkatalah Ia kepada orang lumpuh itu--:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 57, '11 "Kepadamu Kukatakan, bangunlah, angkatlah tempat tidurmu dan pulanglah ke rumahmu!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 58, '12 Dan orang itupun bangun, segera mengangkat tempat tidurnya dan pergi ke luar di hadapan orang-orang itu, sehingga mereka semua takjub lalu memuliakan Allah, katanya: "Yang begini belum pernah kita lihat."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 59, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 60, 'Matius 9');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 61, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 62, '1 Sesudah itu naiklah Yesus ke dalam perahu lalu menyeberang. Kemudian sampailah Ia ke kota-Nya sendiri.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 63, '2 Maka dibawa oranglah kepada-Nya seorang lumpuh yang terbaring di tempat tidurnya. Ketika Yesus melihat iman mereka, berkatalah Ia kepada orang lumpuh itu: "Percayalah, hai anak-Ku, dosamu sudah diampuni."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 64, '3 Maka berkatalah beberapa orang ahli Taurat dalam hatinya: "Ia menghujat Allah."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 65, '4 Tetapi Yesus mengetahui pikiran mereka, lalu berkata: "Mengapa kamu memikirkan hal-hal yang jahat di dalam hatimu?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 66, '5 Manakah lebih mudah, mengatakan: Dosamu sudah diampuni, atau mengatakan: Bangunlah dan berjalanlah?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 67, '6 Tetapi supaya kamu tahu, bahwa di dunia ini Anak Manusia berkuasa mengampuni dosa" --lalu berkatalah Ia kepada orang lumpuh itu--:"Bangunlah, angkatlah tempat tidurmu dan pulanglah ke rumahmu!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 68, '7 Dan orang itupun bangun lalu pulang.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 69, '8 Maka orang banyak yang melihat hal itu takut lalu memuliakan Allah yang telah memberikan kuasa sedemikian itu kepada manusia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 70, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 71, 'Lukas 5');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 72, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 73, '17 Pada suatu hari ketika Yesus mengajar, ada beberapa orang Farisi dan ahli Taurat duduk mendengarkan-Nya. Mereka datang dari semua desa di Galilea dan Yudea dan dari Yerusalem. Kuasa Tuhan menyertai Dia, sehingga Ia dapat menyembuhkan orang sakit.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 74, '18 Lalu datanglah beberapa orang mengusung seorang lumpuh di atas tempat tidur; mereka berusaha membawa dia masuk dan meletakkannya di hadapan Yesus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 75, '19 Karena mereka tidak dapat membawanya masuk berhubung dengan banyaknya orang di situ, naiklah mereka ke atap rumah, lalu membongkar atap itu, dan menurunkan orang itu dengan tempat tidurnya ke tengah-tengah orang banyak tepat di depan Yesus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 76, '20 Ketika Yesus melihat iman mereka, berkatalah Ia: "Hai saudara, dosamu sudah diampuni."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 77, '21 Tetapi ahli-ahli Taurat dan orang-orang Farisi berpikir dalam hatinya: "Siapakah orang yang menghujat Allah ini? Siapa yang dapat mengampuni dosa selain dari pada Allah sendiri?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 78, '22 Akan tetapi Yesus mengetahui pikiran mereka, lalu berkata kepada mereka: "Apakah yang kamu pikirkan dalam hatimu?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 79, '23 Manakah lebih mudah, mengatakan: Dosamu sudah diampuni, atau mengatakan: Bangunlah, dan berjalanlah?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 80, '24 Tetapi supaya kamu tahu, bahwa di dunia ini Anak Manusia berkuasa mengampuni dosa" --berkatalah Ia kepada orang lumpuh itu--:"Kepadamu Kukatakan, bangunlah, angkatlah tempat tidurmu dan pulanglah ke rumahmu!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 81, '25 Dan seketika itu juga bangunlah ia, di depan mereka, lalu mengangkat tempat tidurnya dan pulang ke rumahnya sambil memuliakan Allah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 82, '26 Semua orang itu takjub, lalu memuliakan Allah, dan mereka sangat takut, katanya: "Hari ini kami telah menyaksikan hal-hal yang sangat mengherankan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 83, 'Matius Dipanggil sebagai Murid Yesus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 84, 'Markus 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 85, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 86, '13 Sesudah itu Yesus pergi lagi ke pantai danau, dan seluruh orang banyak datang kepada-Nya, lalu Ia mengajar mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 87, '14 Kemudian ketika Ia berjalan lewat di situ, Ia melihat Lewi anak Alfeus duduk di rumah cukai lalu Ia berkata kepadanya: "Ikutlah Aku!" Maka berdirilah Lewi lalu mengikuti Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 88, '15 Kemudian ketika Yesus makan di rumah orang itu, banyak pemungut cukai dan orang berdosa makan bersama-sama dengan Dia dan murid-murid-Nya, sebab banyak orang yang mengikuti Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 89, '16 Pada waktu ahli-ahli Taurat dari golongan Farisi melihat, bahwa Ia makan dengan pemungut cukai dan orang berdosa itu, berkatalah mereka kepada murid-murid-Nya: "Mengapa Ia makan bersama-sama dengan pemungut cukai dan orang berdosa?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 90, '17 Yesus mendengarnya dan berkata kepada mereka: "Bukan orang sehat yang memerlukan tabib, tetapi orang sakit; Aku datang bukan untuk memanggil orang benar, melainkan orang berdosa."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 91, '18 Pada suatu kali ketika murid-murid Yohanes dan orang-orang Farisi sedang berpuasa, datanglah orang-orang dan mengatakan kepada Yesus: "Mengapa murid-murid Yohanes dan murid-murid orang Farisi berpuasa, tetapi murid-murid-Mu tidak?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 92, '19 Jawab Yesus kepada mereka: "Dapatkah sahabat-sahabat mempelai laki-laki berpuasa sedang mempelai itu bersama mereka? Selama mempelai itu bersama mereka, mereka tidak dapat berpuasa.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 93, '20 Tetapi waktunya akan datang mempelai itu diambil dari mereka, dan pada waktu itulah mereka akan berpuasa.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 94, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 95, 'Matius 9');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 96, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 97, '9 Setelah Yesus pergi dari situ, Ia melihat seorang yang bernama Matius duduk di rumah cukai, lalu Ia berkata kepadanya: "Ikutlah Aku." Maka berdirilah Matius lalu mengikut Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 98, '10 Kemudian ketika Yesus makan di rumah Matius, datanglah banyak pemungut cukai dan orang berdosa dan makan bersama-sama dengan Dia dan murid-murid-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 99, '11 Pada waktu orang Farisi melihat hal itu, berkatalah mereka kepada murid-murid Yesus: "Mengapa gurumu makan bersama-sama dengan pemungut cukai dan orang berdosa?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 100, '12 Yesus mendengarnya dan berkata: "Bukan orang sehat yang memerlukan tabib, tetapi orang sakit.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 101, '13 Jadi pergilah dan pelajarilah arti firman ini: Yang Kukehendaki ialah belas kasihan dan bukan persembahan, karena Aku datang bukan untuk memanggil orang benar, melainkan orang berdosa."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 102, '14 Kemudian datanglah murid-murid Yohanes kepada Yesus dan berkata: "Mengapa kami dan orang Farisi berpuasa, tetapi murid-murid-Mu tidak?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 103, '15 Jawab Yesus kepada mereka: "Dapatkah sahabat-sahabat mempelai laki-laki berdukacita selama mempelai itu bersama mereka? Tetapi waktunya akan datang mempelai itu diambil dari mereka dan pada waktu itulah mereka akan berpuasa.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 104, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 105, 'Lukas 5');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 106, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 107, '27 Kemudian, ketika Yesus pergi ke luar, Ia melihat seorang pemungut cukai, yang bernama Lewi, sedang duduk di rumah cukai. Yesus berkata kepadanya: "Ikutlah Aku!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 108, '28 Maka berdirilah Lewi dan meninggalkan segala sesuatu, lalu mengikut Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 109, '29 Dan Lewi mengadakan suatu perjamuan besar untuk Dia di rumahnya dan sejumlah besar pemungut cukai dan orang-orang lain turut makan bersama-sama dengan Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 110, '30 Orang-orang Farisi dan ahli-ahli Taurat bersungut-sungut kepada murid-murid Yesus, katanya: "Mengapa kamu makan dan minum bersama-sama dengan pemungut cukai dan orang berdosa?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 111, '31 Lalu jawab Yesus kepada mereka, kata-Nya: "Bukan orang sehat yang memerlukan tabib, tetapi orang sakit;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 112, '32 Aku datang bukan untuk memanggil orang benar, tetapi orang berdosa, supaya mereka bertobat."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 113, '33 Orang-orang Farisi itu berkata pula kepada Yesus: "Murid-murid Yohanes sering berpuasa dan sembahyang, demikian juga murid-murid orang Farisi, tetapi murid-murid-Mu makan dan minum."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 114, '34 Jawab Yesus kepada mereka: "Dapatkah sahabat mempelai laki-laki disuruh berpuasa, sedang mempelai itu bersama mereka?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 115, '35 Tetapi akan datang waktunya, apabila mempelai itu diambil dari mereka, pada waktu itulah mereka akan berpuasa."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 116, 'Perumpamaan tentang Hal yang Baru dan Hal yang Lama');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 117, 'Lukas 5');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 118, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 119, '36 Ia mengatakan juga suatu perumpamaan kepada mereka: "Tidak seorangpun mengoyakkan secarik kain dari baju yang baru untuk menambalkannya pada baju yang tua. Jika demikian, yang baru itu juga akan koyak dan pada yang tua itu tidak akan cocok kain penambal yang dikoyakkan dari yang baru itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 120, '37 Demikian juga tidak seorangpun mengisikan anggur yang baru ke dalam kantong kulit yang tua, karena jika demikian, anggur yang baru itu akan mengoyakkan kantong itu dan anggur itu akan terbuang dan kantong itupun hancur.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 121, '38 Tetapi anggur yang baru harus disimpan dalam kantong yang baru pula.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 122, '39 Dan tidak seorangpun yang telah minum anggur tua ingin minum anggur yang baru, sebab ia akan berkata: Anggur yang tua itu baik."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 123, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 124, 'Matius 9');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 125, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 126, '16 Tidak seorangpun menambalkan secarik kain yang belum susut pada baju yang tua, karena jika demikian kain penambal itu akan mencabik baju itu, lalu makin besarlah koyaknya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 127, '17 Begitu pula anggur yang baru tidak diisikan ke dalam kantong kulit yang tua, karena jika demikian kantong itu akan koyak sehingga anggur itu terbuang dan kantong itupun hancur. Tetapi anggur yang baru disimpan orang dalam kantong yang baru pula, dan dengan demikian terpeliharalah kedua-duanya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 128, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 129, 'Markus 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 130, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 131, '21 Tidak seorangpun menambalkan secarik kain yang belum susut pada baju yang tua, karena jika demikian kain penambal itu akan mencabiknya, yang baru mencabik yang tua, lalu makin besarlah koyaknya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(25, 132, '22 Demikian juga tidak seorangpun mengisikan anggur yang baru ke dalam kantong kulit yang tua, karena jika demikian anggur itu akan mengoyakkan kantong itu, sehingga anggur itu dan kantongnya dua-duanya terbuang. Tetapi anggur yang baru hendaknya disimpan dalam kantong yang baru pula."');
