INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 1, 'X.a.3 Kunjungan Singkat ke Yerusalem');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 2, '48. Paskah Kedua dan Penyembuhan di Betesda');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 3, 'Yohanes 5');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 5, '1 Sesudah itu ada hari raya orang Yahudi, dan Yesus berangkat ke Yerusalem.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 6, '2 Di Yerusalem dekat Pintu Gerbang Domba ada sebuah kolam, yang dalam bahasa Ibrani disebut Betesda; ada lima serambinya');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 7, '3 dan di serambi-serambi itu berbaring sejumlah besar orang sakit: orang-orang buta, orang-orang timpang dan orang-orang lumpuh, yang menantikan goncangan air kolam itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 8, '4 Sebab sewaktu-waktu turun malaikat Tuhan ke kolam itu dan menggoncangkan air itu; barangsiapa yang terdahulu masuk ke dalamnya sesudah goncangan air itu, menjadi sembuh, apapun juga penyakitnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 9, '5 Di situ ada seorang yang sudah tiga puluh delapan tahun lamanya sakit.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 10, '6 Ketika Yesus melihat orang itu berbaring di situ dan karena Ia tahu, bahwa ia telah lama dalam keadaan itu, berkatalah Ia kepadanya: "Maukah engkau sembuh?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 11, '7 Jawab orang sakit itu kepada-Nya: "Tuhan, tidak ada orang yang menurunkan aku ke dalam kolam itu apabila airnya mulai goncang, dan sementara aku menuju ke kolam itu, orang lain sudah turun mendahului aku."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 12, '8 Kata Yesus kepadanya: "Bangunlah, angkatlah tilammu dan berjalanlah."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 13, '9 Dan pada saat itu juga sembuhlah orang itu lalu ia mengangkat tilamnya dan berjalan. Tetapi hari itu hari Sabat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 14, '10 Karena itu orang-orang Yahudi berkata kepada orang yang baru sembuh itu: "Hari ini hari Sabat dan tidak boleh engkau memikul tilammu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 15, '11 Akan tetapi ia menjawab mereka: "Orang yang telah menyembuhkan aku, dia yang mengatakan kepadaku: Angkatlah tilammu dan berjalanlah."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 16, '12 Mereka bertanya kepadanya: "Siapakah orang itu yang berkata kepadamu: Angkatlah tilammu dan berjalanlah?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 17, '13 Tetapi orang yang baru sembuh itu tidak tahu siapa orang itu, sebab Yesus telah menghilang ke tengah-tengah orang banyak di tempat itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 18, '14 Kemudian Yesus bertemu dengan dia dalam Bait Allah lalu berkata kepadanya: "Engkau telah sembuh; jangan berbuat dosa lagi, supaya padamu jangan terjadi yang lebih buruk."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 19, '15 Orang itu keluar, lalu menceriterakan kepada orang-orang Yahudi, bahwa Yesuslah yang telah menyembuhkan dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 20, '16 Dan karena itu orang-orang Yahudi berusaha menganiaya Yesus, karena Ia melakukan hal-hal itu pada hari Sabat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 21, '17 Tetapi Ia berkata kepada mereka: "Bapa-Ku bekerja sampai sekarang, maka Akupun bekerja juga."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(26, 22, '18 Sebab itu orang-orang Yahudi lebih berusaha lagi untuk membunuh-Nya, bukan saja karena Ia meniadakan hari Sabat, tetapi juga karena Ia mengatakan bahwa Allah adalah Bapa-Nya sendiri dan dengan demikian menyamakan diri-Nya dengan Allah.');
