INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 1, '49. Kesetaraan Yesus Dengan Tuhan');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 2, 'Yohanes 5');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 3, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 4, '19 Maka Yesus menjawab mereka, kata-Nya: "Aku berkata kepadamu, sesungguhnya Anak tidak dapat mengerjakan sesuatu dari diri-Nya sendiri, jikalau tidak Ia melihat Bapa mengerjakannya; sebab apa yang dikerjakan Bapa, itu juga yang dikerjakan Anak.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 5, '20 Sebab Bapa mengasihi Anak dan Ia menunjukkan kepada-Nya segala sesuatu yang dikerjakan-Nya sendiri, bahkan Ia akan menunjukkan kepada-Nya pekerjaan-pekerjaan yang lebih besar lagi dari pada pekerjaan-pekerjaan itu, sehingga kamu menjadi heran.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 6, '21 Sebab sama seperti Bapa membangkitkan orang-orang mati dan menghidupkannya, demikian juga Anak menghidupkan barangsiapa yang dikehendaki-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 7, '22 Bapa tidak menghakimi siapapun, melainkan telah menyerahkan penghakiman itu seluruhnya kepada Anak,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 8, '23 supaya semua orang menghormati Anak sama seperti mereka menghormati Bapa. Barangsiapa tidak menghormati Anak, ia juga tidak menghormati Bapa, yang mengutus Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 9, '24 Aku berkata kepadamu: Sesungguhnya barangsiapa mendengar perkataan-Ku dan percaya kepada Dia yang mengutus Aku, ia mempunyai hidup yang kekal dan tidak turut dihukum, sebab ia sudah pindah dari dalam maut ke dalam hidup.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 10, '25 Aku berkata kepadamu: Sesungguhnya saatnya akan tiba dan sudah tiba, bahwa orang-orang mati akan mendengar suara Anak Allah, dan mereka yang mendengarnya, akan hidup.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 11, '26 Sebab sama seperti Bapa mempunyai hidup dalam diri-Nya sendiri, demikian juga diberikan-Nya Anak mempunyai hidup dalam diri-Nya sendiri.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 12, '27 Dan Ia telah memberikan kuasa kepada-Nya untuk menghakimi, karena Ia adalah Anak Manusia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 13, '28 Janganlah kamu heran akan hal itu, sebab saatnya akan tiba, bahwa semua orang yang di dalam kuburan akan mendengar suara-Nya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 14, '29 dan mereka yang telah berbuat baik akan keluar dan bangkit untuk hidup yang kekal, tetapi mereka yang telah berbuat jahat akan bangkit untuk dihukum.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 15, '30 Aku tidak dapat berbuat apa-apa dari diri-Ku sendiri; Aku menghakimi sesuai dengan apa yang Aku dengar, dan penghakiman-Ku adil, sebab Aku tidak menuruti kehendak-Ku sendiri, melainkan kehendak Dia yang mengutus Aku.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 16, '31 Kalau Aku bersaksi tentang diri-Ku sendiri, maka kesaksian-Ku itu tidak benar;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 17, '32 ada yang lain yang bersaksi tentang Aku dan Aku tahu, bahwa kesaksian yang diberikan-Nya tentang Aku adalah benar.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 18, '33 Kamu telah mengirim utusan kepada Yohanes dan ia telah bersaksi tentang kebenaran;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 19, '34 tetapi Aku tidak memerlukan kesaksian dari manusia, namun Aku mengatakan hal ini, supaya kamu diselamatkan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 20, '35 Ia adalah pelita yang menyala dan yang bercahaya dan kamu hanya mau menikmati seketika saja cahayanya itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 21, '36 Tetapi Aku mempunyai suatu kesaksian yang lebih penting dari pada kesaksian Yohanes, yaitu segala pekerjaan yang diserahkan Bapa kepada-Ku, supaya Aku melaksanakannya. Pekerjaan itu juga yang Kukerjakan sekarang, dan itulah yang memberi kesaksian tentang Aku, bahwa Bapa yang mengutus Aku.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 22, '37 Bapa yang mengutus Aku, Dialah yang bersaksi tentang Aku. Kamu tidak pernah mendengar suara-Nya, rupa-Nyapun tidak pernah kamu lihat,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 23, '38 dan firman-Nya tidak menetap di dalam dirimu, sebab kamu tidak percaya kepada Dia yang diutus-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 24, '39 Kamu menyelidiki Kitab-kitab Suci, sebab kamu menyangka bahwa oleh-Nya kamu mempunyai hidup yang kekal, tetapi walaupun Kitab-kitab Suci itu memberi kesaksian tentang Aku,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 25, '40 namun kamu tidak mau datang kepada-Ku untuk memperoleh hidup itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 26, '41 Aku tidak memerlukan hormat dari manusia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 27, '42 Tetapi tentang kamu, memang Aku tahu bahwa di dalam hatimu kamu tidak mempunyai kasih akan Allah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 28, '43 Aku datang dalam nama Bapa-Ku dan kamu tidak menerima Aku; jikalau orang lain datang atas namanya sendiri, kamu akan menerima dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 29, '44 Bagaimanakah kamu dapat percaya, kamu yang menerima hormat seorang dari yang lain dan yang tidak mencari hormat yang datang dari Allah yang Esa?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 30, '45 Jangan kamu menyangka, bahwa Aku akan mendakwa kamu di hadapan Bapa; yang mendakwa kamu adalah Musa, yaitu Musa, yang kepadanya kamu menaruh pengharapanmu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 31, '46 Sebab jikalau kamu percaya kepada Musa, tentu kamu akan percaya juga kepada-Ku, sebab ia telah menulis tentang Aku.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(27, 32, '47 Tetapi jikalau kamu tidak percaya akan apa yang ditulisnya, bagaimanakah kamu akan percaya akan apa yang Kukatakan?"');
