INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 1, 'X.a.4 Kembali ke Galilea');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 2, '50. Memetik Gandum pada Hari Sabat');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 3, 'Matius 12');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 5, ':1 Pada waktu itu, pada hari Sabat, Yesus berjalan di ladang gandum. Karena lapar, murid-murid-Nya memetik bulir gandum dan memakannya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 6, ':2 Melihat itu, berkatalah orang-orang Farisi kepada-Nya: "Lihatlah, murid-murid-Mu berbuat sesuatu yang tidak diperbolehkan pada hari Sabat."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 7, ':3 Tetapi jawab Yesus kepada mereka: "Tidakkah kamu baca apa yang dilakukan Daud, ketika ia dan mereka yang mengikutinya lapar,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 8, ':4 bagaimana ia masuk ke dalam Rumah Allah dan bagaimana mereka makan roti sajian yang tidak boleh dimakan, baik olehnya maupun oleh mereka yang mengikutinya, kecuali oleh imam-imam?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 9, ':5 Atau tidakkah kamu baca dalam kitab Taurat, bahwa pada hari-hari Sabat, imam-imam melanggar hukum Sabat di dalam Bait Allah, namun tidak bersalah?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 10, ':6 Aku berkata kepadamu: Di sini ada yang melebihi Bait Allah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 11, ':7 Jika memang kamu mengerti maksud firman ini: Yang Kukehendaki ialah belas kasihan dan bukan persembahan, tentu kamu tidak menghukum orang yang tidak bersalah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 12, ':8 Karena Anak Manusia adalah Tuhan atas hari Sabat."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 13, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 14, 'Markus 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 15, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 16, '23 Pada suatu kali, pada hari Sabat, Yesus berjalan di ladang gandum, dan sementara berjalan murid-murid-Nya memetik bulir gandum.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 17, '24 Maka kata orang-orang Farisi kepada-Nya: "Lihat! Mengapa mereka berbuat sesuatu yang tidak diperbolehkan pada hari Sabat?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 18, '25 Jawab-Nya kepada mereka: "Belum pernahkah kamu baca apa yang dilakukan Daud, ketika ia dan mereka yang mengikutinya kekurangan dan kelaparan,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 19, '26 bagaimana ia masuk ke dalam Rumah Allah waktu Abyatar menjabat sebagai Imam Besar lalu makan roti sajian itu--yang tidak boleh dimakan kecuali oleh imam-imam--dan memberinya juga kepada pengikut-pengikutn');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 20, '27 Lalu kata Yesus kepada mereka: "Hari Sabat diadakan untuk manusia dan bukan manusia untuk hari Sabat,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 21, '28 jadi Anak Manusia adalah juga Tuhan atas hari Sabat."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 22, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 23, 'Lukas 6');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 24, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 25, '1 Pada suatu hari Sabat, ketika Yesus berjalan di ladang gandum, murid-murid-Nya memetik bulir gandum dan memakannya, sementara mereka menggisarnya dengan tangannya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 26, '2 Tetapi beberapa orang Farisi berkata: "Mengapa kamu berbuat sesuatu yang tidak diperbolehkan pada hari Sabat?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 27, '3 Lalu Yesus menjawab mereka: "Tidakkah kamu baca apa yang dilakukan oleh Daud, ketika ia dan mereka yang mengikutinya lapar,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 28, '4 bagaimana ia masuk ke dalam Rumah Allah dan mengambil roti sajian, lalu memakannya dan memberikannya kepada pengikut-pengikutnya, padahal roti itu tidak boleh dimakan kecuali oleh imam-imam?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 29, '5 Kata Yesus lagi kepada mereka: "Anak Manusia adalah Tuhan atas hari Sabat."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 30, '51. Yesus Menyembuhkan Orang Lumpuh pada Hari Sabat');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 31, 'Lukas 6');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 32, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 33, '6 Pada suatu hari Sabat lain, Yesus masuk ke rumah ibadat, lalu mengajar. Di situ ada seorang yang mati tangan kanannya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 34, '7 Ahli-ahli Taurat dan orang-orang Farisi mengamat-amati Yesus, kalau-kalau Ia menyembuhkan orang pada hari Sabat, supaya mereka dapat alasan untuk mempersalahkan Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 35, '8 Tetapi Ia mengetahui pikiran mereka, lalu berkata kepada orang yang mati tangannya itu: "Bangunlah dan berdirilah di tengah!" Maka bangunlah orang itu dan berdiri.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 36, '9 Lalu Yesus berkata kepada mereka: "Aku bertanya kepada kamu: Manakah yang diperbolehkan pada hari Sabat, berbuat baik atau berbuat jahat, menyelamatkan nyawa orang atau membinasakannya?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 37, '10 Sesudah itu Ia memandang keliling kepada mereka semua, lalu berkata kepada orang sakit itu: "Ulurkanlah tanganmu!" Orang itu berbuat demikian dan sembuhlah tangannya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 38, '11 Maka meluaplah amarah mereka, lalu mereka berunding, apakah yang akan mereka lakukan terhadap Yesus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 39, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 40, 'Matius 12');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 41, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 42, ':9 Setelah pergi dari sana, Yesus masuk ke rumah ibadat mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 43, ':10 Di situ ada seorang yang mati sebelah tangannya. Mereka bertanya kepada-Nya: "Bolehkah menyembuhkan orang pada hari Sabat?" Maksud mereka ialah supaya dapat mempersalahkan Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 44, ':11 Tetapi Yesus berkata kepada mereka: "Jika seorang dari antara kamu mempunyai seekor domba dan domba itu terjatuh ke dalam lobang pada hari Sabat, tidakkah ia akan menangkapnya dan mengeluarkannya?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 45, ':12 Bukankah manusia jauh lebih berharga dari pada domba? Karena itu boleh berbuat baik pada hari Sabat."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 46, ':13 Lalu kata Yesus kepada orang itu: "Ulurkanlah tanganmu!" Dan ia mengulurkannya, maka pulihlah tangannya itu, dan menjadi sehat seperti tangannya yang lain.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 47, ':14 Lalu keluarlah orang-orang Farisi itu dan bersekongkol untuk membunuh Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 48, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 49, 'Markus 3');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 50, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 51, '1 Kemudian Yesus masuk lagi ke rumah ibadat. Di situ ada seorang yang mati sebelah tangannya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 52, '2 Mereka mengamat-amati Yesus, kalau-kalau Ia menyembuhkan orang itu pada hari Sabat, supaya mereka dapat mempersalahkan Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 53, '3 Kata Yesus kepada orang yang mati sebelah tangannya itu: "Mari, berdirilah di tengah!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 54, '4 Kemudian kata-Nya kepada mereka: "Manakah yang diperbolehkan pada hari Sabat, berbuat baik atau berbuat jahat, menyelamatkan nyawa orang atau membunuh orang?" Tetapi mereka itu diam saja.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 55, '5 Ia berdukacita karena kedegilan mereka dan dengan marah Ia memandang sekeliling-Nya kepada mereka lalu Ia berkata kepada orang itu: "Ulurkanlah tanganmu!" Dan ia mengulurkannya, maka sembuhlah tangannya itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(28, 56, '6 Lalu keluarlah orang-orang Farisi dan segera bersekongkol dengan orang-orang Herodian untuk membunuh Dia.');
