INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '55. Menyembuhkan Hamba Seorang Perwira Kapernaum');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '(Lukas 7:1-10, <i>Matius 8:5-13</i>)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '1 Setelah Yesus selesai berbicara di depan orang banyak, masuklah Ia ke Kapernaum.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '2 Disitu ada seorang perwira yang mempunyai seorang hamba, yang sangat dihargainya. Hamba itu sedang sakit keras dan hampir mati.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '3 Ketika perwira itu mendengar tentang Yesus, ia menyuruh beberapa orang tua-tua Yahudi kepada-Nya untuk meminta, supaya Ia datang dan menyembuhkan hambanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '4 Mereka datang kepada Yesus dan dengan sangat mereka meminta pertolongan-Nya, katanya: "Ia layak Engkau tolong,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '5 sebab ia mengasihi bangsa kita dan dialah yang menanggung pembangunan rumah ibadat kami."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '6 Lalu Yesus pergi bersama-sama dengan mereka. Ketika Ia tidak jauh lagi dari rumah perwira itu, perwira itu menyuruh sahabat-sahabatnya untuk mengatakan kepada-Nya:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '<i>6 "Tuan, hambaku terbaring di rumah karena sakit lumpuh dan ia sangat menderita."</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '<i>7 Yesus berkata kepadanya: "Aku akan datang menyembuhkannya."</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '<i>8 Tetapi jawab perwira itu kepada-Nya:</i> "Tuan, janganlah bersusah-susah, sebab aku tidak layak menerima Tuan di dalam rumahku;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '7 sebab itu aku juga menganggap diriku tidak layak untuk datang kepada-Mu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, 'Tetapi katakan saja sepatah kata, maka hambaku itu akan sembuh.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '8 Sebab aku sendiri seorang bawahan, dan di bawahku ada pula prajurit. Jika aku berkata kepada salah seorang prajurit itu: Pergi!, maka ia pergi, dan kepada seorang lagi: Datang!, maka ia datang, ataupun kepada hambaku: Kerjakanlah ini!, maka ia mengerjakannya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '9 Setelah Yesus mendengar perkataan itu, Ia heran akan dia, dan sambil berpaling kepada orang banyak yang mengikuti Dia, Ia berkata:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '<i>11 Banyak orang akan datang dari Timur dan Barat dan duduk makan bersama-sama dengan Abraham, Ishak dan Yakub di dalam Kerajaan Sorga,</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '<i>12 sedangkan anak-anak Kerajaan itu akan dicampakkan ke dalam kegelapan yang paling gelap, di sanalah akan terdapat ratap dan kertak gigi."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '<i>13 Lalu Yesus berkata kepada perwira itu: "Pulanglah dan jadilah kepadamu seperti yang engkau percaya." Maka pada saat itu juga sembuhlah hambanya.  "Aku berkata kepadamu, iman sebesar ini tidak pernah Aku jumpai, sekalipun di antara orang Israel!"</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '10 Dan setelah orang-orang yang disuruh itu kembali ke rumah, didapatinyalah hamba itu telah sehat kembali.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '56. Yesus Membangkitkan Anak Seorang Janda di Nain');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '(Lukas 7:11-17)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 3, '11 Kemudian Yesus pergi ke suatu kota yang bernama Nain. Murid-murid-Nya pergi bersama-sama dengan Dia, dan juga orang banyak menyertai-Nya berbondong-bondong.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 4, '12 Setelah Ia dekat pintu gerbang kota, ada orang mati diusung ke luar, anak laki-laki, anak tunggal ibunya yang sudah janda, dan banyak orang dari kota itu menyertai janda itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 5, '13 Dan ketika Tuhan melihat janda itu, tergeraklah hati-Nya oleh belas kasihan, lalu Ia berkata kepadanya: "Jangan menangis!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 6, '14 Sambil menghampiri usungan itu Ia menyentuhnya, dan sedang para pengusung berhenti, Ia berkata: "Hai anak muda, Aku berkata kepadamu, bangkitlah!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 7, '15 Maka bangunlah orang itu dan duduk dan mulai berkata-kata, dan Yesus menyerahkannya kepada ibunya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 8, '16 Semua orang itu ketakutan dan mereka memuliakan Allah, sambil berkata: "Seorang nabi besar telah muncul di tengah-tengah kita," dan "Allah telah melawat umat-Nya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 9, '17 Maka tersiarlah kabar tentang Yesus di seluruh Yudea dan di seluruh daerah sekitarnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '57. Yesus dan Yohanes Pembaptis');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 1, '(Matius 11:2-19, <i>Lukas 7:18-35</i>)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 3, '2 Di dalam penjara Yohanes mendengar tentang pekerjaan Kristus <i>(dari murid-muridnya)</i>,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 4, '3 lalu menyuruh <i>(dua)</i> murid-muridnya datang dan kepada Tuhan: <i>Ketika kedua orang itu sampai kepada Yesus, mereka berkata: “Yohanes Pembaptis menyuruh kami bertanya kepadaMu:</i> "Engkaukah yang akan datang itu atau haruskah kami menantikan orang lain?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 27, '<i>21 Pada saat itu Yesus menyembuhkan banyak orang dari segala penyakit dan penderitaan dan dari roh-roh jahat, dan Ia mengaruniakan penglihatan kepada banyak orang buta.</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 5, '4 Dan Yesus menjawab mereka: "Pergilah dan katakanlah kepada Yohanes apa yang kamu dengar dan kamu lihat:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 6, '5 orang buta melihat, orang lumpuh berjalan, orang kusta menjadi tahir, orang tuli mendengar, orang mati dibangkitkan dan kepada orang miskin diberitakan kabar baik.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 7, '6 Dan berbahagialah orang yang tidak menjadi kecewa dan menolak Aku."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 8, '7 Setelah murid-murid <i>(suruhan)</i> Yohanes pergi, mulailah Yesus berbicara kepada orang banyak itu tentang Yohanes: "Untuk apakah kamu pergi ke padang gurun? Melihat buluh yang digoyangkan angin kian ke mari?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 9, '8 Atau untuk apakah kamu pergi? Melihat orang yang berpakaian halus? Orang yang berpakaian halus <i>(indah dan yang hidup mewah)</i> itu tempatnya di istana raja.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 10, '9 Jadi untuk apakah kamu pergi? Melihat nabi? Benar, dan Aku berkata kepadamu, bahkan lebih dari pada nabi.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 11, '10 Karena tentang dia ada tertulis: Lihatlah, Aku menyuruh utusan-Ku mendahului Engkau, ia akan mempersiapkan jalan-Mu di hadapan-Mu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 12, '11 Aku berkata kepadamu: Sesungguhnya di antara mereka yang dilahirkan oleh perempuan tidak pernah tampil seorang yang lebih besar dari pada Yohanes Pembaptis, namun yang terkecil dalam Kerajaan Sorga lebih besar dari padanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 13, '12 Sejak tampilnya Yohanes Pembaptis hingga sekarang, Kerajaan Sorga diserong dan orang yang menyerongnya mencoba menguasainya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 14, '13 Sebab semua nabi dan kitab Taurat bernubuat hingga tampilnya Yohanes');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 15, '14 dan--jika kamu mau menerimanya--ialah Elia yang akan datang itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 16, '15 Siapa bertelinga, hendaklah ia mendengar!');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 35, '<i>29 Seluruh orang banyak yang mendengar perkataan-Nya, termasuk para pemungut cukai, mengakui kebenaran Allah, karena mereka telah memberi diri dibaptis oleh Yohanes.</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 36, '<i>30 Tetapi orang-orang Farisi dan ahli-ahli Taurat menolak maksud Allah terhadap diri mereka, karena mereka tidak mau dibaptis oleh Yohanes.</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 17, '16 <i>Kata Yesus:</i> Dengan apakah akan Kuumpamakan angkatan ini? Mereka itu seumpama anak-anak yang duduk di pasar dan berseru kepada teman-temannya:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 18, '17 Kami meniup seruling bagimu, tetapi kamu tidak menari, kami menyanyikan kidung duka, tetapi kamu tidak berkabung <i>(tidak menangis)</i>.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 19, '18 Karena Yohanes <i>Pembaptis</i> datang, ia tidak makan <i>roti</i>, dan tidak minum <i>anggur</i>, dan mereka berkata: Ia kerasukan setan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 20, '19 Kemudian Anak Manusia datang, Ia makan dan minum, dan mereka berkata: Lihatlah, Ia seorang pelahap dan peminum, sahabat pemungut cukai dan orang berdosa. Tetapi hikmat Allah dibenarkan oleh perbuatannya <i>(semua orang yang menerimanya)</i>."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 20, '58. Yesus Mengecam Beberapa Kota');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 20, '(Matius 11:20-30)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 3, '20 Lalu Yesus mulai mengecam kota-kota yang tidak bertobat, sekalipun di situ Ia paling banyak melakukan mujizat-mujizat-Nya:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 4, '21 "Celakalah engkau Khorazim! Celakalah engkau Betsaida! Karena jika di Tirus dan di Sidon terjadi mujizat-mujizat yang telah terjadi di tengah-tengah kamu, sudah lama mereka bertobat dan berkabung.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 5, '22 Tetapi Aku berkata kepadamu: Pada hari penghakiman, tanggungan Tirus dan Sidon akan lebih ringan dari pada tanggunganmu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 6, '23 Dan engkau Kapernaum, apakah engkau akan dinaikkan sampai ke langit? Tidak, engkau akan diturunkan sampai ke dunia orang mati! Karena jika di Sodom terjadi mujizat-mujizat yang telah terjadi di tengah-tengah kamu, kota itu tentu masih berdiri sampai hari ini.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 7, '24 Tetapi Aku berkata kepadamu: Pada hari penghakiman, tanggungan negeri Sodom akan lebih ringan dari pada tanggunganmu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 8, '25 Pada waktu itu berkatalah Yesus: "Aku bersyukur kepada-Mu, Bapa, Tuhan langit dan bumi, karena semuanya itu Engkau sembunyikan bagi orang bijak dan orang pandai, tetapi Engkau nyatakan kepada orang kecil.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 9, '26 Ya Bapa, itulah yang berkenan kepada-Mu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 10, '27 Semua telah diserahkan kepada-Ku oleh Bapa-Ku dan tidak seorangpun mengenal Anak selain Bapa, dan tidak seorangpun mengenal Bapa selain Anak dan orang yang kepadanya Anak itu berkenan menyatakannya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 11, '28 Marilah kepada-Ku, semua yang letih lesu dan berbeban berat, Aku akan memberi kelegaan kepadamu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 12, '29 Pikullah kuk yang Kupasang dan belajarlah pada-Ku, karena Aku lemah lembut dan rendah hati dan jiwamu akan mendapat ketenangan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 13, '30 Sebab kuk yang Kupasang itu enak dan beban-Kupun ringan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 20, '59. Yesus di Rumah Simon si Kusta');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 20, '(Lukas 7:36-50)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 3, '36 Seorang Farisi mengundang Yesus untuk datang makan di rumahnya. Yesus datang ke rumah orang Farisi itu, lalu duduk makan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 4, '37 Di kota itu ada seorang perempuan yang terkenal sebagai seorang berdosa. Ketika perempuan itu mendengar, bahwa Yesus sedang makan di rumah orang Farisi itu, datanglah ia membawa sebuah buli-buli pualam berisi minyak wangi.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 5, '38 Sambil menangis ia pergi berdiri di belakang Yesus dekat kaki-Nya, lalu membasahi kaki-Nya itu dengan air matanya dan menyekanya dengan rambutnya, kemudian ia mencium kaki-Nya dan meminyakinya dengan minyak wangi itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 6, '39 Ketika orang Farisi yang mengundang Yesus melihat hal itu, ia berkata dalam hatinya: "Jika Ia ini nabi, tentu Ia tahu, siapakah dan orang apakah perempuan yang menjamah-Nya ini; tentu Ia tahu, bahwa perempuan itu adalah seorang berdosa."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 7, '40 Lalu Yesus berkata kepadanya: "Simon, ada yang hendak Kukatakan kepadamu." Sahut Simon: "Katakanlah, Guru."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 8, '41 "Ada dua orang yang berhutang kepada seorang pelepas uang. Yang seorang berhutang lima ratus dinar, yang lain lima puluh.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 9, '42 Karena mereka tidak sanggup membayar, maka ia menghapuskan hutang kedua orang itu. Siapakah di antara mereka yang akan terlebih mengasihi dia?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 10, '43 Jawab Simon: "Aku kira dia yang paling banyak dihapuskan hutangnya." Kata Yesus kepadanya: "Betul pendapatmu itu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 11, '44 Dan sambil berpaling kepada perempuan itu, Ia berkata kepada Simon: "Engkau lihat perempuan ini? Aku masuk ke rumahmu, namun engkau tidak memberikan Aku air untuk membasuh kaki-Ku, tetapi dia membasahi kaki-Ku dengan air mata dan menyekanya dengan rambutnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 12, '45 Engkau tidak mencium Aku, tetapi sejak Aku masuk ia tiada henti-hentinya mencium kaki-Ku.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 13, '46 Engkau tidak meminyaki kepala-Ku dengan minyak, tetapi dia meminyaki kaki-Ku dengan minyak wangi.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 14, '47 Sebab itu Aku berkata kepadamu: Dosanya yang banyak itu telah diampuni, sebab ia telah banyak berbuat kasih. Tetapi orang yang sedikit diampuni, sedikit juga ia berbuat kasih."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 15, '48 Lalu Ia berkata kepada perempuan itu: "Dosamu telah diampuni."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 16, '49 Dan mereka, yang duduk makan bersama Dia, berpikir dalam hati mereka: "Siapakah Ia ini, sehingga Ia dapat mengampuni dosa?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 17, '50 Tetapi Yesus berkata kepada perempuan itu: "Imanmu telah menyelamatkan engkau, pergilah dengan selamat!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 17, '60. Yesus Mengajar di Galilea untuk Kedua Kalinya');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 20, '(Lukas 8:1-3)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 3, '1 Tidak lama sesudah itu Yesus berjalan berkeliling dari kota ke kota dan dari desa ke desa memberitakan Injil Kerajaan Allah. Kedua belas murid-Nya bersama-sama dengan Dia,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 4, '2 dan juga beberapa orang perempuan yang telah disembuhkan dari roh-roh jahat atau berbagai penyakit, yaitu Maria yang disebut Magdalena, yang telah dibebaskan dari tujuh roh jahat,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(30, 5, '3 Yohana isteri Khuza bendahara Herodes, Susana dan banyak perempuan lain. Perempuan-perempuan ini melayani rombongan itu dengan kekayaan mereka.');