INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 1, '61. Pengajaran tentang Dosa yang Tidak Terampuni');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 1, '(Matius 12:22-37, <i>Markus 3:20-30</i>)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 22, '<i>20 Kemudian Yesus masuk ke sebuah rumah. Maka datanglah orang banyak berkerumun pula, sehingga makanpun mereka tidak dapat.</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 23, '<i>21 Waktu kaum keluarga-Nya mendengar hal itu, mereka datang hendak mengambil Dia, sebab kata mereka Ia tidak waras lagi.</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 3, '22 Kemudian dibawalah kepada Yesus seorang yang kerasukan setan. Orang itu buta dan bisu, lalu Yesus menyembuhkannya, sehingga si bisu itu berkata-kata dan melihat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 4, '23 Maka takjublah sekalian orang banyak itu, katanya: "Ia ini agaknya Anak Daud."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 5, '24 Tetapi ketika orang Farisi <i>dan ahli-ahli Taurat yang datang dari Yerusalem</i> mendengarnya, mereka berkata: "Dengan Beelzebul, penghulu setan, Ia mengusir setan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 6, '25 Tetapi Yesus mengetahui pikiran mereka lalu <i>memanggil</i> [dan] berkata kepada mereka <i>dalam perumpamaan: "Bagaimana Iblis dapat dapat mengusir Iblis?</i> Setiap kerajaan yang terpecah-pecah pasti binasa dan setiap kota atau rumah tangga yang terpecah-pecah tidak dapat bertahan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 28, '<i>26 Demikianlah juga kalau Iblis berontak melawan dirinya sendiri dan kalau ia terbagi-bagi, ia tidak dapat bertahan, melainkan sudahlah tiba kesudahannya.</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 8, '27 Jadi jika Aku mengusir setan dengan kuasa Beelzebul, dengan kuasa siapakah pengikut-pengikutmu mengusirnya? Sebab itu merekalah yang akan menjadi hakimmu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 9, '28 Tetapi jika Aku mengusir setan dengan kuasa Roh Allah, maka sesungguhnya Kerajaan Allah sudah datang kepadamu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 10, '29 Atau bagaimanakah orang dapat memasuki rumah seorang yang kuat dan merampas harta bendanya apabila tidak diikatnya dahulu orang kuat itu? Sesudah diikatnya barulah dapat ia merampok rumah itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 11, '30 Siapa tidak bersama Aku, ia melawan Aku dan siapa tidak mengumpulkan bersama Aku, ia mencerai-beraikan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 12, '31 Sebab itu Aku berkata kepadamu: Segala dosa dan hujat <i>anak-anak</i> manusia <i>(semua hujat yang mereka ucapkan)</i> akan diampuni, tetapi hujat terhadap Roh Kudus tidak akan diampuni.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 13, '32 Apabila seorang mengucapkan sesuatu menentang Anak Manusia, ia akan diampuni, tetapi jika ia menentang Roh Kudus, ia tidak akan diampuni, di dunia ini tidak, dan di dunia yang akan datangpun tidak.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 13, '<i>30 Melainkan bersalah karena berbuat dosa kekal. Ia berkata demikian karena mereka katakan bahwa Ia kerasukan roh jahat.</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 14, '33 Jikalau suatu pohon kamu katakan baik, maka baik pula buahnya; jikalau suatu pohon kamu katakan tidak baik, maka tidak baik pula buahnya. Sebab dari buahnya pohon itu dikenal.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 15, '34 Hai kamu keturunan ular beludak, bagaimanakah kamu dapat mengucapkan hal-hal yang baik, sedangkan kamu sendiri jahat? Karena yang diucapkan mulut meluap dari hati.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 16, '35 Orang yang baik mengeluarkan hal-hal yang baik dari perbendaharaannya yang baik dan orang yang jahat mengeluarkan hal-hal yang jahat dari perbendaharaannya yang jahat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 17, '36 Tetapi Aku berkata kepadamu: Setiap kata sia-sia yang diucapkan orang harus dipertanggungjawabkannya pada hari penghakiman.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 18, '37 Karena menurut ucapanmu engkau akan dibenarkan, dan menurut ucapanmu pula engkau akan dihukum."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 18, '62. Pengajaran Mengenai Tanda Yunus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 18, '(Matius 12:38-42)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 1, 'Matius 12');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 2, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 3, '38 Pada waktu itu berkatalah beberapa ahli Taurat dan orang Farisi kepada Yesus: "Guru, kami ingin melihat suatu tanda dari pada-Mu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 4, '39 Tetapi jawab-Nya kepada mereka: "Angkatan yang jahat dan tidak setia ini menuntut suatu tanda. Tetapi kepada mereka tidak akan diberikan tanda selain tanda nabi Yunus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 5, '40 Sebab seperti Yunus tinggal di dalam perut ikan tiga hari tiga malam, demikian juga Anak Manusia akan tinggal di dalam rahim bumi tiga hari tiga malam.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 6, '41 Pada waktu penghakiman, orang-orang Niniwe akan bangkit bersama angkatan ini dan menghukumnya juga. Sebab orang-orang Niniwe itu bertobat setelah mendengar pemberitaan Yunus, dan sesungguhnya yang ada di sini lebih dari pada Yunus!');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 7, '42 Pada waktu penghakiman, ratu dari Selatan itu akan bangkit bersama angkatan ini dan ia akan menghukumnya juga. Sebab ratu ini datang dari ujung bumi untuk mendengar hikmat Salomo, dan sesungguhnya yang ada di sini lebih dari pada Salomo!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 7, '63. Pengajaran Mengenai Hubungan Rohani');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 7, 'Matius 12:46-50, <i>Markus 3:31-35</i>, <b>Lukas 8:19-21</b>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 3, '46 Ketika Yesus masih berbicara dengan orang banyak itu, <i>datanglah</i> ibu-Nya dan saudara-saudara-Nya berdiri di luar dan berusaha menemui Dia <b>tetapi tidak dapat mencapai Dia karena orang banyak</b>.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 3, '<i>Mereka menyuruh orang memanggil Dia.</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 4, '47 Maka seorang berkata kepada-Nya: "Lihatlah, ibu-Mu dan saudara-saudara-Mu ada di luar dan berusaha menemui Engkau."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 5, '48 Tetapi jawab Yesus kepada orang yang menyampaikan berita itu kepada-Nya: "Siapa ibu-Ku? Dan siapa saudara-saudara-Ku?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 6, '<i>Ia melihat kepada orang-orang yang duduk di sekelilingNya itu</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 6, '49 Lalu kata-Nya, sambil menunjuk ke arah murid-murid-Nya: "Ini ibu-Ku dan saudara-saudara-Ku!');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 6, '<b>"Ibu-Ku dan saudara-saudara-Ku ialah mereka, yang mendengarkan firman Allah dan melakukannya."</b>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(31, 7, '50 Sebab siapapun yang melakukan kehendak Bapa-Ku di sorga, dialah saudara-Ku laki-laki, dialah saudara-Ku perempuan, dialah ibu-Ku."');