INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 1, '64. Perumpamaan tentang Penabur');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 2, '(Matius 13:1-23, <i>Markus 4:1-20</i>, <b>Lukas 8:4-15</b>)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 3, '1 Pada hari itu keluarlah Yesus dari rumah itu dan duduk di tepi danau <i>dan mulai pula mengajar</i>.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 4, '2 Maka datanglah orang banyak berbondong-bondong lalu mengerumuni Dia, sehingga Ia naik ke perahu dan duduk di situ, sedangkan orang banyak <b>berbondong-bondong datang, yaitu orang-orang yang dari kota ke kota menggabungkan diri pada Yesus,</b> semuanya berdiri di pantai <i>(di darat, di tepi danau)</i>.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 5, '3 Dan Ia mengucapkan banyak hal dalam perumpamaan kepada mereka. Kata-Nya: "Adalah seorang penabur keluar untuk menabur <b>benihnya</b>.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 6, '4 Pada waktu ia menabur, sebagian benih itu jatuh di pinggir jalan, lalu <b>diinjak orang dan</b> datanglah burung <b>di udara</b> dan memakannya sampai habis.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 7, '5 Sebagian jatuh di tanah yang berbatu-batu, yang tidak banyak tanahnya, lalu benih itupun segera tumbuh, karena tanahnya tipis.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 8, '6 Tetapi sesudah matahari terbit, layulah ia dan menjadi kering karena tidak berakar <b>dan karena tidak mendapat air</b>.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 9, '7 Sebagian lagi jatuh di tengah semak duri, lalu makin besarlah semak itu dan menghimpitnya sampai mati, <i>sehingga tidak berbuah</i>.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 10, '8 Dan sebagian jatuh di tanah yang baik lalu berbuah: ada yang seratus kali lipat, ada yang enam puluh kali lipat, ada yang tiga puluh kali lipat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 11, '9 <b>Setelah berkata demikian Yesus berseru:</b> Siapa bertelinga, hendaklah ia mendengar!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 12, '10 <i>Ketika Ia sendirian, pengikut-pengikut-Nya dan kedua belas murid itu menanyakan Dia tentang perumpamaan itu:</i> "Mengapa Engkau berkata-kata kepada mereka dalam perumpamaan?" <b>Apa maksud perumpamaan itu?</b>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 13, '11 Jawab Yesus: "Kepadamu diberi karunia untuk mengetahui rahasia Kerajaan Sorga <i>(Allah)</i>, tetapi kepada mereka tidak, <i>(tetapi kepada orang-orang luar segala sesuatu disampaikan dalam perumpamaan.)</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 14, '12 Karena siapa yang mempunyai, kepadanya akan diberi, sehingga ia berkelimpahan; tetapi siapa yang tidak mempunyai, apapun juga yang ada padanya akan diambil dari padanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 15, '13 Itulah sebabnya Aku berkata-kata dalam perumpamaan kepada mereka; karena sekalipun melihat, mereka tidak melihat dan sekalipun mendengar, mereka tidak mendengar dan tidak mengerti.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 16, '14 Maka pada mereka genaplah nubuat Yesaya, yang berbunyi: Kamu akan mendengar dan mendengar, namun tidak mengerti, kamu akan melihat dan melihat, namun tidak menanggap.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 17, '15 Sebab hati bangsa ini telah menebal, dan telinganya berat mendengar, dan matanya melekat tertutup; supaya jangan mereka melihat dengan matanya dan mendengar dengan telinganya dan mengerti dengan hatinya, lalu berbalik sehingga Aku menyembuhkan mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 18, '16 Tetapi berbahagialah matamu karena melihat dan telingamu karena mendengar.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 19, '17 Sebab Aku berkata kepadamu: Sesungguhnya banyak nabi dan orang benar ingin melihat apa yang kamu lihat, tetapi tidak melihatnya, dan ingin mendengar apa yang kamu dengar, tetapi tidak mendengarnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 20, '<i>13 Lalu Ia berkata kepada mereka: "Tidakkah kamu mengerti perumpamaan ini? Kalau demikian bagaimana kamu dapat memahami semua perumpamaan yang lain?</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 21, '18 Karena itu, dengarlah arti perumpamaan penabur itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 22, '<b>Inilah arti perumpamaan itu:</b>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 23, '14 <i>Penabur itu menaburkan firman.</i> <b>(Benih itu ialah firman Allah)</b>.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 24, '19 Kepada setiap orang yang mendengar firman tentang Kerajaan Sorga, tetapi tidak mengertinya, datanglah si jahat <i>(iblis)</i> dan merampas yang ditaburkan dalam hati orang itu; <b>supaya mereka jangan percaya dan diselamatkan</b>, itulah benih yang ditaburkan di pinggir jalan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 25, '20 Benih yang ditaburkan di tanah yang berbatu-batu ialah orang yang mendengar firman itu dan segera menerimanya dengan gembira.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 26, '21 Tetapi ia tidak berakar dan tahan sebentar saja, <b>mereka percaya sebentar saja</b>. Apabila datang penindasan atau penganiayaan <b>(masa pencobaan)</b> karena firman itu, orang itupun segera murtad.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 27, '22 Yang ditaburkan di tengah semak duri ialah orang yang mendengar firman itu <b>dan dalam pertumbuhan selanjutnya</b>, lalu kekuatiran dunia ini dan tipu daya kekayaan, <b>dan kenikmatan hidup</b> menghimpit firman itu sehingga tidak berbuah <b>(sehingga tidak menghasilkan buah yang matang.)</b>.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 28, '23 Yang ditaburkan di tanah yang baik ialah orang yang mendengar firman itu dan mengerti, <b>menyimpannya dalam hati yang baik</b>, dan karena itu ia berbuah <b>dalam ketekunan</b>, ada yang seratus kali lipat, ada yang enam puluh kali lipat, ada yang tiga puluh kali lipat."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 29, '65. Perumpamaan tentang Pelita');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 30, '(Markus 4:21-25, <i>Lukas 8:16-18</i>)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 31, '21 Lalu Yesus berkata kepada mereka: "Orang membawa pelita bukan supaya ditempatkan di bawah gantang atau di bawah tempat tidur, melainkan supaya ditaruh di atas kaki dian.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 32, '<i>17 Sebab tidak ada sesuatu yang tersembunyi yang tidak akan dinyatakan, dan tidak ada sesuatu yang rahasia yang tidak akan diketahui dan diumumkan.</i>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 33, '22 Sebab tidak ada sesuatu yang tersembunyi yang tidak akan dinyatakan, dan tidak ada sesuatu yang rahasia yang tidak akan tersingkap.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 34, '23 Barangsiapa mempunyai telinga untuk mendengar, hendaklah ia mendengar!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 35, '24 Lalu Ia berkata lagi: "Camkanlah apa yang kamu dengar <i>(perhatikanlah cara kamu mendengar)</i>! Ukuran yang kamu pakai untuk mengukur akan diukurkan kepadamu, dan di samping itu akan ditambah lagi kepadamu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 36, '25 Karena siapa yang mempunyai, kepadanya akan diberi, tetapi siapa yang tidak mempunyai, apapun juga yang ada padanya akan diambil dari padanya <i>(juga apa yang ia anggap ada padanya)</i>."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 37, '66. Perumpamaan tentang Lalang');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 38, '(Matius 13:24-30)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 39, '24 Yesus membentangkan suatu perumpamaan lain lagi kepada mereka, kata-Nya: "Hal Kerajaan Sorga itu seumpama orang yang menaburkan benih yang baik di ladangnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 40, '25 Tetapi pada waktu semua orang tidur, datanglah musuhnya menaburkan benih lalang di antara gandum itu, lalu pergi.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 41, '26 Ketika gandum itu tumbuh dan mulai berbulir, nampak jugalah lalang itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 42, '27 Maka datanglah hamba-hamba tuan ladang itu kepadanya dan berkata: Tuan, bukankah benih baik, yang tuan taburkan di ladang tuan? Dari manakah lalang itu?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 43, '28 Jawab tuan itu: Seorang musuh yang melakukannya. Lalu berkatalah hamba-hamba itu kepadanya: Jadi maukah tuan supaya kami pergi mencabut lalang itu?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 44, '29 Tetapi ia berkata: Jangan, sebab mungkin gandum itu ikut tercabut pada waktu kamu mencabut lalang itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 45, '30 Biarkanlah keduanya tumbuh bersama sampai waktu menuai. Pada waktu itu aku akan berkata kepada para penuai: Kumpulkanlah dahulu lalang itu dan ikatlah berberkas-berkas untuk dibakar; kemudian kumpulkanlah gandum itu ke dalam lumbungku."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 46, '67. Perumpamaan tentang Panen');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 47, '(Markus 4:26-29)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 48, '26 Lalu kata Yesus: "Beginilah hal Kerajaan Allah itu: seumpama orang yang menaburkan benih di tanah,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 49, '27 lalu pada malam hari ia tidur dan pada siang hari ia bangun, dan benih itu mengeluarkan tunas dan tunas itu makin tinggi, bagaimana terjadinya tidak diketahui orang itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 50, '28 Bumi dengan sendirinya mengeluarkan buah, mula-mula tangkainya, lalu bulirnya, kemudian butir-butir yang penuh isinya dalam bulir itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 51, '29 Apabila buah itu sudah cukup masak, orang itu segera menyabit, sebab musim menuai sudah tiba."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 52, '68. Perumpamaan tentang Biji Sawi');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 53, '(Matius 13:31-32, <i>Markus 4:30-32</i>)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 54, '31 Yesus membentangkan suatu perumpamaan lain lagi kepada mereka, kata-Nya: <i>"Dengan apa hendak kita membandingkan Kerajaan Allah itu, atau dengan perumpamaan manakah hendaknya kita menggambarkannya?</i> "Hal Kerajaan Sorga itu seumpama biji sesawi, yang diambil dan ditaburkan orang di ladangnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 55, '32 Memang biji itu yang paling kecil dari segala jenis benih <i>yang ada di bumi</i>, tetapi apabila <i>ia ditaburkan dan</i> sudah tumbuh, sesawi itu lebih besar dari pada sayuran yang lain, bahkan menjadi pohon <i>dan mengeluarkan cabang-cabang yang besar</i>, sehingga burung-burung di udara datang bersarang [dan] <i>bernaung</i> pada cabang-cabangnya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 56, '69. Perumpamaan tentang Ragi');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 57, '(Matius 13:33-43, <i>Markus 4:33-34</i>)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 58, '33 Dan Ia menceriterakan perumpamaan ini juga kepada mereka: "Hal Kerajaan Sorga itu seumpama ragi yang diambil seorang perempuan dan diadukkan ke dalam tepung terigu tiga sukat sampai khamir seluruhnya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 59, '34 Semuanya itu disampaikan Yesus kepada orang banyak dalam perumpamaan, <i>dalam banyak perumpamaan yang semacam itu Ia memberitakan firman kepada mereka sesuai dengan pengertian mereka</i>, dan tanpa perumpamaan suatupun tidak disampaikan-Nya kepada mereka, <i>tetapi kepada murid-murid-Nya Ia menguraikan segala sesuatu secara tersendiri</i>,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 60, '35 supaya genaplah firman yang disampaikan oleh nabi: "Aku mau membuka mulut-Ku mengatakan perumpamaan, Aku mau mengucapkan hal yang tersembunyi sejak dunia dijadikan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 61, '36 Maka Yesuspun meninggalkan orang banyak itu, lalu pulang. Murid-murid-Nya datang dan berkata kepada-Nya: "Jelaskanlah kepada kami perumpamaan tentang lalang di ladang itu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 62, '37 Ia menjawab, kata-Nya: "Orang yang menaburkan benih baik ialah Anak Manusia;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 63, '38 ladang ialah dunia. Benih yang baik itu anak-anak Kerajaan dan lalang anak-anak si jahat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 64, '39 Musuh yang menaburkan benih lalang ialah Iblis. Waktu menuai ialah akhir zaman dan para penuai itu malaikat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 65, '40 Maka seperti lalang itu dikumpulkan dan dibakar dalam api, demikian juga pada akhir zaman.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 66, '41 Anak Manusia akan menyuruh malaikat-malaikat-Nya dan mereka akan mengumpulkan segala sesuatu yang menyesatkan dan semua orang yang melakukan kejahatan dari dalam Kerajaan-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 67, '42 Semuanya akan dicampakkan ke dalam dapur api; di sanalah akan terdapat ratapan dan kertakan gigi.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 68, '43 Pada waktu itulah orang-orang benar akan bercahaya seperti matahari dalam Kerajaan Bapa mereka. Siapa bertelinga, hendaklah ia mendengar!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 69, '70. Perumpamaan tentang Harta Terpendam');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 70, '(Matius 13:44)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 71, '44 "Hal Kerajaan Sorga itu seumpama harta yang terpendam di ladang, yang ditemukan orang, lalu dipendamkannya lagi. Oleh sebab sukacitanya pergilah ia menjual seluruh miliknya lalu membeli ladang itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 72, '71. Perumpamaan tentang Mutiara yang Berharga');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 73, '(Matius 13:45-46)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 74, '45 Demikian pula hal Kerajaan Sorga itu seumpama seorang pedagang yang mencari mutiara yang indah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 75, '46 Setelah ditemukannya mutiara yang sangat berharga, iapun pergi menjual seluruh miliknya lalu membeli mutiara itu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 76, '72. Perumpamaan tentang Pukat');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 77, '(Matius 13:47-50)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 78, '47 "Demikian pula hal Kerajaan Sorga itu seumpama pukat yang dilabuhkan di laut, lalu mengumpulkan berbagai-bagai jenis ikan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 79, '48 Setelah penuh, pukat itupun diseret orang ke pantai, lalu duduklah mereka dan mengumpulkan ikan yang baik ke dalam pasu dan ikan yang tidak baik mereka buang.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 80, '49 Demikianlah juga pada akhir zaman: Malaikat-malaikat akan datang memisahkan orang jahat dari orang benar,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 81, '50 lalu mencampakkan orang jahat ke dalam dapur api; di sanalah akan terdapat ratapan dan kertakan gigi.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 82, '73. Memahami Perumpamaan');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 83, '(Matius 13:51-53)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 84, '51 Mengertikah kamu semuanya itu?" Mereka menjawab: "Ya, kami mengerti."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 85, '52 Maka berkatalah Yesus kepada mereka: "Karena itu setiap ahli Taurat yang menerima pelajaran dari hal Kerajaan Sorga itu seumpama tuan rumah yang mengeluarkan harta yang baru dan yang lama dari perbendaharaannya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(32, 86, '53 Setelah Yesus selesai menceriterakan perumpamaan-perumpamaan itu, Iapun pergi dari situ.');
