INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 1, 'I. Silsilah Yesus Kristus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 2, '3. Silsilah Tercantum dalam Injil Matius');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 3, 'Matius 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 5, '1 Inilah silsilah Yesus Kristus, anak Daud, anak Abraham. ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 6, '2 Abraham memperanakkan Ishak, Ishak memperanakkan Yakub, Yakub memperanakkan Yehuda dan saudara-saudaranya, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 7, '3 Yehuda memperanakkan Peres dan Zerah dari Tamar, Peres memperanakkan Hezron, Hezron memperanakkan Ram, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 8, '4 Ram memperanakkan Aminadab, Aminadab memperanakkan Nahason, Nahason memperanakkan Salmon, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 9, '5 Salmon memperanakkan Boas dari Rahab, Boas memperanakkan Obed dari Rut, Obed memperanakkan Isai, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 10, '6 Isai memperanakkan raja Daud. Daud memperanakkan Salomo dari isteri Uria, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 11, '7 Salomo memperanakkan Rehabeam, Rehabeam memperanakkan Abia, Abia memperanakkan Asa, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 12, '8 Asa memperanakkan Yosafat, Yosafat memperanakkan Yoram, Yoram memperanakkan Uzia, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 13, '9 Uzia memperanakkan Yotam, Yotam memperanakkan Ahas, Ahas memperanakkan Hizkia, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 14, '10 Hizkia memperanakkan Manasye, Manasye memperanakkan Amon, Amon memperanakkan Yosia, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 15, '11 Yosia memperanakkan Yekhonya dan saudara-saudaranya pada waktu pembuangan ke Babel. ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 16, '12 Sesudah pembuangan ke Babel, Yekhonya memperanakkan Sealtiel, Sealtiel memperanakkan Zerubabel, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 17, '13 Zerubabel memperanakkan Abihud, Abihud memperanakkan Elyakim, Elyakim memperanakkan Azor, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 18, '14 Azor memperanakkan Zadok, Zadok memperanakkan Akhim, Akhim memperanakkan Eliud, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 19, '15 Eliud memperanakkan Eleazar, Eleazar memperanakkan Matan, Matan memperanakkan Yakub, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 20, '16 Yakub memperanakkan Yusuf suami Maria, yang melahirkan Yesus yang disebut Kristus. ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 21, '17 Jadi seluruhnya ada: empat belas keturunan dari Abraham sampai Daud, empat belas keturunan dari Daud sampai pembuangan ke Babel, dan empat belas keturunan dari pembuangan ke Babel sampai Kristus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 22, '4. Silsilah Tercantum dalam Injil Lukas');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 23, 'Lukas 3');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 24, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 25, '23 Ketika Yesus memulai pekerjaan-Nya, Ia berumur kira-kira tiga puluh tahun dan menurut anggapan orang, Ia adalah anak Yusuf, anak Eli, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 26, '24 anak Matat, anak Lewi, anak Malkhi, anak Yanai, anak Yusuf, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 27, '25 anak Matica, anak Amos, anak Nahum, anak Hesli, anak Nagai, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 28, '26 anak Maat, anak Matica, anak Simei, anak Yosekh, anak Yoda, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 29, '27 anak Yohanan, anak Resa, anak Zerubabel, anak Sealtiel, anak Neri, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 30, '28 anak Malkhi, anak Adi, anak Kosam, anak Elmadam, anak Er, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 31, '29 anak Yesua, anak Eliezer, anak Yorim, anak Matat, anak Lewi, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 32, '30 anak Simeon, anak Yehuda, anak Yusuf, anak Yonam, anak Elyakim, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 33, '31 anak Melea, anak Mina, anak Matata, anak Natan, anak Daud, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 34, '32 anak Isai, anak Obed, anak Boas, anak Salmon, anak Nahason, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 35, '33 anak Aminadab, anak Admin, anak Arni, anak Hezron, anak Peres, anak Yehuda, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 36, '34 anak Yakub, anak Ishak, anak Abraham, anak Terah, anak Nahor, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 37, '35 anak Serug, anak Rehu, anak Peleg, anak Eber, anak Salmon, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 38, '36 anak Kenan, anak Arpakhsad, anak Sem, anak Nuh, anak Lamekh, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 39, '37 anak Metusalah, anak Henokh, anak Yared, anak Mahalaleel, anak Kenan, ');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(4, 40, '38 anak Enos, anak Set, anak Adam, anak Allah.');
