INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 1, '138. Perumpamaan tentang Menara');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 2, '(Lukas 14:28-30)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 3, '28 Sebab siapakah di antara kamu yang kalau mau mendirikan sebuah menara tidak duduk dahulu membuat anggaran biayanya, kalau-kalau cukup uangnya untuk menyelesaikan pekerjaan itu?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 4, '29 Supaya jikalau ia sudah meletakkan dasarnya dan tidak dapat menyelesaikannya, jangan-jangan semua orang yang melihatnya, mengejek dia,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 5, '30 sambil berkata: Orang itu mulai mendirikan, tetapi ia tidak sanggup menyelesaikannya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 6, '139. Perumpaan tentang Raja yang Mau Maju Berperang');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 7, '(Lukas 14:31-33)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 8, '31 Atau, raja manakah yang kalau mau pergi berperang melawan raja lain tidak duduk dahulu untuk mempertimbangkan, apakah dengan sepuluh ribu orang ia sanggup menghadapi lawan yang mendatanginya dengan dua puluh ribu orang?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 9, '32 Jikalau tidak, ia akan mengirim utusan selama musuh itu masih jauh untuk menanyakan syarat-syarat perdamaian.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 10, '33 Demikian pulalah tiap-tiap orang di antara kamu, yang tidak melepaskan dirinya dari segala miliknya, tidak dapat menjadi murid-Ku.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 11, '140. Perumpamaan tentang Garam yang Tawar');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 12, '(Lukas 14:34-35)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 13, '34 Garam memang baik, tetapi jika garam juga menjadi tawar, dengan apakah ia diasinkan?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 14, '35 Tidak ada lagi gunanya baik untuk ladang maupun untuk pupuk, dan orang membuangnya saja. Siapa mempunyai telinga untuk mendengar, hendaklah ia mendengar!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 15, '<b>XI.a.3. Perumpamaan tentang Sesuatu yang Hilang</b>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 16, '141. Perumpamaan tentang Domba yang Hilang');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 17, '(Lukas 15:1-7)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 18, '1 Para pemungut cukai dan orang-orang berdosa biasanya datang kepada Yesus untuk mendengarkan Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 19, '2 Maka bersungut-sungutlah orang-orang Farisi dan ahli-ahli Taurat, katanya: "Ia menerima orang-orang berdosa dan makan bersama-sama dengan mereka."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 20, '3 Lalu Ia mengatakan perumpamaan ini kepada mereka:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 21, '4 "Siapakah di antara kamu yang mempunyai seratus ekor domba, dan jikalau ia kehilangan seekor di antaranya, tidak meninggalkan yang sembilan puluh sembilan ekor di padang gurun dan pergi mencari yang sesat itu sampai ia menemukannya?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 22, '5 Dan kalau ia telah menemukannya, ia meletakkannya di atas bahunya dengan gembira,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 23, '6 dan setibanya di rumah ia memanggil sahabat-sahabat dan tetangga-tetanggan serta berkata kepada mereka: Bersukacitalah bersama-sama dengan aku, sebab dombaku yang hilang itu telah kutemukan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 24, '7 Aku berkata kepadamu: Demikian juga akan ada sukacita di sorga karena satu orang berdosa yang bertobat, lebih dari pada sukacita karena sembilan puluh sembilan orang benar yang tidak memerlukan pertobatan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 25, '142. Perumpamaan tentang Uang yang Hilang');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 26, '(Lukas 15:8-10)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 27, '8 "Atau perempuan manakah yang mempunyai sepuluh dirham, dan jika ia kehilangan satu di antaranya, tidak menyalakan pelita dan menyapu rumah serta mencarinya dengan cermat sampai ia menemukannya?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 28, '9 Dan kalau ia telah menemukannya, ia memanggil sahabat-sahabat dan tetangga-tetangganya serta berkata: Bersukacitalah bersama-sama dengan aku, sebab dirhamku yang hilang itu telah kutemukan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 29, '10 Aku berkata kepadamu: Demikian juga akan ada sukacita pada malaikat-malaikat Allah karena satu orang berdosa yang bertobat."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 30, '143. Perumpamaan tentang Anak yang Hilang');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 31, '(Lukas 15:11-32)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 32, '11 Yesus berkata lagi: "Ada seorang mempunyai dua anak laki-laki.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 33, '12 Kata yang bungsu kepada ayahnya: Bapa, berikanlah kepadaku bagian harta milik kita yang menjadi hakku. Lalu ayahnya membagi-bagikan harta kekayaan itu di antara mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 34, '13 Beberapa hari kemudian anak bungsu itu menjual seluruh bagiannya itu lalu pergi ke negeri yang jauh. Di sana ia memboroskan harta miliknya itu dengan hidup berfoya-foya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 35, '14 Setelah dihabiskannya semuanya, timbullah bencana kelaparan di dalam negeri itu dan iapun mulai melarat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 36, '15 Lalu ia pergi dan bekerja pada seorang majikan di negeri itu. Orang itu menyuruhnya ke ladang untuk menjaga babinya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 37, '16 Lalu ia ingin mengisi perutnya dengan ampas yang menjadi makanan babi itu, tetapi tidak seorangpun yang memberikannya kepadanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 38, '17 Lalu ia menyadari keadaannya, katanya: Betapa banyaknya orang upahan bapaku yang berlimpah-limpah makanannya, tetapi aku di sini mati kelaparan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 39, '18 Aku akan bangkit dan pergi kepada bapaku dan berkata kepadanya: Bapa, aku telah berdosa terhadap sorga dan terhadap bapa,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 40, '19 aku tidak layak lagi disebutkan anak bapa; jadikanlah aku sebagai salah seorang upahan bapa.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 41, '20 Maka bangkitlah ia dan pergi kepada bapanya. Ketika ia masih jauh, ayahnya telah melihatnya, lalu tergeraklah hatinya oleh belas kasihan. Ayahnya itu berlari mendapatkan dia lalu merangkul dan mencium dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 42, '21 Kata anak itu kepadanya: Bapa, aku telah berdosa terhadap sorga dan terhadap bapa, aku tidak layak lagi disebutkan anak bapa.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 43, '22 Tetapi ayah itu berkata kepada hamba-hambanya: Lekaslah bawa ke mari jubah yang terbaik, pakaikanlah itu kepadanya dan kenakanlah cincin pada jarinya dan sepatu pada kakinya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 44, '23 Dan ambillah anak lembu tambun itu, sembelihlah dia dan marilah kita makan dan bersukacita.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 45, '24 Sebab anakku ini telah mati dan menjadi hidup kembali, ia telah hilang dan didapat kembali. Maka mulailah mereka bersukaria.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 46, '25 Tetapi anaknya yang sulung berada di ladang dan ketika ia pulang dan dekat ke rumah, ia mendengar bunyi seruling dan nyanyian tari-tarian.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 47, '26 Lalu ia memanggil salah seorang hamba dan bertanya kepadanya apa arti semuanya itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 48, '27 Jawab hamba itu: Adikmu telah kembali dan ayahmu telah menyembelih anak lembu tambun, karena ia mendapatnya kembali dengan sehat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 49, '28 Maka marahlah anak sulung itu dan ia tidak mau masuk. Lalu ayahnya keluar dan berbicara dengan dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 50, '29 Tetapi ia menjawab ayahnya, katanya: Telah bertahun-tahun aku melayani bapa dan belum pernah aku melanggar perintah bapa, tetapi kepadaku belum pernah bapa memberikan seekor anak kambing untuk bersukacita dengan sahabat-sahabatku.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 51, '30 Tetapi baru saja datang anak bapa yang telah memboroskan harta kekayaan bapa bersama-sama dengan pelacur-pelacur, maka bapa menyembelih anak lembu tambun itu untuk dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 52, '31 Kata ayahnya kepadanya: Anakku, engkau selalu bersama-sama dengan aku, dan segala kepunyaanku adalah kepunyaanmu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 53, '32 Kita patut bersukacita dan bergembira karena adikmu telah mati dan menjadi hidup kembali, ia telah hilang dan didapat kembali."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 54, '144. Perumpamaan tentang Manager yang Kehilangan Pekerjaan');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 55, '(Lukas 16:1-13)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 56, '1 Dan Yesus berkata kepada murid-murid-Nya: "Ada seorang kaya yang mempunyai seorang bendahara. Kepadanya disampaikan tuduhan, bahwa bendahara itu menghamburkan miliknya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 57, '2 Lalu ia memanggil bendahara itu dan berkata kepadanya: Apakah yang kudengar tentang engkau? Berilah pertanggungan jawab atas urusanmu, sebab engkau tidak boleh lagi bekerja sebagai bendahara.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 58, '3 Kata bendahara itu di dalam hatinya: Apakah yang harus aku perbuat? Tuanku memecat aku dari jabatanku sebagai bendahara. Mencangkul aku tidak dapat, mengemis aku malu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 59, '4 Aku tahu apa yang akan aku perbuat, supaya apabila aku dipecat dari jabatanku sebagai bendahara, ada orang yang akan menampung aku di rumah mereka.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 60, '5 Lalu ia memanggil seorang demi seorang yang berhutang kepada tuannya. Katanya kepada yang pertama: Berapakah hutangmu kepada tuanku?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 61, '6 Jawab orang itu: Seratus tempayan minyak. Lalu katanya kepada orang itu: Inilah surat hutangmu, duduklah dan buat surat hutang lain sekarang juga: Lima puluh tempayan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 62, '7 Kemudian ia berkata kepada yang kedua: Dan berapakah hutangmu? Jawab orang itu: Seratus pikul gandum. Katanya kepada orang itu: Inilah surat hutangmu, buatlah surat hutang lain: Delapan puluh pikul.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 63, '8 Lalu tuan itu memuji bendahara yang tidak jujur itu, karena ia telah bertindak dengan cerdik. Sebab anak-anak dunia ini lebih cerdik terhadap sesamanya dari pada anak-anak terang.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 64, '9 Dan Aku berkata kepadamu: Ikatlah persahabatan dengan mempergunakan Mamon yang tidak jujur, supaya jika Mamon itu tidak dapat menolong lagi, kamu diterima di dalam kemah abadi."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 65, '10 "Barangsiapa setia dalam perkara-perkara kecil, ia setia juga dalam perkara-perkara besar. Dan barangsiapa tidak benar dalam perkara-perkara kecil, ia tidak benar juga dalam perkara-perkara besar.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 66, '11 Jadi, jikalau kamu tidak setia dalam hal Mamon yang tidak jujur, siapakah yang akan mempercayakan kepadamu harta yang sesungguhnya?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 67, '12 Dan jikalau kamu tidak setia dalam harta orang lain, siapakah yang akan menyerahkan hartamu sendiri kepadamu?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 68, '13 Seorang hamba tidak dapat mengabdi kepada dua tuan. Karena jika demikian ia akan membenci yang seorang dan mengasihi yang lain, atau ia akan setia kepada yang seorang dan tidak mengindahkan yang lain. Kamu tidak dapat mengabdi kepada Allah dan kepada Mamon."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 69, '145. Peringatan tentang Ketamakan');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 70, '(Lukas 16:14-18)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 71, '14 Semuanya itu didengar oleh orang-orang Farisi, hamba-hamba uang itu, dan mereka mencemoohkan Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 72, '15 Lalu Ia berkata kepada mereka: "Kamu membenarkan diri di hadapan orang, tetapi Allah mengetahui hatimu. Sebab apa yang dikagumi manusia, dibenci oleh Allah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 73, '16 Hukum Taurat dan kitab para nabi berlaku sampai kepada zaman Yohanes; dan sejak waktu itu Kerajaan Allah diberitakan dan setiap orang menggagahinya berebut memasukinya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 74, '17 Lebih mudah langit dan bumi lenyap dari pada satu titik dari hukum Taurat batal.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 75, '18 Setiap orang yang menceraikan isterinya, lalu kawin dengan perempuan lain, ia berbuat zinah; dan barangsiapa kawin dengan perempuan yang diceraikan suaminya, ia berbuat zinah."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 76, '146. Orang Kaya dan Lazarus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 77, '(Lukas 16:19-31)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 78, '19 "Ada seorang kaya yang selalu berpakaian jubah ungu dan kain halus, dan setiap hari ia bersukaria dalam kemewahan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 79, '20 Dan ada seorang pengemis bernama Lazarus, badannya penuh dengan borok, berbaring dekat pintu rumah orang kaya itu,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 80, '21 dan ingin menghilangkan laparnya dengan apa yang jatuh dari meja orang kaya itu. Malahan anjing-anjing datang dan menjilat boroknya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 81, '22 Kemudian matilah orang miskin itu, lalu dibawa oleh malaikat-malaikat ke pangkuan Abraham.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 82, '23 Orang kaya itu juga mati, lalu dikubur. Dan sementara ia menderita sengsara di alam maut ia memandang ke atas, dan dari jauh dilihatnya Abraham, dan Lazarus duduk di pangkuannya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 83, '24 Lalu ia berseru, katanya: Bapa Abraham, kasihanilah aku. Suruhlah Lazarus, supaya ia mencelupkan ujung jarinya ke dalam air dan menyejukkan lidahku, sebab aku sangat kesakitan dalam nyala api ini.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 84, '25 Tetapi Abraham berkata: Anak, ingatlah, bahwa engkau telah menerima segala yang baik sewaktu hidupmu, sedangkan Lazarus segala yang buruk. Sekarang ia mendapat hiburan dan engkau sangat menderita.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 85, '26 Selain dari pada itu di antara kami dan engkau terbentang jurang yang tak terseberangi, supaya mereka yang mau pergi dari sini kepadamu ataupun mereka yang mau datang dari situ kepada kami tidak dapat menyeberang.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 86, '27 Kata orang itu: Kalau demikian, aku minta kepadamu, bapa, supaya engkau menyuruh dia ke rumah ayahku,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 87, '28 sebab masih ada lima orang saudaraku, supaya ia memperingati mereka dengan sungguh-sungguh, agar mereka jangan masuk kelak ke dalam tempat penderitaan ini.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 88, '29 Tetapi kata Abraham: Ada pada mereka kesaksian Musa dan para nabi; baiklah mereka mendengarkan kesaksian itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 89, '30 Jawab orang itu: Tidak, bapa Abraham, tetapi jika ada seorang yang datang dari antara orang mati kepada mereka, mereka akan bertobat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 90, '31 Kata Abraham kepadanya: Jika mereka tidak mendengarkan kesaksian Musa dan para nabi, mereka tidak juga akan mau diyakinkan, sekalipun oleh seorang yang bangkit dari antara orang mati."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 91, '147. Instruksi tentang Pengampunan dan Pelayanan');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 92, '(Lukas 17:1-10)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 93, '1 Yesus berkata kepada murid-murid-Nya: "Tidak mungkin tidak akan ada penyesatan, tetapi celakalah orang yang mengadakannya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 94, '2 Adalah lebih baik baginya jika sebuah batu kilangan diikatkan pada lehernya, lalu ia dilemparkan ke dalam laut, dari pada menyesatkan salah satu dari orang-orang yang lemah ini.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 95, '3 Jagalah dirimu! Jikalau saudaramu berbuat dosa, tegorlah dia, dan jikalau ia menyesal, ampunilah dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 96, '4 Bahkan jikalau ia berbuat dosa terhadap engkau tujuh kali sehari dan tujuh kali ia kembali kepadamu dan berkata: Aku menyesal, engkau harus mengampuni dia."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 97, '5 Lalu kata rasul-rasul itu kepada Tuhan: "Tambahkanlah iman kami!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 98, '6 Jawab Tuhan: "Kalau sekiranya kamu mempunyai iman sebesar biji sesawi saja, kamu dapat berkata kepada pohon ara ini: Terbantunlah engkau dan tertanamlah di dalam laut, dan ia akan taat kepadamu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 99, '7 "Siapa di antara kamu yang mempunyai seorang hamba yang membajak atau menggembalakan ternak baginya, akan berkata kepada hamba itu, setelah ia pulang dari ladang: Mari segera makan!');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 100, '8 Bukankah sebaliknya ia akan berkata kepada hamba itu: Sediakanlah makananku. Ikatlah pinggangmu dan layanilah aku sampai selesai aku makan dan minum. Dan sesudah itu engkau boleh makan dan minum.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 101, '9 Adakah ia berterima kasih kepada hamba itu, karena hamba itu telah melakukan apa yang ditugaskan kepadanya?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(44, 102, '10 Demikian jugalah kamu. Apabila kamu telah melakukan segala sesuatu yang ditugaskan kepadamu, hendaklah kamu berkata: Kami adalah hamba-hamba yang tidak berguna; kami hanya melakukan apa yang kami harus lakukan."');
