INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 1, '148. Membangkitkan Lazarus Orang Betania dari Kematian');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 2, '(Yohanes 11:1-44)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 3, '1 Ada seorang yang sedang sakit, namanya Lazarus. Ia tinggal di Betania, kampung Maria dan adiknya Marta.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 4, '2 Maria ialah perempuan yang pernah meminyaki kaki Tuhan dengan minyak mur dan menyekanya dengan rambutnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 5, '3 Dan Lazarus yang sakit itu adalah saudaranya. Kedua perempuan itu mengirim kabar kepada Yesus: "Tuhan, dia yang Engkau kasihi, sakit."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 6, '4 Ketika Yesus mendengar kabar itu, Ia berkata: "Penyakit itu tidak akan membawa kematian, tetapi akan menyatakan kemuliaan Allah, sebab oleh penyakit itu Anak Allah akan dimuliakan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 7, '5 Yesus memang mengasihi Marta dan kakaknya dan Lazarus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 8, '6 Namun setelah didengar-Nya, bahwa Lazarus sakit, Ia sengaja tinggal dua hari lagi di tempat, di mana Ia berada;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 9, '7 tetapi sesudah itu Ia berkata kepada murid-murid-Nya: "Mari kita kembali lagi ke Yudea."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 10, '8 Murid-murid itu berkata kepada-Nya: "Rabi, baru-baru ini orang-orang Yahudi mencoba melempari Engkau, masih maukah Engkau kembali ke sana?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 11, '9 Jawab Yesus: "Bukankah ada dua belas jam dalam satu hari? Siapa yang berjalan pada siang hari, kakinya tidak terantuk, karena ia melihat terang dunia ini.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 12, '10 Tetapi jikalau seorang berjalan pada malam hari, kakinya terantuk, karena terang tidak ada di dalam dirinya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 13, '11 Demikianlah perkataan-Nya, dan sesudah itu Ia berkata kepada mereka: "Lazarus, saudara kita, telah tertidur, tetapi Aku pergi ke sana untuk membangunkan dia dari tidurnya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 14, '12 Maka kata murid-murid itu kepada-Nya: "Tuhan, jikalau ia tertidur, ia akan sembuh."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 15, '13 Tetapi maksud Yesus ialah tertidur dalam arti mati, sedangkan sangka mereka Yesus berkata tentang tertidur dalam arti biasa.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 16, '14 Karena itu Yesus berkata dengan terus terang: "Lazarus sudah mati;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 17, '15 tetapi syukurlah Aku tidak hadir pada waktu itu, sebab demikian lebih baik bagimu, supaya kamu dapat belajar percaya. Marilah kita pergi sekarang kepadanya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 18, '16 Lalu Tomas, yang disebut Didimus, berkata kepada teman-temannya, yaitu murid-murid yang lain: "Marilah kita pergi juga untuk mati bersama-sama dengan Dia."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 19, '17 Maka ketika Yesus tiba, didapati-Nya Lazarus telah empat hari berbaring di dalam kubur.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 20, '18 Betania terletak dekat Yerusalem, kira-kira dua mil jauhnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 21, '19 Di situ banyak orang Yahudi telah datang kepada Marta dan Maria untuk menghibur mereka berhubung dengan kematian saudaranya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 22, '20 Ketika Marta mendengar, bahwa Yesus datang, ia pergi mendapatkan-Nya. Tetapi Maria tinggal di rumah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 23, '21 Maka kata Marta kepada Yesus: "Tuhan, sekiranya Engkau ada di sini, saudaraku pasti tidak mati.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 24, '22 Tetapi sekarangpun aku tahu, bahwa Allah akan memberikan kepada-Mu segala sesuatu yang Engkau minta kepada-Nya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 25, '23 Kata Yesus kepada Marta: "Saudaramu akan bangkit."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 26, '24 Kata Marta kepada-Nya: "Aku tahu bahwa ia akan bangkit pada waktu orang-orang bangkit pada akhir zaman."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 27, '25 Jawab Yesus: "Akulah kebangkitan dan hidup; barangsiapa percaya kepada-Ku, ia akan hidup walaupun ia sudah mati,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 28, '26 dan setiap orang yang hidup dan yang percaya kepada-Ku, tidak akan mati selama-lamanya. Percayakah engkau akan hal ini?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 29, '27 Jawab Marta: "Ya, Tuhan, aku percaya, bahwa Engkaulah Mesias, Anak Allah, Dia yang akan datang ke dalam dunia."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 30, '28 Dan sesudah berkata demikian ia pergi memanggil saudaranya Maria dan berbisik kepadanya: "Guru ada di sana dan Ia memanggil engkau."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 31, '29 Mendengar itu Maria segera bangkit lalu pergi mendapatkan Yesus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 32, '30 Tetapi waktu itu Yesus belum sampai ke dalam kampung itu. Ia masih berada di tempat Marta menjumpai Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 33, '31 Ketika orang-orang Yahudi yang bersama-sama dengan Maria di rumah itu untuk menghiburnya, melihat bahwa Maria segera bangkit dan pergi ke luar, mereka mengikutinya, karena mereka menyangka bahwa ia pergi ke kubur untuk meratap di situ.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 34, '32 Setibanya Maria di tempat Yesus berada dan melihat Dia, tersungkurlah ia di depan kaki-Nya dan berkata kepada-Nya: "Tuhan, sekiranya Engkau ada di sini, saudaraku pasti tidak mati."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 35, '33 Ketika Yesus melihat Maria menangis dan juga orang-orang Yahudi yang datang bersama-sama dia, maka masygullah hati-Nya. Ia sangat terharu dan berkata:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 36, '34 "Di manakah dia kamu baringkan?" Jawab mereka: "Tuhan, marilah dan lihatlah!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 37, '35 Maka menangislah Yesus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 38, '36 Kata orang-orang Yahudi: "Lihatlah, betapa kasih-Nya kepadanya!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 39, '37 Tetapi beberapa orang di antaranya berkata: "Ia yang memelekkan mata orang buta, tidak sanggupkah Ia bertindak, sehingga orang ini tidak mati?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 40, '38 Maka masygullah pula hati Yesus, lalu Ia pergi ke kubur itu. Kubur itu adalah sebuah gua yang ditutup dengan batu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 41, '39 Kata Yesus: "Angkat batu itu!" Marta, saudara orang yang meninggal itu, berkata kepada-Nya: "Tuhan, ia sudah berbau, sebab sudah empat hari ia mati."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 42, '40 Jawab Yesus: "Bukankah sudah Kukatakan kepadamu: Jikalau engkau percaya engkau akan melihat kemuliaan Allah?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 43, '41 Maka mereka mengangkat batu itu. Lalu Yesus menengadah ke atas dan berkata: "Bapa, Aku mengucap syukur kepada-Mu, karena Engkau telah mendengarkan Aku.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 44, '42 Aku tahu, bahwa Engkau selalu mendengarkan Aku, tetapi oleh karena orang banyak yang berdiri di sini mengelilingi Aku, Aku mengatakannya, supaya mereka percaya, bahwa Engkaulah yang telah mengutus Aku."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 45, '43 Dan sesudah berkata demikian, berserulah Ia dengan suara keras: "Lazarus, marilah ke luar!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 46, '44 Orang yang telah mati itu datang ke luar, kaki dan tangannya masih terikat dengan kain kapan dan mukanya tertutup dengan kain peluh. Kata Yesus kepada mereka: "Bukalah kain-kain itu dan biarkan ia pergi."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 47, '149. Pertobatan dari Teman-teman Maria Orang Betania');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 48, '(Yohanes 11:45-46)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 49, '45 Banyak di antara orang-orang Yahudi yang datang melawat Maria dan yang menyaksikan sendiri apa yang telah dibuat Yesus, percaya kepada-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(45, 50, '46 Tetapi ada yang pergi kepada orang-orang Farisi dan menceriterakan kepada mereka, apa yang telah dibuat Yesus itu.');
