INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 1, '150. Perencanaan Pembunuhan oleh Imam Kepala dan Farisi');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 2, '(Yohanes 11:47-53)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 3, '47 Lalu imam-imam kepala dan orang-orang Farisi memanggil Mahkamah Agama untuk berkumpul dan mereka berkata: "Apakah yang harus kita buat? Sebab orang itu membuat banyak mujizat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 4, '48 Apabila kita biarkan Dia, maka semua orang akan percaya kepada-Nya dan orang-orang Roma akan datang dan akan merampas tempat suci kita serta bangsa kita."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 5, '49 Tetapi seorang di antara mereka, yaitu Kayafas, Imam Besar pada tahun itu, berkata kepada mereka: "Kamu tidak tahu apa-apa,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 6, '50 dan kamu tidak insaf, bahwa lebih berguna bagimu, jika satu orang mati untuk bangsa kita dari pada seluruh bangsa kita ini binasa."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 7, '51 Hal itu dikatakannya bukan dari dirinya sendiri, tetapi sebagai Imam Besar pada tahun itu ia bernubuat, bahwa Yesus akan mati untuk bangsa itu,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 8, '52 dan bukan untuk bangsa itu saja, tetapi juga untuk mengumpulkan dan mempersatukan anak-anak Allah yang tercerai-berai.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 9, '53 Mulai dari hari itu mereka sepakat untuk membunuh Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 10, '151. Yesus Mengundurkan Diri dari Muka Umum');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 11, '(Yohanes 11:54-54)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 12, '54 Karena itu Yesus tidak tampil lagi di muka umum di antara orang-orang Yahudi, Ia berangkat dari situ ke daerah dekat padang gurun, ke sebuah kota yang bernama Efraim, dan di situ Ia tinggal bersama-sama murid-murid-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 13, '152. Yesus Menyembuhan 10 Orang Kusta');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 14, '(Lukas 17:11-19)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 15, '11 Dalam perjalanan-Nya ke Yerusalem Yesus menyusur perbatasan Samaria dan Galilea.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 16, '12 Ketika Ia memasuki suatu desa datanglah sepuluh orang kusta menemui Dia. Mereka tinggal berdiri agak jauh');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 17, '13 dan berteriak: "Yesus, Guru, kasihanilah kami!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 18, '14 Lalu Ia memandang mereka dan berkata: "Pergilah, perlihatkanlah dirimu kepada imam-imam." Dan sementara mereka di tengah jalan mereka menjadi tahir.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 19, '15 Seorang dari mereka, ketika melihat bahwa ia telah sembuh, kembali sambil memuliakan Allah dengan suara nyaring,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 20, '16 lalu tersungkur di depan kaki Yesus dan mengucap syukur kepada-Nya. Orang itu adalah seorang Samaria.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 21, '17 Lalu Yesus berkata: "Bukankah kesepuluh orang tadi semuanya telah menjadi tahir? Di manakah yang sembilan orang itu?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 22, '18 Tidak adakah di antara mereka yang kembali untuk memuliakan Allah selain dari pada orang asing ini?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 23, '19 Lalu Ia berkata kepada orang itu: "Berdirilah dan pergilah, imanmu telah menyelamatkan engkau."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 24, '153. Tanda-tanda Akhir Zaman');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 25, '(Lukas 17:20-37)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 26, '20 Atas pertanyaan orang-orang Farisi, apabila Kerajaan Allah akan datang, Yesus menjawab, kata-Nya: "Kerajaan Allah datang tanpa tanda-tanda lahiriah,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 27, '21 juga orang tidak dapat mengatakan: Lihat, ia ada di sini atau ia ada di sana! Sebab sesungguhnya Kerajaan Allah ada di antara kamu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 28, '22 Dan Ia berkata kepada murid-murid-Nya: "Akan datang waktunya kamu ingin melihat satu dari pada hari-hari Anak Manusia itu dan kamu tidak akan melihatnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 29, '23 Dan orang akan berkata kepadamu: Lihat, ia ada di sana; lihat, ia ada di sini! Jangan kamu pergi ke situ, jangan kamu ikut.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 30, '24 Sebab sama seperti kilat memancar dari ujung langit yang satu ke ujung langit yang lain, demikian pulalah kelak halnya Anak Manusia pada hari kedatangan-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 31, '25 Tetapi Ia harus menanggung banyak penderitaan dahulu dan ditolak oleh angkatan ini.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 32, '26 Dan sama seperti terjadi pada zaman Nuh, demikian pulalah halnya kelak pada hari-hari Anak Manusia:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 33, '27 mereka makan dan minum, mereka kawin dan dikawinkan, sampai kepada hari Nuh masuk ke dalam bahtera, lalu datanglah air bah dan membinasakan mereka semua.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 34, '28 Demikian juga seperti yang terjadi di zaman Lot: mereka makan dan minum, mereka membeli dan menjual, mereka menanam dan membangun.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 35, '29 Tetapi pada hari Lot pergi keluar dari Sodom turunlah hujan api dan hujan belerang dari langit dan membinasakan mereka semua.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 36, '30 Demikianlah halnya kelak pada hari, di mana Anak Manusia menyatakan diri-Nya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 37, '31 Barangsiapa pada hari itu sedang di peranginan di atas rumah dan barang-barangnya ada di dalam rumah, janganlah ia turun untuk mengambilnya, dan demikian juga orang yang sedang di ladang, janganlah ia kembali.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 38, '32 Ingatlah akan isteri Lot!');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 39, '33 Barangsiapa berusaha memelihara nyawanya, ia akan kehilangan nyawanya, dan barangsiapa kehilangan nyawanya, ia akan menyelamatkannya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 40, '34 Aku berkata kepadamu: Pada malam itu ada dua orang di atas satu tempat tidur, yang seorang akan dibawa dan yang lain akan ditinggalkan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 41, '35 Ada dua orang perempuan bersama-sama mengilang, yang seorang akan dibawa dan yang lain akan ditinggalkan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 42, '36 (Kalau ada dua orang di ladang, yang seorang akan dibawa dan yang lain akan ditinggalkan.)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(46, 43, '37 Kata mereka kepada Yesus: "Di mana, Tuhan?" Kata-Nya kepada mereka: "Di mana ada mayat, di situ berkerumun burung nasar."');
