INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 1, '161. Menyembuhkan si Buta Bartimeus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 2, '(Markus 10:46-52, <i>Matius 20:29-34</i>, <b>Lukas 18:35-43</b>)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 3, '46 Lalu tibalah Yesus dan murid-murid-Nya di Yerikho. Dan ketika Yesus keluar dari Yerikho, bersama-sama dengan murid-murid-Nya dan orang banyak yang berbondong-bondong, <i>mengikuti Dia</i>, <b>waktu Yesus hampir tiba di Yerikho</b>, <i>ada dua orang buta</i> [salah satu orang tersebut] seorang pengemis yang buta, bernama Bartimeus, anak Timeus, duduk di pinggir jalan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 4, '<b>36 Waktu orang itu mendengar orang banyak lewat, ia bertanya: "Apa itu?"</b>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 5, '<b>37 Kata orang kepadanya: "Yesus orang Nazaret lewat."</b>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 6, '47 Ketika didengarnya, bahwa itu adalah Yesus orang Nazaret <i>lewat</i>, mulailah (<i>mereka</i>) ia berseru: "Yesus, Anak Daud, kasihanilah (<i>kami</i>) aku!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 7, '48 Banyak orang menegornya supaya (<i>mereka</i>) ia diam. Namun semakin keras (<i>mereka</i>) ia berseru: "<i>Tuhan,</i> Anak Daud, kasihanilah (<i>kami</i>) aku!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 8, '49 Lalu Yesus berhenti dan <b>menyuruh membawa orang itu kepadaNya dan</b> berkata: "Panggillah (<i>mereka</i>) dia!" Mereka memanggil orang-[orang] buta itu dan berkata kepadanya: "Kuatkan hatimu, berdirilah, Ia memanggil (<i>kamu</i>) engkau."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 9, '50 Lalu ia menanggalkan jubahnya, ia segera berdiri dan pergi mendapatkan Yesus. <b>Dan ketika ia telah berada di dekatNya.</b>');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 10, '51 Tanya Yesus kepadanya: "Apa yang kaukehendaki supaya Aku perbuat bagi(<i>kamu</i>)mu?" Jawab orang buta itu: "Rabuni, supaya (<i>mata kami</i>) aku dapat melihat!"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 11, '52 Lalu kata Yesus kepadanya: "Pergilah, <b>melihatlah engkau,</b> imanmu telah menyelamatkan engkau!" Pada saat itu juga melihatlah (<i>mereka</i>) ia, lalu (<i>mereka</i>) ia mengikuti Yesus dalam perjalanan-Nya <b>sambil memuliakan Allah. Seluruh rakyat melihat hal itu dan memuji-muji Allah</b>.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 12, '162.  Pertobatan Zakheus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 13, '(Lukas 19:1-10)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 14, '1 Yesus masuk ke kota Yerikho dan berjalan terus melintasi kota itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 15, '2 Di situ ada seorang bernama Zakheus, kepala pemungut cukai, dan ia seorang yang kaya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 16, '3 Ia berusaha untuk melihat orang apakah Yesus itu, tetapi ia tidak berhasil karena orang banyak, sebab badannya pendek.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 17, '4 Maka berlarilah ia mendahului orang banyak, lalu memanjat pohon ara untuk melihat Yesus, yang akan lewat di situ.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 18, '5 Ketika Yesus sampai ke tempat itu, Ia melihat ke atas dan berkata: "Zakheus, segeralah turun, sebab hari ini Aku harus menumpang di rumahmu."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 19, '6 Lalu Zakheus segera turun dan menerima Yesus dengan sukacita.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 20, '7 Tetapi semua orang yang melihat hal itu bersungut-sungut, katanya: "Ia menumpang di rumah orang berdosa."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 21, '8 Tetapi Zakheus berdiri dan berkata kepada Tuhan: "Tuhan, setengah dari milikku akan kuberikan kepada orang miskin dan sekiranya ada sesuatu yang kuperas dari seseorang akan kukembalikan empat kali lipat."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 22, '9 Kata Yesus kepadanya: "Hari ini telah terjadi keselamatan kepada rumah ini, karena orang inipun anak Abraham.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 23, '10 Sebab Anak Manusia datang untuk mencari dan menyelamatkan yang hilang."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 24, '163. Perumpamaan tentang Mata Uang');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 25, '(Lukas 19:11-28)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 26, '11 Untuk mereka yang mendengarkan Dia di situ, Yesus melanjutkan perkataan-Nya dengan suatu perumpamaan, sebab Ia sudah dekat Yerusalem dan mereka menyangka, bahwa Kerajaan Allah akan segera kelihatan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 27, '12 Maka Ia berkata: "Ada seorang bangsawan berangkat ke sebuah negeri yang jauh untuk dinobatkan menjadi raja di situ dan setelah itu baru kembali.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 28, '13 Ia memanggil sepuluh orang hambanya dan memberikan sepuluh mina kepada mereka, katanya: Pakailah ini untuk berdagang sampai aku datang kembali.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 29, '14 Akan tetapi orang-orang sebangsanya membenci dia, lalu mengirimkan utusan menyusul dia untuk mengatakan: Kami tidak mau orang ini menjadi raja atas kami.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 30, '15 Dan terjadilah, ketika ia kembali, setelah ia dinobatkan menjadi raja, ia menyuruh memanggil hamba-hambanya, yang telah diberinya uang itu, untuk mengetahui berapa hasil dagang mereka masing-masing.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 31, '16 Orang yang pertama datang dan berkata: Tuan, mina tuan yang satu itu telah menghasilkan sepuluh mina.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 32, '17 Katanya kepada orang itu: Baik sekali perbuatanmu itu, hai hamba yang baik; engkau telah setia dalam perkara kecil, karena itu terimalah kekuasaan atas sepuluh kota.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 33, '18 Datanglah yang kedua dan berkata: Tuan, mina tuan telah menghasilkan lima mina.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 34, '19 Katanya kepada orang itu: Dan engkau, kuasailah lima kota.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 35, '20 Dan hamba yang ketiga datang dan berkata: Tuan, inilah mina tuan, aku telah menyimpannya dalam sapu tangan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 36, '21 Sebab aku takut akan tuan, karena tuan adalah manusia yang keras; tuan mengambil apa yang tidak pernah tuan taruh dan tuan menuai apa yang tidak tuan tabur.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 37, '22 Katanya kepada orang itu: Hai hamba yang jahat, aku akan menghakimi engkau menurut perkataanmu sendiri. Engkau sudah tahu bahwa aku adalah orang yang keras, yang mengambil apa yang tidak pernah aku taruh dan menuai apa yang tidak aku tabur.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 38, '23 Jika demikian, mengapa uangku itu tidak kauberikan kepada orang yang menjalankan uang? Maka sekembaliku aku dapat mengambilnya serta dengan bunganya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 39, '24 Lalu katanya kepada orang-orang yang berdiri di situ: Ambillah mina yang satu itu dari padanya dan berikanlah kepada orang yang mempunyai sepuluh mina itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 40, '25 Kata mereka kepadanya: Tuan, ia sudah mempunyai sepuluh mina.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 41, '26 Jawabnya: Aku berkata kepadamu: Setiap orang yang mempunyai, kepadanya akan diberi, tetapi siapa yang tidak mempunyai, dari padanya akan diambil, juga apa yang ada padanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 42, '27 Akan tetapi semua seteruku ini, yang tidak suka aku menjadi rajanya, bawalah mereka ke mari dan bunuhlah mereka di depan mataku."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 43, '28 Dan setelah mengatakan semuanya itu Yesus mendahului mereka dan meneruskan perjalanan-Nya ke Yerusalem.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 44, '164. Ketibaan di Betania di Daerah Yudea');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 45, '(Yohanes 11:55-12:1;9-11)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 46, '(Yohanes 11:55-57)');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 47, '55 Pada waktu itu hari raya Paskah orang Yahudi sudah dekat dan banyak orang dari negeri itu berangkat ke Yerusalem untuk menyucikan diri sebelum Paskah itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 48, '56 Mereka mencari Yesus dan sambil berdiri di dalam Bait Allah, mereka berkata seorang kepada yang lain: "Bagaimana pendapatmu? Akan datang jugakah Ia ke pesta?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 49, '57 Sementara itu imam-imam kepala dan orang-orang Farisi telah memberikan perintah supaya setiap orang yang tahu di mana Dia berada memberitahukannya, agar mereka dapat menangkap Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 50, '1 Enam hari sebelum Paskah Yesus datang ke Betania, tempat tinggal Lazarus yang dibangkitkan Yesus dari antara orang mati.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 51, '9 Sejumlah besar orang Yahudi mendengar, bahwa Yesus ada di sana dan mereka datang bukan hanya karena Yesus, melainkan juga untuk melihat Lazarus, yang telah dibangkitkan-Nya dari antara orang mati.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 52, '10 Lalu imam-imam kepala bermupakat untuk membunuh Lazarus juga,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(49, 53, '11 sebab karena dia banyak orang Yahudi meninggalkan mereka dan percaya kepada Yesus.');
