INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 1, 'II. Pengumuman Kelahiran');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 2, 'II.a Pengumuman Kelahiran Yohanes Pembaptis');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 3, '5. Pengumuman Kelahiran Yohanes Pembaptis kepada Zakharia');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 4, 'Lukas 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 5, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 6, '5 Pada zaman Herodes, raja Yudea, adalah seorang imam yang bernama Zakharia dari rombongan Abia. Isterinya juga berasal dari keturunan Harun, namanya Elisabet.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 7, '6 Keduanya adalah benar di hadapan Allah dan hidup menurut segala perintah dan ketetapan Tuhan dengan tidak bercacat.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 8, '7 Tetapi mereka tidak mempunyai anak, sebab Elisabet mandul dan keduanya telah lanjut umurnya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 9, '8 Pada suatu kali, waktu tiba giliran rombongannya, Zakharia melakukan tugas keimaman di hadapan Tuhan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 10, '9 Sebab ketika diundi, sebagaimana lazimnya, untuk menentukan imam yang bertugas, dialah yang ditunjuk untuk masuk ke dalam Bait Suci dan membakar ukupan di situ.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 11, '10 Sementara itu seluruh umat berkumpul di luar dan sembahyang. Waktu itu adalah waktu pembakaran ukupan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 12, '11 Maka tampaklah kepada Zakharia seorang malaikat Tuhan berdiri di sebelah kanan mezbah pembakaran ukupan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 13, '12 Melihat hal itu ia terkejut dan menjadi takut.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 14, '13 Tetapi malaikat itu berkata kepadanya: "Jangan takut, hai Zakharia, sebab doamu telah dikabulkan dan Elisabet, isterimu, akan melahirkan seorang anak laki-laki bagimu dan haruslah engkau menamai dia Yohanes.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 15, '14 Engkau akan bersukacita dan bergembira, bahkan banyak orang akan bersukacita atas kelahirannya itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 16, '15 Sebab ia akan besar di hadapan Tuhan dan ia tidak akan minum anggur atau minuman keras dan ia akan penuh dengan Roh Kudus mulai dari rahim ibunya;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 17, '16 ia akan membuat banyak orang Israel berbalik kepada Tuhan, Allah mereka,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 18, '17 dan ia akan berjalan mendahului Tuhan dalam roh dan kuasa Elia untuk membuat hati bapa-bapa berbalik kepada anak-anaknya dan hati orang-orang durhaka kepada pikiran orang-orang benar dan dengan demikian menyiapkan bagi Tuhan suatu umat yang layak bagi-Nya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 19, '18 Lalu kata Zakharia kepada malaikat itu: "Bagaimanakah aku tahu, bahwa hal ini akan terjadi? Sebab aku sudah tua dan isteriku sudah lanjut umurnya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 20, '19 Jawab malaikat itu kepadanya: "Akulah Gabriel yang melayani Allah dan aku telah diutus untuk berbicara dengan engkau dan untuk menyampaikan kabar baik ini kepadamu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 21, '20 Sesungguhnya engkau akan menjadi bisu dan tidak dapat berkata-kata sampai kepada hari, di mana semuanya ini terjadi, karena engkau tidak percaya akan perkataanku yang akan nyata kebenarannya pada waktunya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 22, '21 Sementara itu orang banyak menanti-nantikan Zakharia. Mereka menjadi heran, bahwa ia begitu lama berada dalam Bait Suci.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 23, '22 Ketika ia keluar, ia tidak dapat berkata-kata kepada mereka dan mengertilah mereka, bahwa ia telah melihat suatu penglihatan di dalam Bait Suci. Lalu ia memberi isyarat kepada mereka, sebab ia tetap bisu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 24, '23 Ketika selesai jangka waktu tugas jabatannya, ia pulang ke rumah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 25, '24 Beberapa lama kemudian Elisabet, isterinya, mengandung dan selama lima bulan ia tidak menampakkan diri, katanya:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(5, 26, '25 "Inilah suatu perbuatan Tuhan bagiku, dan sekarang Ia berkenan menghapuskan aibku di depan orang."');