INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 1, 'II.b Pengumuman Kelahiran Yesus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 2, '6. Kepada Maria');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 3, 'Lukas 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 5, '26 Dalam bulan yang keenam Allah menyuruh malaikat Gabriel pergi ke sebuah kota di Galilea bernama Nazaret,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 6, '27 kepada seorang perawan yang bertunangan dengan seorang bernama Yusuf dari keluarga Daud; nama perawan itu Maria.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 7, '28 Ketika malaikat itu masuk ke rumah Maria, ia berkata: "Salam, hai engkau yang dikaruniai, Tuhan menyertai engkau."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 8, '29 Maria terkejut mendengar perkataan itu, lalu bertanya di dalam hatinya, apakah arti salam itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 9, '30 Kata malaikat itu kepadanya: "Jangan takut, hai Maria, sebab engkau beroleh kasih karunia di hadapan Allah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 10, '31 Sesungguhnya engkau akan mengandung dan akan melahirkan seorang anak laki-laki dan hendaklah engkau menamai Dia Yesus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 11, '32 Ia akan menjadi besar dan akan disebut Anak Allah Yang Mahatinggi. Dan Tuhan Allah akan mengaruniakan kepada-Nya takhta Daud, bapa leluhur-Nya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 12, '33 dan Ia akan menjadi raja atas kaum keturunan Yakub sampai selama-lamanya dan Kerajaan-Nya tidak akan berkesudahan."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 13, '34 Kata Maria kepada malaikat itu: "Bagaimana hal itu mungkin terjadi, karena aku belum bersuami?"');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 14, '35 Jawab malaikat itu kepadanya: "Roh Kudus akan turun atasmu dan kuasa Allah Yang Mahatinggi akan menaungi engkau; sebab itu anak yang akan kaulahirkan itu akan disebut kudus, Anak Allah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 15, '36 Dan sesungguhnya, Elisabet, sanakmu itu, iapun sedang mengandung seorang anak laki-laki pada hari tuanya dan inilah bulan yang keenam bagi dia, yang disebut mandul itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 16, '37 Sebab bagi Allah tidak ada yang mustahil."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 17, '38 Kata Maria: "Sesungguhnya aku ini adalah hamba Tuhan; jadilah padaku menurut perkataanmu itu." Lalu malaikat itu meninggalkan dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 18, '7. Kepada Yusuf');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 19, 'Matius 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 20, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 21, '18 Kelahiran Yesus Kristus adalah seperti berikut: Pada waktu Maria, ibu-Nya, bertunangan dengan Yusuf, ternyata ia mengandung dari Roh Kudus, sebelum mereka hidup sebagai suami isteri.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 22, '19 Karena Yusuf suaminya, seorang yang tulus hati dan tidak mau mencemarkan nama isterinya di muka umum, ia bermaksud menceraikannya dengan diam-diam.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 23, '20 Tetapi ketika ia mempertimbangkan maksud itu, malaikat Tuhan nampak kepadanya dalam mimpi dan berkata: "Yusuf, anak Daud, janganlah engkau takut mengambil Maria sebagai isterimu, sebab anak yang di dalam kandungannya adalah dari Roh Kudus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 24, '21 Ia akan melahirkan anak laki-laki dan engkau akan menamakan Dia Yesus, karena Dialah yang akan menyelamatkan umat-Nya dari dosa mereka."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 25, '22 Hal itu terjadi supaya genaplah yang difirmankan Tuhan oleh nabi:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 26, '23 "Sesungguhnya, anak dara itu akan mengandung dan melahirkan seorang anak laki-laki, dan mereka akan menamakan Dia Imanuel" --yang berarti: Allah menyertai kita.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 27, '24 Sesudah bangun dari tidurnya, Yusuf berbuat seperti yang diperintahkan malaikat Tuhan itu kepadanya. Ia mengambil Maria sebagai isterinya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(6, 28, '25 tetapi tidak bersetubuh dengan dia sampai ia melahirkan anaknya laki-laki dan Yusuf menamakan Dia Yesus.');
