INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 1, '8. Nyanyian Pujian Elisabet');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 2, 'Lukas 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 3, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 4, '39 Beberapa waktu kemudian berangkatlah Maria dan langsung berjalan ke pegunungan menuju sebuah kota di Yehuda.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 5, '40 Di situ ia masuk ke rumah Zakharia dan memberi salam kepada Elisabet.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 6, '41 Dan ketika Elisabet mendengar salam Maria, melonjaklah anak yang di dalam rahimnya dan Elisabetpun penuh dengan Roh Kudus,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 7, '42 lalu berseru dengan suara nyaring: "Diberkatilah engkau di antara semua perempuan dan diberkatilah buah rahimmu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 8, '43 Siapakah aku ini sampai ibu Tuhanku datang mengunjungi aku?');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 9, '44 Sebab sesungguhnya, ketika salammu sampai kepada telingaku, anak yang di dalam rahimku melonjak kegirangan.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 10, '45 Dan berbahagialah ia, yang telah percaya, sebab apa yang dikatakan kepadanya dari Tuhan, akan terlaksana."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 11, '9. Nyanyian Pujian Maria');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 12, 'Lukas 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 13, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 14, '46 Lalu kata Maria: "Jiwaku memuliakan Tuhan,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 15, '47 dan hatiku bergembira karena Allah, Juruselamatku,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 16, '48 sebab Ia telah memperhatikan kerendahan hamba-Nya. Sesungguhnya, mulai dari sekarang segala keturunan akan menyebut aku berbahagia,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 17, '49 karena Yang Mahakuasa telah melakukan perbuatan-perbuatan besar kepadaku dan nama-Nya adalah kudus.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 18, '50 Dan rahmat-Nya turun-temurun atas orang yang takut akan Dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 19, '51 Ia memperlihatkan kuasa-Nya dengan perbuatan tangan-Nya dan mencerai-beraikan orang-orang yang congkak hatinya;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 20, '52 Ia menurunkan orang-orang yang berkuasa dari takhtanya dan meninggikan orang-orang yang rendah;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 21, '53 Ia melimpahkan segala yang baik kepada orang yang lapar, dan menyuruh orang yang kaya pergi dengan tangan hampa;');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 22, '54 Ia menolong Israel, hamba-Nya, karena Ia mengingat rahmat-Nya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 23, '55 seperti yang dijanjikan-Nya kepada nenek moyang kita, kepada Abraham dan keturunannya untuk selama-lamanya."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(7, 24, '56 Dan Maria tinggal kira-kira tiga bulan lamanya bersama dengan Elisabet, lalu pulang kembali ke rumahnya.');
