INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 1, 'IV. Kelahiran Yohanes Pembaptis dan Yesus Kristus');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 2, '10. Kelahiran Yohanes Pembaptis');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 3, 'Lukas 1');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 4, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 5, '57 Kemudian genaplah bulannya bagi Elisabet untuk bersalin dan iapun melahirkan seorang anak laki-laki.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 6, '58 Ketika tetangga-tetangganya serta sanak saudaranya mendengar, bahwa Tuhan telah menunjukkan rahmat-Nya yang begitu besar kepadanya, bersukacitalah mereka bersama-sama dengan dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 7, '59 Maka datanglah mereka pada hari yang kedelapan untuk menyunatkan anak itu dan mereka hendak menamai dia Zakharia menurut nama bapanya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 8, '60 tetapi ibunya berkata: "Jangan, ia harus dinamai Yohanes."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 9, '61 Kata mereka kepadanya: "Tidak ada di antara sanak saudaramu yang bernama demikian."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 10, '62 Lalu mereka memberi isyarat kepada bapanya untuk bertanya nama apa yang hendak diberikannya kepada anaknya itu.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 11, '63 Ia meminta batu tulis, lalu menuliskan kata-kata ini: "Namanya adalah Yohanes." Dan merekapun heran semuanya.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 12, '64 Dan seketika itu juga terbukalah mulutnya dan terlepaslah lidahnya, lalu ia berkata-kata dan memuji Allah.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 13, '65 Maka ketakutanlah semua orang yang tinggal di sekitarnya, dan segala peristiwa itu menjadi buah tutur di seluruh pegunungan Yudea.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 14, '66 Dan semua orang, yang mendengarnya, merenungkannya dan berkata: "Menjadi apakah anak ini nanti?" Sebab tangan Tuhan menyertai dia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 15, '67 Dan Zakharia, ayahnya, penuh dengan Roh Kudus, lalu bernubuat, katanya:');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 16, '68 "Terpujilah Tuhan, Allah Israel, sebab Ia melawat umat-Nya dan membawa kelepasan baginya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 17, '69 Ia menumbuhkan sebuah tanduk keselamatan bagi kita di dalam keturunan Daud, hamba-Nya itu,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 18, '70 --seperti yang telah difirmankan-Nya sejak purbakala oleh mulut nabi-nabi-Nya yang kudus--');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 19, '71 untuk melepaskan kita dari musuh-musuh kita dan dari tangan semua orang yang membenci kita,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 20, '72 untuk menunjukkan rahmat-Nya kepada nenek moyang kita dan mengingat akan perjanjian-Nya yang kudus,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 21, '73 yaitu sumpah yang diucapkan-Nya kepada Abraham, bapa leluhur kita, bahwa Ia mengaruniai kita,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 22, '74 supaya kita, terlepas dari tangan musuh, dapat beribadah kepada-Nya tanpa takut,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 23, '75 dalam kekudusan dan kebenaran di hadapan-Nya seumur hidup kita.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 24, '76 Dan engkau, hai anakku, akan disebut nabi Allah Yang Mahatinggi; karena engkau akan berjalan mendahului Tuhan untuk mempersiapkan jalan bagi-Nya,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 25, '77 untuk memberikan kepada umat-Nya pengertian akan keselamatan yang berdasarkan pengampunan dosa-dosa mereka,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 26, '78 oleh rahmat dan belas kasihan dari Allah kita, dengan mana Ia akan melawat kita, Surya pagi dari tempat yang tinggi,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 27, '79 untuk menyinari mereka yang diam dalam kegelapan dan dalam naungan maut untuk mengarahkan kaki kita kepada jalan damai sejahtera."');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(8, 28, '80 Adapun anak itu bertambah besar dan makin kuat rohnya. Dan ia tinggal di padang gurun sampai kepada hari ia harus menampakkan diri kepada Israel.');
