INSERT INTO book ('chapter', 'verse', 'content') VALUES(9, 1, '11. Kelahiran Yesus Sang Mesias');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(9, 2, 'Lukas 2');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(9, 3, '');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(9, 4, '1 Pada waktu itu Kaisar Agustus mengeluarkan suatu perintah, menyuruh mendaftarkan semua orang di seluruh dunia.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(9, 5, '2 Inilah pendaftaran yang pertama kali diadakan sewaktu Kirenius menjadi wali negeri di Siria.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(9, 6, '3 Maka pergilah semua orang mendaftarkan diri, masing-masing di kotanya sendiri.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(9, 7, '4 Demikian juga Yusuf pergi dari kota Nazaret di Galilea ke Yudea, ke kota Daud yang bernama Betlehem, --karena ia berasal dari keluarga dan keturunan Daud--');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(9, 8, '5 supaya didaftarkan bersama-sama dengan Maria, tunangannya, yang sedang mengandung.');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(9, 9, '6 Ketika mereka di situ tibalah waktunya bagi Maria untuk bersalin,');
INSERT INTO book ('chapter', 'verse', 'content') VALUES(9, 10, '7 dan ia melahirkan seorang anak laki-laki, anaknya yang sulung, lalu dibungkusnya dengan lampin dan dibaringkannya di dalam palungan, karena tidak ada tempat bagi mereka di rumah penginapan.');
