INSERT INTO toc ('id', 'title') VALUES('1','Pendahuluan Injil Tuhan Yesus');
INSERT INTO toc ('id', 'title') VALUES('2','Prolog Injil Dalam Injil Yohanes');
INSERT INTO toc ('id', 'title') VALUES('3','Prolog Injil Dalam Injil Lukas');
INSERT INTO toc ('id', 'title') VALUES('4','Silsilah Yesus Kristus');
INSERT INTO toc ('id', 'title') VALUES('5','Pengumuman Kelahiran Yohanes Pembaptis');
INSERT INTO toc ('id', 'title') VALUES('6','Pengumuman Kelahiran Yesus');
INSERT INTO toc ('id', 'title') VALUES('7','Pujian-pujian');
INSERT INTO toc ('id', 'title') VALUES('8','Kelahiran Yohanes Pembaptis');
INSERT INTO toc ('id', 'title') VALUES('9','Kelahiran Yesus Sang Mesias');
INSERT INTO toc ('id', 'title') VALUES('10','Natal Pertama');
INSERT INTO toc ('id', 'title') VALUES('11','Masa Bayi Yesus');
INSERT INTO toc ('id', 'title') VALUES('12','Masa Kanak-kanak Yesus');
INSERT INTO toc ('id', 'title') VALUES('13','Permulaan Pelayanan Yesus Kristus');
INSERT INTO toc ('id', 'title') VALUES('14','Yesus Dibaptis');
INSERT INTO toc ('id', 'title') VALUES('15','Yesus Dicobai');
INSERT INTO toc ('id', 'title') VALUES('16','Kesaksian Yohanes Pembaptis (Yohanes 1:19-34)');
INSERT INTO toc ('id', 'title') VALUES('17','Murid-murid Yesus Yang Pertama');
INSERT INTO toc ('id', 'title') VALUES('18','Mujizad Pertama Di Kana');
INSERT INTO toc ('id', 'title') VALUES('19','Paskah Pertama Dan Yesus Meyucikan Bait Allah Untuk Pertama Kali');
INSERT INTO toc ('id', 'title') VALUES('20','Yesus Mengajar Nikodemus Tentang Kelahiran Kembali');
INSERT INTO toc ('id', 'title') VALUES('21','Pelayanan Kristus Di Yudea');
INSERT INTO toc ('id', 'title') VALUES('22','Pelayanan Yesus Di Daerah Samaria');
INSERT INTO toc ('id', 'title') VALUES('23','Pelayanan Kristus Di Daerah Galilea');
INSERT INTO toc ('id', 'title') VALUES('24','Penginjilan Keliling Yang Pertama');
INSERT INTO toc ('id', 'title') VALUES('25','Yesus Mengajar Di Galilea Untuk Pertama Kali');
INSERT INTO toc ('id', 'title') VALUES('26','Kunjungan Singkat Ke Yerusalem');
INSERT INTO toc ('id', 'title') VALUES('27','Kesetaraan Yesus Dengan Tuhan');
INSERT INTO toc ('id', 'title') VALUES('28','Kembali Ke Galilea');
INSERT INTO toc ('id', 'title') VALUES('29','Periode Kedua Pelayanan Besar Di Galilea');
INSERT INTO toc ('id', 'title') VALUES('30','Penginjilan Keliling Kedua');
INSERT INTO toc ('id', 'title') VALUES('31','Pengajaran Yesus');
INSERT INTO toc ('id', 'title') VALUES('32','Perumpamaan Tentang Kerajaan Allah');
INSERT INTO toc ('id', 'title') VALUES('33','Mujizad-mujizad Yang Dilakukan Oleh Tuhan Yesus');
INSERT INTO toc ('id', 'title') VALUES('34','Penginjilan Keliling Yang Ketiga');
INSERT INTO toc ('id', 'title') VALUES('35','Pelayanan Di Sekitar Galilea');
INSERT INTO toc ('id', 'title') VALUES('36','Periode Ketiga Pelayanan Yesus Di Galilea');
INSERT INTO toc ('id', 'title') VALUES('37','Kembali Ke Galilea');
INSERT INTO toc ('id', 'title') VALUES('38','Kunjungan Ke Kaisarea Filipi');
INSERT INTO toc ('id', 'title') VALUES('39','Kembali Ke Kapernaum');
INSERT INTO toc ('id', 'title') VALUES('40','Pelayanan Lanjutan Yesus Di Yudea');
INSERT INTO toc ('id', 'title') VALUES('41','Di Yerusalem');
INSERT INTO toc ('id', 'title') VALUES('42','Di Sekitar Yerusalem');
INSERT INTO toc ('id', 'title') VALUES('43','Pelayanan Di Perea');
INSERT INTO toc ('id', 'title') VALUES('44','Perumpamaan Tentang Pemuridan');
INSERT INTO toc ('id', 'title') VALUES('45','Kembali Ke Yudea');
INSERT INTO toc ('id', 'title') VALUES('46','Pelayanan Di Efraim Dan Kembali Ke Yerusalem Melalui Samaria Dan Galilea');
INSERT INTO toc ('id', 'title') VALUES('47','Perumpamaan-perumpamaan Tentang Doa');
INSERT INTO toc ('id', 'title') VALUES('48','Tiba Di Perea');
INSERT INTO toc ('id', 'title') VALUES('49','Menuju Ke Yerusalem Dan Ketibaan Di Betania Dari Yudea');
INSERT INTO toc ('id', 'title') VALUES('50','Kesengsaraan Kristus Minggu');
INSERT INTO toc ('id', 'title') VALUES('51','Senin');
INSERT INTO toc ('id', 'title') VALUES('52','Selasa');
INSERT INTO toc ('id', 'title') VALUES('53','Rabu');
INSERT INTO toc ('id', 'title') VALUES('54','Kamis');
INSERT INTO toc ('id', 'title') VALUES('55','Jum’at Agung');
INSERT INTO toc ('id', 'title') VALUES('56','Yesus Disalib');
INSERT INTO toc ('id', 'title') VALUES('57','Sabtu');
INSERT INTO toc ('id', 'title') VALUES('58','Kebangkitan');
INSERT INTO toc ('id', 'title') VALUES('59','Penampakkan Diri Yesus Yang Bangkit');
INSERT INTO toc ('id', 'title') VALUES('60','Kenaikan Tuhan Yesus');
INSERT INTO toc ('id', 'title') VALUES('61','Tujuan Injil');
INSERT INTO toc ('id', 'title') VALUES('62','Lampiran');
INSERT INTO toc ('id', 'title') VALUES('63','Indeks Alkitab');
